.\" $ Id: $
.\"This is the man page for ~/.micq/micqrc."
.\".TH MICQ 7 "February 15, 2002" "MICQ(7)"
.Dd August 1, 2002
.Dt MICQ 7
.Os MICQ(7)
.Sh ИМЯ
micq интерактивные команды
.Sh ОПИСАНИЕ
Эта страница описывает команды, которые используются в micq. Эта страница
содержит ту же информацию, что и на странице помощи в веб.
.Sh КОМАНДЫ
.Bl -tag -width Fl
.It Ic trans Op Ar lang|nr ...
Переключает язык 
.Ar lang ,
данный iso кодом, или выводит номер перевода
.Ar nr .
Чтобы выбрать язык по умолчанию, описанный переменными окружения
.Ic LANG ,
.Ic LC_ALL
и
.Ic LC_MESSAGES ,
используйте
.Ic \&! ,
.Ic auto
или
.Ic default .
Чтобы отключить перевод вообще, используйте
.Ic \&. ,
.Ic none
или
.Ic unload .
Чтобы получить отладочную информацию, используйте
.Ic debug .
Чтобы получить funny сообщения, используйте
.Ic _fun .
.sp
Файлы из ~/.micq/i18n/*.i18n считаются главнее,
тогда как "funny" сообщения берутся из стандартной директории.
.sp
Фактически, вы можете указать сколь угодно много аргументов, например, чтобы
вывести строку 117 по-немецки и затем переключится на язык по умолчанию,
достаточно ввести "trans de 117 default".
.It Ic tabs 
Показывает список пользователей, которых вы можете перебирать табуляцией.
.It Ic save
Сохраняет текущие настройки в кофигурационный файл, которым является
.Pa ~/.micq/micqrc ,
если не указано другого.
Будьте осторожны, это удалит все комментарии в этом файле.
.It Ic r Op Ar сообщение
Ответить пользователю, который последним послал вам сообщение.  Без
.Ar сообщение
будет включен многолинейный режим.  Чтобы послать многолинейное сообщение,
поставьте точку
.Ic ( . )
на пустой линии в конце сообщения.  Чтобы отменить сообщение, поставьте решетку
.Ic ( # )
на пустой линии в конце сообщения.
.It Ic a Op Ar сообщение
Послать сообщение тому, кто последний получил ваше сообщение.  Смотрите
.Ic r
без указания сообщения
.Ar сообщение .
.It Ic msg Ar uin|ник Ic Op Ar сообщение
Посылает сообщение на
.Ar uin|ник .
Смотрите
.Ic r 
без указания сообщения
.Ar сообщение .
.It Ic url Ar uin|ник Ic Ar url Ar сообщение
Посылает
.Ar сообщение
ссылаясь на
.Ar url
к
.Ar uin|ник .
.It Ic sms Ar мобильник сообщение
Посылает SMS
.Ar сообщение
на сотовый номер
.Ar мобильник ,
который выглядит как +<номер страны><телефон>.
.It Ic msga
Посылает многолинейное сообщение всем из вашего контакт-листа.
Используйте точку
.Ic ( . )
на пустой линии в конце сообщения, чтобы послать сообщение
или поставьте решетку
.Ic ( # )
на пустой линии в конце сообщения, чтобы отменить сообщение.
.It Ic uptime
Показывает сколько времени работает micq.
.It Ic last Op Ar контакт
Показывает список пользователей, которые послали вам сообщения
или последнее сообщение принятое от
.Ar контакт ,
который может быть
.Ar uin
или
.Ar ник .
.It Ic verbose Op Ar verb
Установить уровень вывода micq'а на
.Ar verb ,
или показать текущий уровень. Уровень вывода - это установка флагов:
.Bl -tag -width Fl
.It 128
Дамп входящих и исходящих пакетов.
.It 256
Записывать входящие и исходящие серверные пакеты на диск (~/.micq/debug/packets).
.El
и кое-что еще.
.It Ic clear
Очистить экран.
.It Ic sound Op Ar command
Включить/выключить звук, или установить команду
.Ar command .
.It Ic soundonline Op Ar command
Включить/выключить звук когда пользователь становится online,
или установить команду
.Ar command .
.It Ic soundoffline Op Ar command
Включить/выключить звук когда пользователь становится
.br
offline, или установить команду
.Ar command .
.It Ic q
Выйти из micq'а.
.It Ic auto Op Ar on|off
Включить/выключить автоответы. Если не задано on или off,
то показать автоответ.
.It Ic auto Ar status ответ
Изменить автоответ для режима
.Ar status
на
.Ar ответ .
.It Ic autoaway Op Ar timeout
Включить/выключить autoaway, или поставить таймаут на
.Ar timeout .
.It Ic alter Ar command new
Изменить команду
.Ar command
на
.Ar new .
.It Ic auth Ar uin|ник
Позволить
.Ar uin|ник
добавить вас в их контакт-лист.
.It Ic rand Ar number
Найти пользователя в группе номер
.Ar number .
.It Ic pass Ar password
Меняет ваш icq пароль на
.Ar password . 
.br
Примечание: вам нужно будет сохраниться командой
.Ar save
чтобы пароль записался в ваш
.Pa ~/.micq/micqrc
файл (смотри
.Xr micqrc 7 ) ,
или у вас будет неправильный пароль когда вы будете логиниться.
.It Ic search
.It Ic search Ar email
.It Ic search Ar nick
.It Ic search Ar first last
Поиск пользователя с 
.Ar email
как его электронный адрес, с
.Ar nick
как его ник (не может содержать @), или с
.Ar first
как имя и
.Ar last
как его фамилия. Если не задано аргументов, то спрашивать все это
и более того в интерактивном режиме поиска
.It Ic add Ar uin Op Ar ник
Добавить
.Ar uin
в ваш контакт-лист в виде
.Ar ник ,
или переименовать
.Ar uin
в
.Ar ник .
Если
.Ar ник
не задан, то использовать
.Ar uin
как ник.
.br
Замечание: вам нужно сохраниться командой
.Ar save
чтобы инфа не пропала.
.It Ic rem Ar ник
Удаляет
.Ar ник
из вашего контакт-лист.
.br
Замечание: вам нужно сохраниться командой
.Ar save
чтобы инфа не пропала.
.It Ic togvis Ar ник
Включает вашу видимость для
.Ar ник
даже если вы невидимы.
.It Ic toginvis Ar ник
Включает вашу невидимость для
.Ar ник .
.It Ic togig Ar ник
Включает игнор
.Ar ник'а
на его сообщения и режимы.
.It Ic info Ar uin|ник
Показать всю инфу о
.Ar uin|ник .
.It Ic w
Показать всех людей в вашем контакт-листе.
.It Ic e
Показать всех online пользователей в вашем контакт-листе.
.It Ic wide
Показать всех в вашем контакт-листе в широком формате.
.It Ic ewide
Показать всех online пользователей в вашем контакт-листе в широком формате.
.It Ic s
Показывает ваш статус.
.It Ic i
Показывает всех игнорированных пользователей.
.It Ic status Ar ник
Показывает статус 
.Ar ник'а .
Включает IP адрес, версию протокола ICQ и тип соединения.
.It Ic change Op Ar number
Изменить ваш статус на номер
.Ar number .
Без номера показывает возможные режимы.
.It Ic reg password
Создает новый аккаунт с паролем
.Ar password .
.It Ic online
Изменить статус на online.
.It Ic away
Изменить статус на Ушел.
.It Ic na
Изменить статус на Недоступен.
.It Ic occ             
Изменить статус на Занят.
.It Ic dnd 
Изменить статус на Не беспокоить.
.It Ic ffc
Изменить статус на Готов пообщаться.
.It Ic inv
Изменить статус на Невидимый
.It Ic update
Обновляет вашу основную инфу (email, ник, и т.д.).
.It Ic other
Обновляет другую инфу как возраст и пол.
.It Ic about
Обновляет информацию о вас.
.It Ic set Ar option Ar value
Установить опцию
.Ar option
активной
.Ic on
или
.Ic off .
.Ar option
может быть
.Ic color ,
.Ic funny
или
.Ic quiet .
.It Ic peek Ar ник
Проверяет, является ли
.Ar ник
online или нет. Использует дыру в ICQ протоколе;
другую информацию таким способом не найти.
.It Ic setr Op Ar number
Устанавливает вашу группу номер
.Ar number .
Без аргумента, показывает возможные группы.
.It Ic tcp Ar command Ar uin|ник
Приводит в действие команду
.Ar command
на пользователе по UIN'у
.Ar uin
или прозвищу
.Ar ник .
.Ar command
может быть
.Ic open
чтобы открыть 1-на-1 соединение по TCP к пользователю, или
.Ic close
чтобы закрыть и сбросить данное соединение, или
.Ic off
отключить попытки установить такое соединение для отправки
сообщения пока оно точно не открыто или сброшено
.It Ic conn Op Ar command Ar nr
Вывести все соединения, или выполнить команду
.Ar command
на соединении номер
.Ar nr .
.Ar command
может быть
.Ic open
или
.Ic login
чтобы открыть это соединение, если оно еще не открыто.
.El
.Sh СМОТРИТЕ ТАКЖЕ
.Xr micq 1 ,
.Xr micqrc 5
.Sh АВТОР
Это руководство создано James Morrison
.Pa <ja2morrison@student.math.uwaterloo.ca>
как справка о всех интерактивных командах 
.Ic micq .
