.\"     $Id$ -*- nroff -*-
.\" EN: $Id$
.TH MICQ 1 mICQ
.SH НАЗВАНИЕ
.B mICQ
\- небольшой ICQ-клиент в текстовом режиме
.SH ИСПОЛЬЗОВАНИЕ
.B micq
.I [\-h]
.I [\-c]
.I [\-i <локализация>]
.I [\-b <базовая_директория>]
.I [\-f <файл_конфигурации>]
.I [\-v[уровень]]
.I [\-l <место_для_лога>]
.SH ОПИСАНИЕ
.B mICQ
это клиент для ICQ в текстовом режиме, который поддерживает многие из
возможностей ICQ, обеспечиваемых клиентом от Mirabilis. mICQ позволяет
изменять пароль пользователя, создавать новые аккаунты, обновлять
информацию о пользователе, искать других пользователей, посылать SMS,
открывать прямые соединения, посылать сообщения в кодировке UTF-8,
выполнять команды по любому событию, и так далее.
.SH ПАРАМЕТРЫ
.TP
.BI \-h|\-\-help
Показать краткую справку и выйти
.TP
.BI \-c|\-\-nocolor
Запретить использование цветов.
.TP
.BI \-i|\-\-i18n \ <локализация>
Использовать указанную
.I локализацию
вместо заданной в переменных среды.
.TP
.BI \-b|\-\-basedir \ <базовая_директория>
Указать
.I базовую_директорию
где mICQ будет искать свои файлы, в частности, конфигурационный файл
micqrc.
.TP
.BI \-f|\-\-config \ <файл_конфигурации>
Указать
.I файл_конфигурации
к использованию.
.TP
.BI \-v|\-\-verbose [уровень]
Включить многословность или установить её
.IR уровень .
.TP
.BI \-l|\-\-logplace \ файл|директория
Использовать
.I файл
для записи журнала либо использовать
.I директорию
для создания в ней отдельных журналов по каждому из пользователей.
.SH ВОЗМОЖНОСТИ
.B mICQ
хорошо переносим, он работает на Linux, DOS, OS/2, Win32, BeOS,
AmigaOS, GNU HURD и любой другой современной Unix-системе.
.B mICQ версии 0.4.10
работает на Linux, AIX, HPUX, Tru64, AmigaOS, частично на BeOS и
других юниксах. Однако, на других платформах порт может как
заработать, так и не заработать, желающие это протестировать
приветствуются.
.SH ИСТОРИЯ.
.TP
16 Авг 1998
Мэттью Д. Смит выпустил micq в мир. Далее последовало
12 релизов, датированных вплоть до 25 сентября 1998 г.
.TP
05 Янв 2001
Мэттью Д. Смит погиб в автокатастрофе.
Пользователи взялись за тот micq, что остался, формализовали
его под лицензией BSD и продолжили разработку
.BR mICQ .
.TP
10 Июня 2002
Версия 0.4.9 была выпущена по лицензии GPL, реализуя наконец-то
новую, восьмую версию протокола ICQ, это сделал
R\(:udiger Kuhlmann.
.SH СПИСОК РАССЫЛКИ
Список рассылки mICQ -
.IR micq\-list@micq.org .
Информация о подписке и архивах доступна по адресу
.IR http://www.micq.org/pipermail/micq\-list/ .
.SH СКАЧАТЬ
По HTTP с
.IR http://www.micq.org/download .
.br
Чтобы получить новейшую версию из CVS, наберите
.br
cvs \-d:pserver:anonymous@micq.org:/var/lib/cvs co micq
.br
.SH СМ. ТАКЖЕ
.BR micqrc (5),
.BR micq (7)
.SH ФАЙЛЫ
.TP
.I ~/.micqrc
Старый файл конфигурации для mJCQ \- устарел.
.TP
.I ~/.micq/
Стандартная базовая директория, где mICQ ищет свои файлы.
.TP
.I BASE/micqrc
Конфигурационный файл для mICQ.
.TP
.I BASE/i18n/*.i18n
Локальные замены для файлов перевода mICQ.
.TP
.I BASE/contacts/
Директория, где сохраняются мета-данные о контактах.
.TP
.I BASE/history/
Стандартная директория для файлов журналов.
.TP
.I BASE/files/
Директория, где сохраняются принятые файлы.
.TP
.I BASE/remote-control
Стандартное расположение FIFO, используемого для
удалённого управления.
.TP
.I PREFIX/share/micq/*.i18n
Файлы локализации, содержащие переводы всех строк вывода mICQ.
.SH ОШИБКИ
Сообщения об ошибках или замечания направляйте по адресу:
R\(:udiger Kuhlmann
.I <micq@ruediger\-kuhlmann.de>
(на немецком или английском).
.SH АВТОР
Эта справочная страница была образована Джеймсом Моррисоном
.I <ja2morrison@student.math.uwaterloo.ca>
из минимальной справочной страницы. написанной Джорди Маллахом.
.I <jordi@sindominio.net>
для системы Debian GNU/Linux.
Перевод - Сева Глущенко 2003.
