.\" $Id$ -*- nroff -*-
.\"  EN: <add CVS id like above from the file this translation is synced to>
.TH MICQRC 5 mICQ RU
.SH ИМЯ
.B ~/.micq/micqrc
\- Файл конфигураций для mICQ
.SH Описание
Эта страница описывает файл конфигураций для mICQ. Он сосотоит из 
нескольких частей, которые начинаются с
.BR [часть] ,
где
.B часть - имя раздела.
.SH CONNECTIONS
Раздел
.B Соединений
описывает соединение с ICQ. Обычно, их два, которые относятся
друг к другу: соединение с ICQ сервером, и соединение для прослушивания
один-на-один соединений.
.TP
.BI type \ type\ [auto]
Устанавливает тип соединения на
.IR type ,
который может быть как
.B server
для подключения к ICQ северу, или
.B peer
для соединения, прослушивающего один-на-один подключение. Если
.B auto
задано, создает это соединение при загрузке. Вы, вероятнее всего, напишите это,
если, конечно, у вас не несколько UIN'ов, тогда поставьте соединение подходящее
для вашего UIN'а, который вы используете.
.TP
.BI version \ номер
Устанавливает версию протокола для соединения на
.IR номер .
Учьтите, что для серверного соединения только версия
.B 5
поддерживается, а
.B 8
планируется, и для одни-на-один соединений только
.BR 6 .
.TP
.BI server \ сервер
Устанавливает сервер, к которому подключаться на
.IR сервер .
По умолчанию
.BR icq.icq.com .
Не используется для 1-на-1 соединений.
.TP
.BI port \ порт
Устанавливает порт, к которому подключаться на сервере на
.IR порт ,
или порт для прослушивания 1-на-1 соединений на
.IR порт .
.TP
.BI uin \ UIN
Устанавливает UIN, с которым логиниться на
.IR UIN .
Не используется для 1-на-1 соединений.
.TP
.BI password \ [пароль]
Устанавливает пароль, с которым логиниться на
.IR пароль .
Не используется для 1-на-1 соединений. Если закомментированно, спрашивать пароль при загрузке.
.TP
.BI status \ номер
Устанавливает режим, с которым логиниться на
.IR номер .
Возможные режимы:
.RS
.TP
0
Online
.TP
1
Ушел
.TP
5
Недоступен
.TP
17
Занят
.TP
19
Не беспокоить
.TP
32
Готов пообщаться
.TP
256
Невидимый
.RE
.SH GENERAL
Этот раздел включает опции для SOCKS 5, которые могут быть перемещены
в свою секцию, общие опции и кое-что еще.
.TP
.BI s5_use \ номер
Установите
.I номер
на 0 для выкл и 1 для вкл.
.TP
.BI s5_host \ хост
Соединяет с socks 5 прокси на
.IR хост .
.TP
.BI s5_port \ порт
Соединяет с socks 5 прокси на порт
.IR порт .
.TP
.BI s5_auth \ номер
Установите
.I номер
на 0 если не надо аутентификации и 1 если надо.
.TP
.BI s5_name \ имя
Идентифицировать пользователя как
.I имя
на socks 5 прокси.
.br
.TP
.BI s5_pass \ пароль
Подтвердить подлинность паролем
.I пароль
на socks 5 прокси.
.PP
Теперь опции:
.TP
.BI verbose \ уровень
Устанавливает уровень вывода инфы при загрузке на
.IR уровень .
.TP
.BI auto_away \ время
Устанавливает время для перехода в режим Ушел на
.I время
секунд. Установите
.B 0
чтобы отключить.
.TP
.BI Screen_width \ ширина
Устанавливает ширину экрана на
.IR ширина .
Если не поставлено, то
.BR 0 , \ 80
будет использованно. Используется редко, т.к. ширина может быть уменьшина
во время работы.
.TP
.BI set \ delbs\ on|off
Если установленно
.BR on ,
то клавиша delete будет как backspace. Если
.BR off ,
то останется сама собой.
.TP
.BI set \ russian\ on|off
Включить или отключить перевод русских букв с koi8-r/u на cp1251.
Если вы читаете эту страницу, тогда поставьте on.
.TP
.BI set \ japanese\ on|off
Включить или отключить перевод японских букв с Shift-JIS на EUC.
.TP
.BI set \ funny\ on|off
Включить или отключить "funny" сообщения.
.TP
.BI set \ color\ on|off
Включить или отключить использование цветов.
.TP
.BI set \ hermit\ on|off
Если стоит
.BR on ,
то игнорировать все сообщения пользователей, кроме тех, кто в
вашем контакт-листе.
.TP
.BI set \ log\ on|off
Включить или отключить журнал.
.TP
.BI set \ logonoff\ on|off
Когда включен журнал, включить или отключить запись в журнал смены
online/offline режимов.
.TP
.BI set \ auto\ on|off
Включить или отключить автоответы.
.TP
.BI set \ uinprompt\ on|off
Включить или отключить использование ника, от которого вам пришло сообщение в строке.
.TP
.BI set \ linebreak\ тип
Устанавливает тип обрезки линий входящих сообщений на
.IR тип ,
который может быть
.B simple
просто переносить линии как обычно,
.B break
перенос линии перед каждым сообщением,
.B indent
перенос линии и делать отступ в сообщении и
.B smart
переносить линии, если они больше экрана.
.PP
Наконец, еще кое-что:
.TP
.BI logplace \ файл|дир
Устанавливает файл, в который записывается лог в
.IR файл ,
или директорию, в которую писать логи в
.IR дир .
Учьтите, считается за путь если содержит
.BR / .
.TP
.BI sound \ on|off|cmd
Включить или отключить пиканье. Если ни
.I on
и ни
.IR off ,
то тогда будет запускаться программа вместо пиканья.
.TP
.BI soundonline \ on|off|cmd
Тоже самое, только для случая, когда пользователь переходит в online режим.
.TP
.BI soundoffline \ on|off|cmd
Тоже самое, только для случая, когда пользователь переходит в offline режим.
.TP
.BI receivescript \ cmd
Команда, запускаемая при входящих сообщениях. Оставьте пустым если не надо.
.TP
.BI auto \ режим\ строка
Устанавливает автоответы для режимов
.I режим
на
.IR строка .
Эта опция может быть повторена для всех режимов
.BR away ,
.BR na ,
.BR dnd ,
.BR occ ,
и
.B inv
для
.IR режим .
.SH STRINGS
Этот раздел содержит информацию о изменении команд.
.TP
.BI alter \ old\ new
Переименовать команду
.I old
на
.IR new .
Старая команда может быть использована до тех пор, пока она не конфликтует
.I new
имя.
Для возможных команд, смотрите
.BR micq (7).
Эта опция может быть повторена сколько угодно раз.
.SH CONTACTS
Этот раздел содержит контакт-лист.
.TP
.I [*][~][^] uin ник
Пользователь с UIN'ом
.I uin
будет отображаться ником
.IR ник .
Если
.B *
задано, пользователь может видеть вас когда вы невидимы. Если
.B ~
задано, то вы будете для него всегда offline. Если
.B ^
задано, то игнорировать этого пользователя.
Если uin повторяется несколько раз, то все, кроме первого, считаются иначе называемыми.

Примечание: контакт-лист должен быть последней частью файла.
.SH СМОТРИТЕ ТАКЖЕ
.BR micq (1),
.BR micq (7)
.SH Автор
Эта страница была написана James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca> .
И была переписана для нового синтаксиса файла конфигураций RЭdiger Kuhlmann
.IR <micq@ruediger-kuhlmann.de> .
This man page was translated by "Pest"
.IR <pezt@mail.ru> .
