.\" $Id$
.\"                                      Hey, EMACS: -*- nroff -*-
.Dd August 1, 2002
.Dt MICQ 1
.Os MICQ(1)
.\" Please adjust this date whenever revising the manpage.
.Sh ИМЯ
.Ic micq
\- маленький, ICQ client для работы в текстовом режиме
.Sh ЗАПУСК
.Ic micq Op Ar -v
.Op Ar -f файл
.br
.Sh ОПИСАНИЕ
.Ic mICQ
ICQ клиент, поддерживающий большинство функций ICQ от Mirabillis. 
Micq позволяет менять пароль, создавать новые аккаунты, обновлять инфу 
о пользователе, искать других пользователей и т.д.
.Sh ОПЦИИ
.Bl -tag -width flag
.It Fl v Op Ar уровень
Включает вывод доп. инфы или меняет вывод инфы на
.Ar уровень.
.It Fl f Ar файл
Использует
.Ar файл
как rc файл.
.It Fl l Ar файл|дир
Использует
.Ar файл
, в который записывает логи, или
.Ar дир
, в которую будут писаться логи.
.It Fl ?, h
Показывает помощь.
.El

.Sh ОСОБЕННОСТИ
.Ic mICQ
очень компактный и запускается на Linux, DOS, OS/2, Win32, BeOS, AmigaOS, GNU HURD и других
современных unix'ах.  
.Ic mICQ версии 0.4.8
запускается на Linux, GNU HURD и других никсах. Но на других системах он
может или не может запускаться и если кто-то желает протестить их, мы не против.
.Sh ИСТОРИЯ
.Bl -tag -width Fl
.It 16 Авг 1998
Matthew D. Smith выпускает micq на обозрение всего мира. 
Следуемых 12 релизами до 25 Сен 1998.
.It 05 Янв 2001
Matthew D. Smith умер в автомобильной аварии.
Пользователи подняли micq под BSD лицензией и начали 
разработку 
.Ic mICQ .

.Sh ЛИСТ РАССЫЛКИ
Лист рассылки Micq по этому адресу:
.Pa micq-list@mc.ukeer.de .
Информация о подписках и архивах лежит здесь:
.Pa http://micq.ukeer.de/pipermail/micq-list/ .
.Sh СКАЧАТЬ
По HTTP с
.Pa http://micq.ukeer.de/download.html .
.br
Чтобы достать последнюю версию от CVS, введите
.br
cvs -d:pserver:anonymous@micq.ukeer.de:/usr/local/cvsroot login
.br
без пароля, нажмите Enter
.br
cvs -d:pserver:anonymous@micq.ukeer.de:/usr/local/cvsroot -z3 co micq
.Sh СМОТРИТЕ ТАКЖЕ
.Xr micqrc 5 ,
.Xr micq 7
.Sh ФАЙЛЫ
.Bl -tag -width Fl
.It ~/.micqrc
Старый файл конфигураций для mICQ - устарел.
.It ~/.micq/micqrc
Файл конфигураций для mICQ.
.It PREFIX/share/micq/*.i18n
Файлы интернационализации, содержащие перевод mICQ.
.It ~/.micq/i18n/*.i18n
Или здесь.
.It ~/.micq/history/
Директория по умолчанию, где создаются логи.
.El
.Sh BUGS
Глюки в программе или комментарии пишите Rico GlЖckner <mc@verdinet.de>,
UIN #99798577, или RЭdiger Kuhlmann <micq@ruediger-kuhlmann.de>.
.Sh АВТОР
Это описание было написано James Morrison
.Pa <ja2morrison@student.math.uwaterloo.ca>
.br
с минимального описания от Jordi Mallach
.Pa <jordi@sindominio.net>
.br
для Debian GNU/Linux систем.
