.\" $Id$ -*- nroff -*-
.\"  EN: micq.1,v 1.12 2002/09/30 21:26:12
.TH MICQ 1 mICQ RU
.SH ИМЯ
.B micq
\- маленький ICQ client для работы в текстовом режиме
.SH ЗАПУСК
.B micq
.I [-v[level]]
.I [-f файл]
.SH ОПИСАНИЕ
.B mICQ
ICQ клиент, поддерживающий большинство функций ICQ от Mirabillis. 
mICQ позволяет менять пароль, создавать новые аккаунты, обновлять инфу 
о пользователе, искать других пользователей и т.д.
.SH ОПЦИИ
.TP
.BI -v [уровень]
Включает вывод доп. инфы или меняет вывод инфы на
.IR уровень .
.TP
.BI -f \ файл
Использует
.I файл
как rc файл.
.TP
.BI -l \ файл|дир
Использует
.IR файл ,
в который записывает логи, или
.IR дир ,
в которую будут писаться логи.
.TP
.BI -?,\ -h
Показывает помощь.

.SH ОСОБЕННОСТИ
.B mICQ
очень компактный и запускается на Linux, DOS, OS/2, Win32, BeOS, AmigaOS, GNU HURD и других
современных unix'ах.  
.B mICQ версии 0.4.9.2
запускается на Linux, AIX, HPUX, Tru64, AmigaOS, partially BeOS и других никсах.
Но на других системах он
может или не может запускаться и если кто-то желает протестить их, мы не против.

.SH ИСТОРИЯ
.TP
16 Авг 1998
Matthew D. Smith выпускает mICQ на обозрение всего мира. 
Следуемых 12 релизами до 25 Сен 1998.
.TP
05 Янв 2001
Matthew D. Smith умер в автомобильной аварии.
Пользователи подняли micq под BSD лицензией и начали 
разработку 
.BR mICQ .
.TP
10 June 2002
Версия 0.4.9 выпущена под лицензией GPL, окончательно
включила новую версию 8 ICQ протокола, сделано
RЭdiger Kuhlmann.

.SH ЛИСТ РАССЫЛКИ
Лист рассылки mICQ по этому адресу:
.IR micq-list@micq.org .
Информация о подписках и архивах лежит здесь:
.IR http://micq.org/pipermail/micq-list/ .
.SH СКАЧАТЬ
По HTTP с
.IR http://micq.org/download.html .
.br
Чтобы достать последнюю версию от CVS, введите
.sp
cvs -d:pserver:anonymous@micq.org:/usr/local/cvsroot co micq
.sp
.SH СМОТРИТЕ ТАКЖЕ
.BI micqrc (5),
.BI micq (7)
.SH ФАЙЛЫ

.TP
.I ~/.micqrc
Старый файл конфигураций для mICQ - устарел.
.TP
.I ~/.micq/micqrc
Файл конфигураций для mICQ.
.TP
.I PREFIX/share/micq/*.i18n
Файлы интернационализации, содержащие перевод mICQ.
.TP
.I ~/.micq/i18n/*.i18n
Или здесь.
.TP
.I ~/.micq/history/
Директория по умолчанию, где создаются логи.

.SH BUGS
Если вы нашли глюки в программе или просто хотите что-то сказать,
пишите Rico GlЖckner <mc@verdinet.de>,
UIN #99798577, или RЭdiger Kuhlmann
.IR <micq@ruediger-kuhlmann.de> .
.SH АВТОР
Это описание было написано James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca>
с минимального описания от Jordi Mallach
.IR <jordi@sindominio.net>
для Debian GNU/Linux систем.
Это руководство было переведено "Pest"
.IR <pest@sharm.info> .
