#!/bin/sh -e

aclocal-1.9 -I m4 && \
(autoheader || autoheader-2.50) && \
automake-1.9 -ac && \
(autoconf || autoconf-2.50) && \
echo "Maintainer scripts ran fine." || \
echo "Maintainer scripts failed."

