.\" $Id: climm.7 2072 2005-12-11 20:57:34Z kuhlmann $ -*- nroff -*-
.\"  EN: climm.7,v 1.49
.TH CLIMM 7 climm DE
.SH NAME
.B climm
\- interaktive Befehle
.SH BESCHREIBUNG
Diese Hilfeseite beschreibt die Befehle, die aus climm heraus verwendet
werden k\(:onnen. Diese Seite enth\(:alt prinzipiell dieselben Informationen wie
die Hilfe innerhalb von climm, nur pr\(:aziser und umfangreicher.
Notationen: eckige Klammern
.RB ( [] )
zeigen optionale Argumente an, w\(:ahrend spitze Klammern
.RB ( <> )
Argumente (im Gegensatz zu Schl\(:usselw\(:ortern) anzeigen.
Insbesondere bedeutet
.I <uin>
immer eine beliebige UIN,
w\(:ahrend
.I <Kontakte>
eine Komma-separierte Liste von Kontakten, d.h. UIN und Spitznamen, bedeutet.
Ist dies das letzte Argument, d\(:urfen die Kontakte auch durch
Leerzeichen getrennt sein.
.SH BEFEHLE ZUM SENDEN VON NACHRICHTEN
.TP
.BI msg \ <Kontakte>\ [<Nachricht>]
Schickt eine Nachricht an alle
.IR Kontakte .
Ohne
.I Nachricht
wird der Mehr-Zeilen-Modus aktiviert. Um eine Mehr-Zeilen-Nachricht abzuschicken,
gebe man einen Punkt
.RB ( . )
auf einer Zeile f\(:ur sich ein. Um die Nachricht abzubrechen, gebe man ein Doppelkreuz
.RB ( # )
auf einer Zeile f\(:ur sich ein.
.br
Ausgehende und eingehende Nachrichten werden unterschiedlich je nach Transport markiert.
.B \(Fo\(Fo\(Fo
und
.B \(Fc\(Fc\(Fc
bezeichnet Nachrichten, die \(:uber eine direkte Verbindung versandt wurden.
.B \(Fo%\(Fo
und
.B \(Fc%\(Fc
bezeichnet Nachrichten, die verschl\(:usselt \(:uber eine direkte Verbindung versandt wurden
(ben\(:otigt GnuTLS oder OpenSSL bei der \(:Ubersetzung).
.B \(Fo<<
und
.B >>\(Fc
bezeichnen "icq8"- (genannt auch "type-2"-) Nachrichten.
Zuletzt bezeichnen
.B <<<
und
.B >>>
"icq5"-Nachrichten, welche auch "type-"-, "type-4"- oder "Offline"-Nachrichten
genannt werden. Diese Art von Nachrichten werden nicht best\(:atigt.
.br
Eine Nachricht wird zun\(:achst versucht, \(:uber eine vorher bestehende
direkte Verbindung verschickt zu werden; ist keine vorhanden, wird im
Hintergrund versucht, eine solche f\(:ur sp\(:atere Nachrichten aufzubauen.
In diesem Falle, oder wenn die Nachricht nach einer Weile immer noch nicht
best\(:atigt wurde, wird die Verbindung als fehlgeschlagen abgebaut, und der
n\(:achste Transport probiert: das Verschicken als type-2-Nachricht. Dieser
Schritt wird \(:ubersprungen, wenn das Gegen\(:uber nicht durch geeignete
"capabilities" die F\(:ahigkeit signalisiert hat, solche Nachrichten zu
Empfangen. Wenn dieser Schritt \(:ubersprungen wird, ein Fehler auftaucht
oder die Nachricht ebenfalls nicht best\(:atigt wird, z.B. wenn sich das
Gegen\(:uber in der Zwischenzeit ausgeloggt hat, wird die Nachricht als
normale type-4-Nachricht verschickt.
.br
Wenn das Gegen\(:uber die F\(:ahigkeit, solche zu empfangen, signalisiert
hat, werden Nachrichten UTF-8-kodiert \(:ubertragen
und entsprechend markiert. Andernfalls wird die Nachricht mit der f\(:ur
das Gegen\(:uber eingestellten Kodierung, oder, falls keine eingestellt ist,
mit der als Standard f\(:ur andere eingestellten Kodierung verschickt.
type-1, type-4 und Offline-Nachrichten k\(:onnen nicht mit ihrer
Kodierung markiert werden, deshalb h\(:angt die korrekte \(:Ubertragung
von 8bit-Zeichen (also insbesondere Umlauten) von der korrekten
Einstellung ab.
.TP
.BI a \ [<Nachricht>]
Schickt eine Nachricht zur gleichen Person wie die letzte Nachricht.
Auto-expandierendes Alias f\(:ur
.BR msg\ %a .
.TP
.BI r \ [<Nachricht>]
Antwortet auf die zuletzt empfangene Nachricht.
Auto-expandierendes Alias f\(:ur
.BR msg\ %r .
.TP
.BI url \ <Kontakte>\ <URL>\ <Nachricht>
Schickt eine
.I Nachricht
\(:uber die Seite
.I URL
an alle
.IR Kontakte .
.TP
.BI sms \ [<Kontakt>]\ [<HandyNr>]\ <Nachricht>
Verschickt eine SMS-Nachricht
.I Nachricht
an die Handy-Nummer
.IR HandyNr ,
die in der Form +<Landeskode><Nummer> sein mu\(ss,
oder an die Handy-Nummer von
.IR Kontakt ,
die auf
.IR HandyNR
gesetzt wird, falls diese noch nicht gesetzt ist.
Es ist nicht zul\(:asslig,
.IR HandyNr
anzugeben, wenn
.IR Kontakt
bereits eine Handy-Nummer zugeordnet bekommen hat.
Ung\(:ultige Handy-Nummern werden von den Meta-Daten eines
Kontaktes entfernt.
.TP
.BI chat \ <Kontakte>\ [<Nachricht>]
Sendet eine Nachricht
.I Nachricht
an Kontakte
.I Kontakte
genau wie bei dem
.BR msg -
Kommando. Nachdem die Nachricht gesendet (oder abgebrochen) wurde,
wird der Mehr-Zeilen-Modus aktiviert und Nachrichten gesendet, bis
eine leere Nachricht abgebrochen wurde. Wird eine nicht-leere
Nachricht abgebrochen, dann wird nur diese Nachricht selber nicht
gesendet, aber der Mehr-Zeilen-Modus bleibt aktiviert und weitere
Nachrichten k\(:onnen gesendet werden.
.TP
.BI getauto \ [auto|away|na|dnd|occ|ffc]\ [<Kontakte>]
Holt automatische Antworten aller
.IR Kontakte
f\(:ur den angegebenen Status, der
.B away
f\(:ur abwesend,
.B na
f\(:ur nicht verf\(:ugbar,
.B dnd
f\(:ur nicht st\(:oren,
.B occ
f\(:ur besch\(:aftigt und
.B ffc
f\(:ur f\(:ur Plaudereien frei sein kann. Wenn
.B auto
oder gar nichts angegeben ist, wird die automatische Antwort f\(:ur
den Kontakt f\(:ur dessen jeweiligen Status geholt.
Kontakte, die dabei nicht einen der genannten Stati haben, werden
\(:ubersprungen.
Neu seit 0.4.10.
.TP
.BI auth \ [req|grant|deny|add]\ <Kontakte>
Erlaubt es allen
.IR <Kontakten> ,
Sie zu ihrer Kontaktliste hinzuzuf\(:ugen
.RB ( grant ),
verbietet dies
.RB ( deny ),
beantragt dies
.RB ( req )
oder teilt das Hinzuf\(:ugen nach Autorisierung mit
.RB ( add ).
.TP
.BI resend \ <Kontakte>
Schickt die letzte Nachricht erneut an weitere
.IR Kontakte .
.TP
.BI last \ [<Kontakte>]
Zeigt die zuletzt empfangene Nachricht aller
.IR Kontakte 
oder von allen, die bisher eine Nachricht geschickt haben.
.TP
.BI h \ <Kontakt>\ [<Start>\ [<Anzahl>]]
.TP
.BI history \ <Kontakt>\ [<Start>\ [<Anzahl>]]
Zeigt Nachrichten von und an
.I <Kontakt>
aus den Logdateien. Starte mit der
.IR Start -letzten
Nachricht, oder der
.IR \-Start -ten
Nachricht wenn
.I Start
negativ ist, oder, wenn nicht angegeben, bei der 20. Nachricht von hinten,
und zeige
.I Anzahl
Nachrichten, oder 20, wenn nicht angegeben.
.TP
.BI historyd \ <Kontakt>\ <Datum>\ [<Anzahl>]
Zeige Nachrichten von
.I <Kontakt>
aus den Logdateien. Starte beim Datum
.IR Datum ,
welches im ISO-8601-Format angegeben sein mu\(ss, entweder
.RB JJJJ \- MM \- TT\ oder\ JJJJ \- MM \- TT T HH : MM : SS,
und zeige
.I Anzahl
Nachrichten, oder 20, wenn nicht angegeben.
.TP
.BI find \ <Kontakt>\ <Muster>
Suche nach dem Suchmuster
.I Muster
ohne Beachtung der Gro\(ss-/Kleinschreibung in der
Logdatei von
.IR Kontakt .
.TP
.BI finds \ <Kontakt>\ <Muster>
Suche nach dem Suchmuster
.I Muster
mit Beachtung der Gro\(ss-/Kleinschreibung in der
Logdatei von
.IR Kontakt .
.TP
.B tabs 
Zeigt eine Liste von Benutzern, zu denen man bereits Nachrichten
geschickt hat bzw. von denen man bereits welche Empfangen hat, und
die man mittels das <tab>-Taste durchgehen kann.
.SH BEFEHLE BEZ\(:UGLICH DES STATUS
.TP
.B login
Eingebaute Abk\(:urzung f\(:ur
.IR conn\ login .
\(:Offnet die erste Server-Verbindung.
.TP
.B online
Wechsel in den Status "verbunden".
.TP
.BI away \ [<Nachricht>]
Wechselt in den Status "abwesend". Setzt optional die automatische Antwort tempor\(:ar auf
.IR Nachricht .
.TP
.BI na \ [<Nachricht>]
Wechselt in den Status "nicht verf\(:ugbar". Setzt optional die automatische Antwort tempor\(:ar auf
.IR Nachricht .
.TP
.BI occ \ [<Nachricht>]
Wechselt in den Status "besch\(:aftigt". Setzt optional die automatische Antwort tempor\(:ar auf
.IR Nachricht .
.TP
.BI dnd \ [<Nachricht>]
Wechselt in den Status "nicht st\(:oren". Setzt optional die automatische Antwort tempor\(:ar auf
.IR Nachricht .
.TP
.BI ffc \ [<Nachricht>]
Wechselt in den Status "frei f\(:ur Plaudereien". Setzt optional die automatische Antwort tempor\(:ar auf
.IR Nachricht .
.TP
.B inv
Wechselt in den Status "unsichtbar".
.TP
.BI change \ [<Nummer>\ [<Nachricht>]]
Wechselt in den Status
.IR Nummer ,
und setze optional die automatische Antwort f\(:ur diesen Status auf
.IR Nachricht .
Ohne eine Nummer: liste die verf\(:ugbaren Nummern auf.
.SH BEFEHLE ZUM SUCHEN UND ANZEIGEN ANDERER BENUTZER
.TP
.BI f \ <Kontakte>
.TP
.BI finger \ <Kontakte>
Zeigt alle Meta-Daten \(:uber alle
.IR Kontakte .
.TP
.TP
.BI ss \ <Kontakte>
Zeigt alle lokal gespeicherten Meta-Daten \(:uber alle
.IR Kontakte .
.TP
.B i
Zeigt alle Kontakte auf der Ignorieren-Liste.
.TP
.BI s \ [<Kontakte>]
Zeigt den aktuellen Status, oder die Details zu den angegebenen Kontakten an,
inklusive dessen Zweit-Namen.
.TP
.BR e ,\  ee ,\  eg ,\  eeg ,\  ev ,\  eev ,\  egv ,\  eegv ,\  w ,\  ww ,\  wg ,\  wwg ,\  wv ,\  wwv ,\  wgv ,\  wwgv
Liste Teile der Kontaktliste auf. Die folgenden Zeichen werden
dabei in der ersten Spalte angezeigt:
.RS
.TP
.B +
Dieser Eintrag ist kein Kontakt, sondern lediglich ein Zweit-Name f\(:ur den
vorhergehenden. Nur mit
.BR ww .
.TP
.B #
Dieser Eintrag ist nicht auf der Kontaktliste, aber die Benutzernummer wurde
schonmal verwendet. Nur mit
.B w
und
.BR ww .
.TP
.B *
Dieser Kontakt ist auf der Sichtbarkeitsliste, d.h. kann den Status auch
im Falle von unsichtbar sehen.
.TP
.B \-
Dieser Kontakt ist auf der Unsichtbarkeitsliste, d.h. kann als Status
nur als ausgeloggt sehen.
.TP
.B ^
Dieser Kontakt wird ignoriert: keine Nachrichten und keine
Statuswechsel werden angezeigt.
.PP
Die Befehle, die mit
.B ww
und
.B ee
beginnen, geben eine weitere Spalte mit Zeichen aus. Wenn die erste Spalte sonst leer w\(:are,
wird das entsprechende Zeichen aus dieser Spalte auch dort ausgegeben,
solange es kein
.BR ^ 
ist.
.TP
.B &
Eine direkte Verbindung wurde aufgebaut.
.TP
.B \(ba
Eine direkte Verbindung wurde versucht, aufzubauen, dies schlug jedoch fehl.
.TP
.B :
Eine direkte Verbindung wird gerade aufgebaut.
.TP
.B ^
Keine direkte Verbindung aufgebaut, aber die IP-Adresse und der Port sind bekannt.
.PP
Eine weitere Spalte wird von den Befehlen, die mit
.B ww
und
.B ee
beginnen, ausgegeben, die Informationen \(:uber die serverseitige Kontaktliste ausgeben,
soweit dies bekannt ist:
.TP
.B S
Der Kontakt ist auf der serverseitigen Kontaktliste, und soll da auch sein.
.TP
.B s
Der Kontakt ist auf der serverseitigen Kontaktliste, soll da aber nicht sein.
.TP
.B .
Der Kontakt ist nicht auf der serverseitigen Kontaktliste, soll da aber sein.
Das bedeutet meistens "Autorisierung erforderlich".
.TP
.B \'\ \'
Der Kontakt ist nicht auf der serverseitigen Kontaktliste, und soll da auch nicht sein.
.RE
.TP
.BI e \ [<Kontaktgruppe>]
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind. Zeigt auch den eigenen Status an. 
.TP
.BI ee \ [<Kontaktgruppe>]
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind, mit mehr Details.
.TP
.BR eg ,\  eeg
Wie oben, aber sortiere nach Gruppen. Neu seit climm 0.4.10.
.TP
.BR w ,\  ww ,\  wg ,\  wwg
Wie oben, aber zeige auch Kontakte an, die gerade nicht verbunden sind.
.TP
.BR ev ,\  eev ,\  egv ,\  eegv ,\  wv ,\  wwv ,\  wgv ,\  wwgv
Wie oben, aber zeige auch versteckte Kontakte an, also solche, die die
.B shadow
effektiv gesetzt haben. Neu seit climm 0.5.
.TP
.B ewide
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind, in einem breiten Format.
.TP
.B wide
Zeigt alle Kontakte auf der Kontaktliste in einem breiten Format.
.TP
.B search
.TP
.BI search \ <eM@il>
.TP
.BI search \ <Spitzname>
.TP
.BI search \ <Vorname>\ <Nachname>
Sucht nach einem Benutzer mit der eMail-Adresse
.IR eM@il ,
mit dem Spitznamen
.IR Spitzname ,
der kein @ enthalten darf, oder mit
.I Vorname
als Vor- und
.I Nachname
als Nachname. Ist kein Argument gegeben, frage nach
Spitznamen, Vornamen, Nachnamen, eMail-Adresse und einem
Haufen anderer Daten, nach denen man suchen kann.
.TP
.BI rand \ [<Nummer>]
Findet einen zuf\(:alligen Kontakt in der Interessengruppe
.IR Nummer ,
oder zeigt alle Interessengruppen an.
.SH BEFEHLE ZUM VERWALTEN DER KONTAKTLISTE
.TP
.BI add \ <Benutzernummer>\ <Spitzname>
F\(:ugt den Benutzer mit Benutzernummer
.I Benutzernummer
zur Kontaktliste unter dem Namen
.IR Spitzname
hinzu.
.br
Hinweis: Sie m\(:ussen mit
.B save
abspeichern, um diese \(:Anderungen dauerhaft zu machen.
.TP
.BI add \ <Spitzname>\ <Zweit-Name>
.TP
.BI addalias \ <Spitzname>\ <Zweit-Name>
Vergibt einen Zweit-Namen
.I Zweit-Name
f\(:ur
.IR Spitzname .
Neu (addalias) seit 0.4.10.
.br
Hinweis: Sie m\(:ussen mit
.B save
abspeichern, um diese \(:Anderungen dauerhaft zu machen.
.TP
.BI add \ <Gruppe>\ [<Kontakte>]
.TP
.BI addgroup \ <Gruppe>\ [<Kontakte>]
F\(:uge alle Kontakte in
.IR Kontakte
zur Kontaktgruppe
.IR Gruppe
hinzu, welche erforderlichenfalls neu angelegt wird,
falls man den Befehl als
.B addgroup
aufruft.
Neu seit 0.4.10.
.br
Hinweis: Sie m\(:ussen mit
.B save
abspeichern, um diese \(:Anderungen dauerhaft zu machen.
.TP
.BI rem \ [all]\ <Kontakte>
.TP
.BI remalias \ [all]\ <Kontakte>
Entfernt alle in
.IR Kontakte
angegebenen Zweit-Namen.
Wenn dies der einzige Name ist, oder wenn
.B all
angegeben wurde, entferne den jeweiligen Kontakt
von der Kontaktliste.
Neu seit 0.4.10.
.br
Hinweis: Sie m\(:ussen mit
.B save
abspeichern, um diese \(:Anderungen dauerhaft zu machen.
.TP
.BI rem \ [all]\ <Gruppe>
.TP
.BI rem \ <Gruppe>\ <Kontakte>
.TP
.BI remgroup \ [all]\ <Gruppe>
.TP
.BI remgroup \ <Gruppe>\ <Kontakte>
Entferne alle Kontakte in
.IR Kontakte
aus der Kontaktgruppe
.IR Gruppe ,
oder entferne diese Gruppe vollst\(:andig, falls
.B all
angegeben ist.
Neu seit 0.4.10.
.br
Hinweis: Sie m\(:ussen mit
.B save
abspeichern, um diese \(:Anderungen dauerhaft zu machen.
.TP
.BI togig \ <Kontakte>
\(:Andert, ob Nachrichten und Status\(:anderungen der Kontakte
.I Kontakte
ignoriert werden sollen.
.TP
.BI toginvis \ <Kontakte>
\(:Andert f\(:ur jeden Kontakt aus
.IR Kontakte ,
ob er Sie niemals sehen kann.
.TP
.BI togvis \ <Kontakte>
\(:Andert f\(:ur jeden Kontakt aus
.IR Kontakte ,
ob er Sie sehen kann, wenn Sie unsichtbar sind.
.SH BEFEHLE BEZ\(:UGLICH IHRES ICQ-KONTOS
.TP
.BI pass \ <Pa\(sswort>
Setzt das Pa\(sswort auf
.IR Pa\(sswort .
.br
Hinweis: das Pa\(sswort darf nicht mit einem \('o (Byte 0xf3) beginnen.
.br
Hinweis: Sie m\(:ussen danach mit
.B save
abspeichern, um diese \(:Anderung dauerhaft zu machen, falls Sie Ihr Pa\(sswort
in Ihrem
.I ~/.climm/climmrc
abspeichern (siehe
.BR climmrc (7),
oder Ihr Pa\(sswort wird beim n\(:achsten Login fehlerhaft sein.
.TP
.B update
Aktualisiert die auf dem Server gespeicherten Benutzerinformationen (eMail-Adresse, Spitzname, und so weiter).
.TP
.B other
Aktualisiert weitergehende Benutzerinformationen wie Alter und Geschlecht.
.TP
.B about
Aktualisiert den Punkt "\(:Uber" der Benutzerinformationen.
.TP
.BI setr \ [<Nummer>]
Setzt die Interessengruppe f\(:ur zuf\(:allige Kontakte auf
.IR Nummer .
Ohne Argumente: listet m\(:ogliche Interessengruppen auf.
.TP
.BI reg \ <Pa\(sswort>
Erzeugt eine neue Benutzernummer mit dem Pa\(sswort
.IR Pa\(sswort . 
.SH BEFEHLE ZUM KONFIGURIEREN DES CLIMM ICQ-PROGRAMMS
.TP
.BI verbose \ [<verb>]
Setzt die Ausf\(:uhrlichkeit der Ausgaben von climm auf
.IR verb ,
oder zeigt die aktuelle Ausf\(:uhrlichkeit an. Die Ausf\(:uhrlichkeit ist eine Menge von
Werten, die aufaddiert werden:
.RS
.TP
.B 8
Zeige Protokoll-Fehler.
.TP
.B 16
Zeige Erzeugung und Entfernung von Paketen.
.TP
.B 32
Zeige hinzugef\(:ugte und entfernte Warteschlangen-Ereignisse.
.TP
.B 64
Zeige Erzeugung und Entfernung von Verbindungen.
.TP
.B 256
Zeige Version-6-Pakete mit hexadezimalem Abbild.
.TP
.B 4096
Zeige Version-7/8-Pakete.
.TP
.B 8192
Zeige zus\(:atzlich das hexadezimale Abbild.
.TP
.B 16284
Speichere diese Pakete in eine Datei.
.TP
.B 65536
Zeige Direktverbindungs-Pakete.
.TP
.B 131072
Zeige zus\(:atzlich das hexadezimale Abbild.
.TP
.B 262144
Speichere diese Pakete in eine Datei.
.TP
.B 2097152
Zeige den Direktverbindungs-Handschlag.
.TP
.B 4194304
Zeige den Verbindungsaufbau von Verbindungen.
.PP
In jedem Fall bewirkt eine Ausf\(:uhlichkeit gr\(:o\(sser als 0 die Ausgabe von mehr
Informationen, und eine gr\(:o\(sser als 1 von noch mehr.
.RE
.TP
.B clear
L\(:oscht den Bildschirm.
.TP
.BI sound \ [on|off|event]
Schaltet Piepsen ein
.RB ( on )
oder aus
.RB ( off ),
oder verwendet stattdessen das Ereignis-Skript
.RB ( event ).
Neue Syntax seit 0.4.10.
.TP
.BI autoaway \ [<Zeit>|on|off]
Gehe nach
.I Zeit
Sekunden automatisch in den Status "abwesend" bzw. "nicht verf\(:ugbar",
oder schaltet dies an (\fBon\fR) (mit der letzten verwendeten Zeit) oder ab (\fBoff\fR).
Eine Zeit von 0 schaltet dies ebenfalls ab. Ist kein Argument gegeben,
zeigt es die aktuelle Einstellung an.
.TP
.BI alias\ [auto[expand]] \ [<Alias>\ <Erweiterung>]
Erzeuge ein neues Alias mit dem Namen
.IR Alias ,
das durch
.IR Erweiterung
ersetzt wird.
Wird kein
.I Alias
angegeben, dann liste alle Aliase auf.
Wird keine
.I Erweiterung
angegeben, dann liste das bestehende
.I Alias
auf.
Anderfalls erzeuge ein neues
.IR Alias .
Ist das Schl\(:usselwort
.I auto
oder
.I autoexpand
angegeben, dann erzeuge ein auto-expandierendes Alias, d.h. ein
Alias, das sofort expandiert wird, wenn die Leertaste oder die
Eingabetaste direkt nach dem Alias eingegeben wird.
.br
Wenn die Zeichenkette
.B %s
in der
.I Erweiterung
vorhanden ist, wird jedes Auftreten durch die beim Aufruf des Alias angegebenen Argumente ersetzt,
andernfalls werden diese an das Ende angeh\(:angt.
Wenn die Zeichenkette
.B %r
in der
.I Erweiterung
vorhanden ist, wird jedes Auftreten ersetzt durch den Spitznamen, falls vorhanden, oder die UIN des
Kontaktes ersetzt, von dem die letzte Nachricht empfangen wurde, oder durch die leere
Zeichenkette, falls es noch keinen solchen gibt.
Wenn die Zeichenkette
.B %a
in der
.I Erweiterung
vorhanden ist, wird jedes Auftreten ersetzt durch den Spitznamen, falls vorhanden, oder die UIN des
Kontaktes ersetzt, an den die letzte Nachricht gesendet wurde, oder durch die leere
Zeichenkette, falls es noch keinen solchen gibt.
.br
Neu seit 0.4.10. Auto-expandierende Aliase neu seit 0.5.0.4.
.TP
.BI unalias \ <Alias>
L\(:osche den Alias mit dem Namen
.IR Alias .
Neu seit 0.4.10.
.TP
.BI lang \ [<Sprache>|<Nr>]\ ...
Wechsle zur Sprache
.IR Sprache ,
gegeben durch ihren ISO-Sprachcode, oder gibt die \(:Ubersetzung
der Textes mit der Nummer
.I Nr
aus. Um die durch die Umgebungsvariablen
.BR LANG ,
.B LC_ALL
und
.B LC_MESSAGES
bestimmte Sprache auszuw\(:ahlen, kann
.BR ! ,
.B auto
oder
.B default
verwendet werden. Um \(:uberhaupt keine \(:Ubersetzung auszuw\(:ahlen,
kann man
.BR . ,
.B none
oder
.B unload
verwenden. Um zur Fehlersuche die Nummern der
\(:ubersetzten Texte mitauszugeben, kann man
.B debug
voranstellen.
.sp
Die Dateien aus ~/.climm/i18n/*.i18n haben Vorrang  \(:uber die globalen
Dateien, die Dateien aus BASIS/i18n/*.i18n haben Vorrang \(:uber die aus
~/.climm/i18n/*.i18n, w\(:ahrend die "lustigen" Texte \(:uber die normalen
Vorrang haben.
.sp
Tats\(:achlich kann man sogar soviele Argumente angeben, wie man will,
um z.B. den 117. Text in Deutsch auszugeben und dann zur Standardsprache
zur\(:uckzukehren, gebe man "trans de 117 default" ein.
.TP
.B uptime
Zeigt an, wie lange climm bereits l\(:auft, sowie einige Statistiken.
.TP
.BI set \ <Option>\ <Wert>
Schaltet die Option
.I Option
entweder
.I an
.RB ( on ),
.I aus
.RB ( off )
oder auf einen optionsspezifischen
.BR Wert .
.I Option
kann dabei sein:
.RS
.TP
.BR color :
verwende Farben,
.TP
.BR delbs :
interpretiere das L\(:oschzeichen als R\(:uckschritt,
.TP
.BR funny :
lustige Meldungen verwenden,
.TP
.BR auto :
schicke automatische Antworten wenn man z.B. abwesend ist,
.TP
.BR uinprompt :
f\(:ugt den zuletzt verwendeten Spitznamen in den Prompt ein,
.TP
.BR autosave :
speichert das climmrc automatisch beim Beenden,
.TP
.BR autofinger :
fingert automatisch neue Benutzernummern,
.TP
.BR linebreak :
setzt den Stil f\(:ur Zeilenumbr\(:uche bei Nachrichten auf:
.BR simple ,
um die Nachricht nach dem Spitznamen auszugeben und normal umzubrechen,
.BR break ,
um in jedem Fall vor der Nachricht zus\(:atzlich umzubrechen,
.BR indent ,
um alle Zeilen der Nachricht zur selben Stelle wie die erste Zeile einzur\(:ucken, oder
.BR smart ,
um einen Zeilenumbruch nur vor der Nachricht einzuf\(:ugen, wenn diese
sonst nicht in die Zeile passen w\(:urde;
.PP
Neue Optionen seit 0.4.10. Die Optionen hermit, log, logonoff, silent,
tabs wurden f\(:ur climm 0.5 entfernt; benutze das
.BR opt -Kommando
stattdessen.
.RE
.TP
.BI opt \ [<contact>|<contact\ group>|connection|global\ [<option>\ [<value>]]]
Setze die Option
.I option
für Kontakt
.IR contact ,
Kontaktgruppe
.IR contact\ group ,
für die aktuelle Verbindung oder global auf den Wert
.IR value ,
oder zeige den aktuellen Wert, oder zeige alle Optionen und ihren Wert.
.br
Wenn Optionen von Kontakten aufgel\(:ost werden, wird zuerst die Option
vom Kontakt selber benutzt, falls diese gesetzt ist; andernfalls wird,
wenn der Kontakt zu einer Gruppe geh\(:ort, die Option dieser Gruppe
benutzt, falls diese gesetzt ist; andernfalls wird, wenn der Kontakt zu
einer Server-Verbindung geh\(:ort (d.h. wenn er noch nicht entfernt wurde),
die Option von der Server-Verbindung benutzt, falls diese gesetzt ist;
andernfalls wird die globale Option benutzt, falls diese gesetzt ist.
Andernfalls wird 0 angenommen, wenn es eine Ganzzahl-Option ist, falsch
f\(:ur eine An-/Aus-Option, die Farbzeichenkette f\(:ur "keine Farbe",
falls nicht gerade nach selbiger gesucht wurde, oder andernfalls
die leere Zeichenkette f\(:ur Zeichenkettenoptionen.
.br
Wenn Optionen von Kontaktgruppen aufgel\(:ost werden, wird das
gleiche getan, au\(sser dem ersten Schritt; Optionen von
Verbindungen werden zuerst von der Verbindung, andernfalls
global genommen; und globale Optionen nat\(:urlich nur global.
.br
Die folgenden Optionen existieren, angegeben mit Typ und Anwendbarkeit:
.RS
.TP
.BI colorscheme \ Ganzzahl\ global
Die Nummer des Farbschemas, das benutzt werden soll. Ist dies
auf 0 gesetzt, dann (und nur dann) werden die unten definierten
Farben verwendet.
.TP
.BI colornone \ Farbzeichenkette\ global
Die Farbzeichenkette, um normalen Text auszuw\(:ahlen.
Die Schl\(:usselw\(:orter
.BR black (schwarz),
.BR red (rot),
.BR green (gr\(:un),
.BR yellow (gelb),
.BR blue (blau),
.BR magenta (magenta),
.BR cyan (cyan),
.BR white (wei\(ss),
.BR none (keine),
und
.BR bold (fett)
werden jeweils durch die entsprechende ANSI-Kontrollsequenz ersetzt.
Jede Farbe enth\(:alt implizit bereits
.BR none (keine),
deshalb mu\(ss
.BR bold (fett)
immer nach einer Farbe angegeben werden. Jeder andere Text wird als
Kontrollsequenz interpretiert, die unver\(:andert auszugeben ist.
.TP
.BI colorserver \ Farbzeichenkette\ global
Die Farbzeichenkette f\(:ur Dinge, die den Server betreffen.
.TP
.BI colorclient \ Farbzeichenkette\ global
Die Farbzeichenkette f\(:ur Dinge, die climm selber betreffen.
.TP
.BI colorinvchar \ Farbzeichenkette\ global
Die Farbzeichenkette f\(:ur die Anzeige von Bytesequenzen, die
in der aktuellen Zeichenkodierung keinen Sinn haben.
.TP
.BI colorerror \ Farbzeichenkette\ global
Die Farbzeichenkette f\(:ur die Anzeige von Fehlern.
.TP
.BI colordebug \ Farbzeichenkette\ global
Die Farbzeichenkette f\(:ur die Ausgabe von Debug-Meldungen.
.TP
.BI colorquote \ Farbzeichenkette\ global
Die Farbzeichenkette f\(:ur die Ausgabe von zitiertem Text.
.TP
.BI webaware \ An/Aus\ Verbindung
Gibt an, ob der aktuelle Status \(:uber das Web einsehbar sein soll.
.TP
.BI hideip \ An/Aus\ Verbindung
Gibt an, ob die (lokale) IP-Adresse versteckt werden soll.
.TP
.BI dcauth \ An/Aus\ Verbindung
Gibt an, ob nur autorisierte Kontakte die (entfernte)
IP-Adresse sehen d\(:urfen.
.TP
.BI dccont \ An/Aus\ Verbindung
Gibt an, ob Kontakte die (entferne)
IP-Adresse sehen d\(:urfen.
.TP
.BI obeysbl \ An/Aus\ Verbindung
Gibt an, ob die Server-basierte Kontaktliste beim Einloggen
geladen werden soll. Die f\(:uhrt dazu, da\(ss Autorisierungen
durchgesetzt werden, welche bei der lokalen Kontaktliste
noch ignoriert werden.
.TP
.BI ignore \ An/Aus\ Kontakt
Gibt an, ob alle Nachrichten von diesem Kontakt ignoriert
werden sollen.
.TP
.BI hidefrom \ An/Aus\ Kontakt
Gibt an, ob man gegen\(:uber diesem Kontakt immer unsichtbar ist.
.TP
.BI intimate \ An/Aus\ Kontakt
Gibt an, ob man gegen\(:uber diesem Kontakt immer sichtbar ist.
.TP
.BI logonoff \ An/Aus\ Kontakt
Gibt an, ob mitgeloggt werden soll, wenn sich dieser Kontakt
einloggt oder wieder verschwindet.
.TP
.BI logchange \ An/Aus\ Kontakt
Gibt an, ob Statuswechsel dieses Kontaktes mitgeloggt werden sollen.
.TP
.BI logmess \ An/Aus\ Kontakt
Gibt an, ob Nachrichten dieses Kontaktes mitgeloggt werden sollen.
.TP
.BI showonoff \ An/Aus\ Kontakt
Gibt an, ob angezeigt werden soll, wenn sich dieser Kontakt
einloggt oder wieder verschwindet.
.TP
.BI showchange \ An/Aus\ Kontakt
Gibt an, ob Statuswechsel dieses Kontaktes angezeigt werden sollen.
.TP
.BI autoauto \ An/Aus\ Kontakt
Gibt an, ob bei Statuswechsel dieses Kontakts automatisch dessen
automatische Nachricht erfragt werden soll, ausser bei einem Wechsel
des Status zu "online" oder "invisible".
.TP
.BI hideack \ An/Aus\ Kontakt
Gibt an, ob Best\(:atigungen zu Nachrichten dieses Kontaktes
versteckt werden sollen.
.br
Hinweis: dies zu benutzen ist eine wirklich schlechte Idee,
da dadurch nicht angezeigt wird, wenn Nachrichten als
unbest\(:atigte Nachrichten erneut versendet werden.
.TP
.BI wantsbl \ An/Aus\ Kontakt
Gibt an, ob dieser Kontakt auf die Server-seitige Kontaktliste soll.
.TP
.BI peekme \ boolean\ contact
Gibt an, ob dieser Kontakt \(:uberpr\(:uft werden soll, wenn der Befehl
.BR peek\ all \ bzw. \ peekall
verwendet wird.
.TP
.BI shadow \ An/Aus\ Kontakt
Gibt an, ob dieser Kontakt in der kontaktliste nicht angezeigt werden
soll, wenn nicht eines der auf v endenden Kommandos verwendet wird.
.TP
.BI local \ An/Aus\ Kontakt
Gibt an, ob dieser Kontakt kein richtiger Kontakt ist, sondern
nur ein Spitzname f\(:ur die betreffende Nummer.
.TP
.BI encoding \ Zeichenkette\ Kontakt
Die Zeichenkodierung, in der zu sein eine Nachricht angenommen wird,
wenn die Zeichenkodierung nicht definiert ist. Das betrifft insbesondere
die Metadaten auf dem Server.
.TP
.BI tabspool \ Ganzzahl\ Kontakt
Gibt an, ob dieser Kontakt beim Starten in die Liste der mittels
der Tabulator-Taste aufrufbaren Kontakte aufgenommen werden soll.
.TP
.BI autoaway \ Zeichenkette\ Kontakt
Die Abwesenheitsmeldung f\(:ur den Status "abwesend", die an
diesen Kontakt zur\(:uckgegeben werden soll.
.TP
.BI autona \ Zeichenkette\ Kontakt
Die Abwesenheitsmeldung f\(:ur den Status "nicht verf\(:ugbar", die an
diesen Kontakt zur\(:uckgegeben werden soll.
.TP
.BI autoocc \ Zeichenkette\ Kontakt
Die Abwesenheitsmeldung f\(:ur den Status "besch\(:aftigt", die an
diesen Kontakt zur\(:uckgegeben werden soll.
.TP
.BI autodnd \ Zeichenkette\ Kontakt
Die Abwesenheitsmeldung f\(:ur den Status "nicht st\(:oren", die an
diesen Kontakt zur\(:uckgegeben werden soll.
.TP
.BI autoffc \ Zeichenkette\ Kontakt
Die Abwesenheitsmeldung f\(:ur den Status "frei f\(:ur Plaudereien", die an
diesen Kontakt zur\(:uckgegeben werden soll.
.TP
.BI colormessage \ Farbzeichenkette\ Kontakt
Die Farbzeichenkette, die f\(:ur Nachrichten dieses Kontakts verwendet werden soll.
.TP
.BI colorsent \ Farbzeichenkette\ Kontakt
Die Farbzeichenkette, die f\(:ur den Spitznamen dieses Kontakts verwendet werden soll,
wenn Nachrichten verschickt werden.
.TP
.BI colorack \ Farbzeichenkette\ Kontakt
Die Farbzeichenkette, die f\(:ur den Spitznamen dieses Kontakts verwendet werden soll,
wenn Nachrichten best\(:atigt werden.
.TP
.BI colorincoming \ Farbzeichenkette\ Kontakt
Die Farbzeichenkette, die f\(:ur den Spitznamen dieses Kontakts verwendet werden soll,
wenn Nachrichten empfangen werden.
.TP
.BI colorcontact \ Farbzeichenkette\ Kontakt
Die Farbzeichenkette, die ansonsten f\(:ur den Spitznamen dieses Kontakts verwendet werden soll.
.PP
Neu seit 0.5.
.RE
.TP
.BI optcontact \ <contact>\ [<option>\ [<value>]]
Setze oder zeige die Option
.I option
oder alle Optionen des Kontaktes
.IR contact
an.
Neu seit 0.5.
.TP
.BI optgroup \ <group>\ [<option>\ [<value>]]
Setze oder zeige die Option
.I option
oder alle Optionen der Kontaktgruppe
.IR group 
an.
Neu seit 0.5.
.TP
.BI optconnection \ [<option>\ [<value>]]
Setze oder zeige die Option
.IR option 
der aktuellen Verbindung an.
Neu seit 0.5.
.TP
.BI optglobal \ [<option>\ [<value>]]
Setze oder zeige die globale Option
.IR option
an.
Neu seit 0.5.
.TP
.B save
Speichert die aktuellen Einstellungen in der Kon\(figurationsdatei ab,
welches
.I ~/.climm/climmrc
ist, wenn nicht anders angegeben. Vorsicht, dies wird alle hinzugef\(:ugten
Kommentare in dieser Datei \(:uberschreiben.
.TP
.BI q \ [<msg>]
.TP
.BI quit \ [<msg>]
.TP
.BI exit \ [<msg>]
Beendet climm. Falls angegeben, sende die Nachricht
.I msg
an alle, die schon Nachrichten bekommen haben, noch
verbunden sind und noch auf der Kontaktliste sind.
.br
Hinweis: climm wartet nicht auf Best\(:atigungen der Nachrichten,
d.h. falls diese Nachricht aus irgendeinem Grunde nicht beim
anderen Kontakt ankommt, wird sie nicht erneut gesendet.
.br
quit und exit sind neu seit 0.4.10.
.TP
.BI x \ [<msg>]
Beendet climm, ohne zu speichern. Falls angegeben, sende die Nachricht
.I msg
an alle, die schon Nachrichten bekommen haben, noch
verbunden sind und noch auf der Kontaktliste sind.
.br
Hinweis: climm wartet nicht auf Best\(:atigungen der Nachrichten,
d.h. falls diese Nachricht aus irgendeinem Grunde nicht beim
anderen Kontakt ankommt, wird sie nicht erneut gesendet.
.br
Neu seit climm 0.5.
.SH BEFEHLE F\(:UR WEITERGEHENDE F\(:AHIGKEITEN
.TP
.BI meta \ [show|load|save|set|get|rget]\ <Kontakte>
Bearbeite Benutzerinformationen aller Kontakte. Es gibt folgende Unterbefehle:
.RS
.TP
.B show
Zeigt die Benutzerinformationen aller
.I Kontakte
an.
.TP
.B load
L\(:ad die gespeicherten Benutzerinformationen aller
.IR Kontakte
und zeigt diese an.
.TP
.B save
Speichert die Benutzerinformationen aller
.IR Kontakte .
.TP
.B set
Setzt die eigenen Benutzerinformationen auf dem Server.
.TP
.B get
Fragt die Benutzerinformationen f\(:ur alle
.I Kontakte
ab und zeigt diese an.
.TP
.B getr
Fragt die Benutzerinformationen f\(:ur den kontakt, von dem
die letzte Nachricht empfangen wurde, ab und zeigt diese an.
.PP
Neu seit 0.4.10.
.RE
.TP
.BI file \ [...]
K\(:urzel f\(:ur
.BR peer\ file .
Neu seit 0.4.10.
.TP
.BI peer \ <Befehl>\ <Benutzernummer>|<Spitzname>
wendet den Befehl
.I Befehl
auf den durch Benutzernummer
.I Benutzernummer
oder Spitzname
.I Spitzname
angegebenen Benutzer an.
.RS
.TP
.B open
\(:O\(ffnet eine Direktverbindung \(:uber TCP zu diesem Benutzer.
.TP
.B close
Schlie\(sst eine Direktverbindung zu diesem Benutzer bzw. setzt sie zur\(:uck.
.TP
.B off
Deaktiviert Direktverbindungen f\(:ur diesen Benutzer.
.TP
.BI file \ Datei\ Beschreibung
Sendet eine einzelne Datei
.I Datei
mit der Beschreibung
.IR Beschreibung .
.TP
.BI files \ [Datei\ als]...\ Beschreibung
Sende Dateien zum Benutzer. Es darf beliebig viele Paare von tats\(:achlichen Dateinamen
.I Datei
und dem gegen\(:uber pr\(:asentierten Dateinamen
.I als
geben. Wenn
.IR als
.RB ' / '
is, dann gebe den Dateinamen ohne den Pfad an, wenn
.IR als
.RB ' . '
ist, dann gebe den richtigen Dateinamen an.
.TP
.BR accept \ [<contact>]\ [<id>]
Akzeptiert eine eingehende Datei\(:ubertragung von Kontakt
.IR contact
mit der Kennung
.IR id .
Wenn es nur eine ausstehende eingehende Datei\(:ubertragung gibt,
dann k\(:onnen die
.IR contact -\ und\  id -
Argumente weggelassen werden, andernfalls ist es undefiniert, welche
Datei\(:ubertragung gemeint ist, falls mehrere passen.
.TP
.BR deny \ [<contact>]\ [<id>]\ [<reason>]
Lehnt eine einkommende Datei\(:ubertragung von Kontakt
.IR contact
mit der Kennung
.IR id
mit dem Grund
.IR reason
ab.
.RE
.TP
.BI login \ [...]
K\(:urzel f\(:ur
.BR conn\ login .
Neu seit climm 0.4.10.4.
.TP
.BI conn \ [<Befehl>\ <Nr>]
Zeigt alle o\(ffenen Verbindungen, oder wendet den Befehl
.I Befehl
auf die Verbindung
.I Nr 
an.
.RS
.TP
.B open
\(:O\(ffne die angegebene, oder die erster Server-Verbindung.
.TP
.B login
dito
.TP
.B close
Schlie\(sst die angegebene Verbindung. Tempor\(:are Verbindungen werden entfernt.
.TP
.B remove
Schlie\(sse und entferne die angegebene (tempor\(:are) Verbindung.
.TP
.B select
W\(:ahlt die angegebene Server-Verbindung als die aktuelle aus.
.I Nr
kann dabei die sowohl die Verbindungsnummer als auch die in der
Server-Verbindung verwendete Benutzernummer sein.
.RE
.TP
.BI contact \ [<Befehl>]
Bearbeitet die Server-seitige Kontaktliste:
.RS
.TP
.B show
L\(:ad die Server-seitige Kontaktliste herunter und zeigt sie an.
.TP
.B diff
L\(:ad die Server-seitige Kontaktliste herunter und zeigt alle Kontakte
(also Benutzernummer/Spitzname-Paare) an, die nicht in der lokalen
Kontaktliste sind.
.TP
.B add
L\(:ad die Server-seitige Kontaktliste herunter und f\(:ugt alle Kontakte
der lokalen Kontaktliste hinzu.
.B upload
Versucht, lokale Kontakte auf die Server-seitige Kontaktliste hochzuladen.
.br
.B Hinweis:
L\(:ad nur die Kontakte hoch, die die Kontaktoption
.I wantsbl
gesetzt haben. Um alle Kontakte hochzuladen, kann man die global mit
.I optglobal wantsbl on
setzen.
.TP
.B download
Lade Kontakte von der server-seitigen Kontaktliste herunter,
aber vermeide es, bestehende lokale Kontakte zu ver\(:andern.
.TP
.B import
Lade Kontakte von der server-seitigen Kontaktliste herunter,
wobei bestehende lokale Kontakte ver\(:andert werden.
.RE
.TP
.BI peek \ [<Kontakte>]\ [all]\ [<Kontakte>]
\(:Uberpr\(:uft, ob die
.I Kontakte
tats\(:achlich verbunden sind oder nicht.
Wird das Schl\(:usselwort
.B all
mit angegeben, werden auch alle Kontakte \(:uberpr\(:uft,
die die Option
.B peekme
effektiv gesetzt haben.
.br
.B Hinweis:
Dies mi\(ssbraucht einen Fehler im ICQ-Protokoll, um dies herauszu\(finden,
und kann deshalb jederzeit aufh\(:oren, zu funktionieren.
Es kann nur herausgefunden werden, ob verbunden oder nicht.
.TP
.BI peek2 \ <Kontakte>
Eingebaute Abk\(:urzung f\(:ur
.B getauto\ away
.IR contacts .
Kann dazu benutzt werden, die Anwesenheit der Benutzer
mancher ICQ-Programme zu erkennen, aber dieser Versuch
kann vom ICQ-Programm des anderen Benutzers erkannt werden.
climm ab Version 0.5 kann hiermit nicht entdeckt werden,
und wird auch derlei Versuche anderer ICQ-Programme erkennen.
.TP
.BI peekall \ [<Kontakte>]
Eingebaute Abk\(:urzung f\(:ur
.BR peek\ <Kontakte>\ all .
.TP
.BI as \ <nr|uin>\ <cmd>
F\(:uhre den climm-Befehl
.I cmd
aus als ob die Verbindung mit der Nummer
.I nr
oder f\(:ur die UIN
.I uin
die aktuelle w\(:are.
.SH KOMMANDOS F\(:UR SKRIPTE
.TP
.BI tclscript \ <file>
F\(:uhre das tcl-Skript
.IR file 
aus, wobei der Pfad relativ zum climm-Basis-Verzeichnis
angegeben werden kann.
.TP
.BI tcl \ <string>
F\(:uhre den tcl-Befehl
.IR string
aus. Mit
.I tcl climm help
wird eine Liste der climm\-spezifischen tcl-Befehle ausgegeben.
.SH SIEHE AUCH
.BR climm (1),
.BR climmrc (5)
.SH AUTOR
Diese Hilfeseite wurde von James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
erscha\(ffen, um eine Referenz f\(:ur alle interaktiven Befehle in
.B climm
zu erscha\(ffen. Sie wurde aktualisiert und ins
Deutsche \(:ubersetzt von R\(:udiger Kuhlmann.
