.\" $Id$
.\"  EN: micqrc.5,v 1.9 2002/08/09 01:22:20
.TH MICQRC 5 mICQ
.SH NAME
.B ~/.micq/micqrc
\- die Konfigurationsdatei für mICQ
.SH BESCHREIBUNG
Diese Hilfeseite beschreibt die konfigurationsdatei für mICQ. Dieses besteht
aus mehreren Abschnitten, die jeweils durch
.I [section]
eingeleitet werden, wobei
.I section
der Name des Abschnittes ist.
.SH VERBINDUNGEN - connection
Ein Abschnitt
.B Connection
beschreibt eine Verbindung innerhalb ICQ. Typischerweise gibt es genau zwei davon,
die voneinander abhängen: eine Verbindung zum ICQ-Server, und eine Verbindung,
auf der auf eingehende Direktverbindungen gewartet wird.
.TP
.BI type \ type\ [auto]
Wählt 
.I type
als Typ der Verbindung:
.B server
für eine Verbindung zum ICQ-Server oder
.B peer
für eine Verbindung für eingehende Direktverbindungen. Wenn
.B auto
gegeben ist, öffne diese Verbindung beim Programmstart.
Dies möchte man normalerweise, es sei denn, man hat mehrere Benutzernummern,
dann verwendet man es nur für diejenige, die man gerade verwenden will.
.TP
.BI version \ nr
Setzt die Version, die für diese Verbindung zu verwenden ist, auf
.IR nr .
Man beachte, daß für Server-Verbindungen nur die Versionen
.IR 5 ,
.I 7
und
.IR 8 ,
und für Direktverbindungen
.IR 6 ,
.I 7
und
.I 8
unterstützt werden. Empfehlenswerterweise verwende man stets
Version 8.
.TP
.BI server \ server
Setzt den Rechnername, zu dem verbunden werden soll, auf
.IR server .
Dies ist standardmäßig
.IR login.icq.com .
Unbenutzt für Direktverbindungen.
.TP
.BI port \ port
Setzt den Port, zu dem verbunden werden soll, bzw. auf dem
auf eingehende Verbindungen gewartet werden soll, auf
.IR port .
.TP
.BI uin \ UIN
Setzt die Benutzernummer, mit der einzuloggen ist, auf
.IR UIN .
Unbenutzt für Direktverbindungen.
.TP
.BI password \ password
Setzt das Login-Paßwort auf
.IR password .
Unbenutzt für Direktverbindungen. Wenn dies weggelassen wird, fragt mICQ
beim Programmstart nach dem Paßwort. Benutzer von BeOS müssen diese
Option verwenden.
.TP
.BI status \ nr
Setzt den Status beim Login auf
.IR nr .
Status kann dabei sein:
.RS
.TP
0
verbunden
.TP
1
abwesend
.TP
5
nicht verfügbar
.TP
17
beschäftigt
.TP
19
nicht stören
.TP
32
frei für Plaudereien
.TP
256
unsichtbar
.RE

.SH ALLGEMEINES - general
Dieser Abschnitt enthält Optionen für SOCKS 5, die möglicherweise später
in einen eigenen Abschnitt wandern, allgemeine Optionen, und ein paar
Texte, die man anpassen kann.
.TP
.BI s5_use \ number
Falls
.I number
gleich 1 ist, verwende SOCKS 5, sonst nicht.
.TP
.BI s5_host \ host
Verwende als SOCKS-5-Server den Rechner
.IR host .
.TP
.BI s5_port \ port
Verbinde zum SOCKS-5-Server auf Port
.IR port .
.TP
.BI s5_auth \ number
Falls
.IR number
gleich 1 ist, authentifiziere beim SOCKS-5-Server mit Paßwort, ansonsten nicht.
.TP
.BI s5_name \ name
Verwende
.I name
als Benutzername beim SOCKS-5-Server.
.TP
.BI s5_pass \ password
Verwende Paßwort
.I password
beim SOCKS-5-Server.
.PP
Jetzt die Optionen:
.TP
.BI verbose \ level
Setzt die Ausfühlichkeit bei der Ausgabe auf
.IR level .
.TP
.BI auto_away \ time
Setzt die Zeit, nach der automatisch nach "abwesend" und "nicht verfügbar"
gewechselt wird, auf
.I time
Sekunden. Deaktiviere mit
.I 0
Sekunden.
.TP
.BI Screen_width \ width
Setzt die standardmäßige Bildschirmbreite auf
.IR width .
Wenn nicht gesetzt oder auf
.BR 0 ,
wird
.B 80
verwendet. Dies wird sehr selten benötigt, da normalerweise die
Bildschirmbreite zur Laufzeit bestimmt werden kann.
.TP
.BI set \ delbs\ on|off
Wenn es auf
.B on
gesetzt ist, funktioniert das DELETE-Zeichen wie ein Rückschritt. Wenn es auf
.B off
gesetzt ist, funktioniert es wie ein Löschen-Zeichen.
.TP
.BI set \ russian\ on|off
Aktiviere (\fBon\fR) oder deaktiviere (\fBoff\fR) russische Zeichenkonvertierung zwischen koi8-r/u und cp1251.
.TP
.BI set \ japanese\ on|off
Aktiviere oder deaktiviere japanische Zeichenkonvertierung zwischen Shift-JIS und EUC.
.TP
.BI set \ funny\ on|off
Aktiviere oder deaktiviere lustige Meldungen.
.TP
.BI set \ color\ on|off
Aktiviere oder deaktiviere Farben.
.TP
.BI set \ hermit\ on|off
Wenn es auf
.B on
gesetzt ist, ignoriere alle Nachrichten von Personen, die nicht auf der Kontaktliste sind.
.TP
.BI set \ log\ on|off
Aktiviere oder deaktiviere das Loggen.
.TP
.BI set \ logonoff\ on|off
Wenn geloggt wird, aktiviere oder deaktiviere das Loggen von sich verbindenden und ausloggenden Benutzern.
.TP
.BI set \ auto\ on|off
Aktiviere oder deaktiviere automatische Antworten.
.TP
.BI set \ uinprompt\ on|off
Aktiviere oder deaktiviere das Verwenden in der Eingabeaufforderung des Spitznamens, von dem
zuletzt eine Nachricht empfangen wurde.
.TP
.BI set \ linebreak\ type
Setzt den Zeilenumbruchtyp für eingehende Nachrichten auf
.IR type ,
der sein kann:
.BR simple ,
um ganz normal umzubrechen,
.BR break ,
um vor jeder Nachricht einen Zeilenumbruch zu machen,
.BR indent ,
um vor jeder Nachricht einen Zeilenumbruch zu machen und die
Nachricht einzurücken, und
.BR smart ,
um nur dann einen Zeilenumbruch vor der Nachricht zu machen,
wenn diese nicht in die aktuelle Zeile paßt.
.TP
.BI set \ tabs\ simple|cycle|cycleall
Wählt aus, wie mit der tab-Taste die Spitznamen durchgegangen werden.
Ältere Versionen von mICQ kannten nur
.BR simple ,
welches nur beim
.BR msg -Befehl
funktioniert und den Befehl vervollständigt und durch alle
Kontakte geht, von denen schon Nachrichten empfangen wurden bzw. zu
denen schon Nachrichten geschickt wurden. Schon getippter Text
nach dem Spitznamen ging verloren.
.B cycle
hingegen geht alle Kontakte der Kontaktliste durch, die verbunden sind.
Es läßt die sonstige Eingabe intakt, vervollständigt allerdings auch nicht
den
.BR msg -Befehl.
.B cycleall
ist wie
.BR cycle ,
nur daß alle, nicht nur die verbundenen, Kontakte durchgegangen werden.
.PP
Zuletzt können noch einige Texte definiert werden:
.TP
.BI color\ scheme \ nr
Wählt das Farbschema
.I nr
aus.
.TP
.BI color \ use\ color
Wählt die Farbe
.I color
für
.I use
aus.
.IR use
kann dabei
.BR none ,
.BR server ,
.BR client ,
.BR message ,
.BR contact ,
.BR sent ,
.BR ack ,
.BR error
oder
.BR incoming
sein,
.IR color
kann dabei beliebig viele von
.BR black
(schwarz),
.BR red
(red),
.BR green
(green),
.BR yellow
(gelb),
.BR blue
(blaub),
.BR magenta
(magenta),
.BR cyan
(hellblau),
.BR white
(weiß),
.BR none
(keine) oder
.BR bold
(fett) sein
.RB ( bold
muß allerdings zuletzt kommen, um wirksam zu sein), oder eine
beliebige Zeichenkette, die auf dem Terminal des Benutzers
die gewünschte Farbe auswählt.
.TP
.BI logplace \ file|dir
Logge in die Datei
.IR file ,
oder logge in einzelne Dateien im Verzeichnis
.IR dir .
Ein Pfad wird dabei als Verzeichnis aufgefaßt, wenn
er mit einem
.I /
endet.
.TP
.BI sound \ on|off|cmd
Aktiviere oder deaktiviere Piepsen. Ist das Argument weder
.B on
noch
.B off,
dann ist es ein Programm, das stattdessen ausgeführt wird.
.TP
.BI soundonline \ on|off|cmd
Wie oben, aber nur bei sich verbindenden Kontakten.
.TP
.BI soundoffline \ on|off|cmd
wie oben, aber nur bei sich ausloggenden Kontakten.
.TP
.BI receivescript \ cmd
Befehl, der ausgeführt wird, wenn eine Nachricht eingeht.
Wenn dieser leer ist, wird nichts ausgeführt.
.TP
.BI auto \ status\ string
Setze die automatische Antwort im Status
.I status
auf
.I string .
Diese Option kann für alle möglichen Werte
.BR away ,
.BR na ,
.BR dnd ,
.BR occ ,
.B inv 
oder
.B ffc
für
.I status
wiederholt werden.

.SH TEXTE - strings
Dieser Abschnitt enthält umbenannte Befehle.
.TP
.BI alter \ old\ new
Nenne den Befehl
.I old
in
.I new
um. Der alte Name kann weiterverwendet werden, wenn er nicht
mit einem neuen
.I new
übereinstimmt. Für mögliche Befehle siehe
.BR micq (7).
Diese Option kann beliebig wiederholt werden.

.SH KONTAKTE - contacts
Dieser Abschnitt enthält die Kontakt-Liste.
.TP
.I [*][~][^] uin nick
Mach den Benutzer mit der Benutzernummer
.I uin
bekannt unter dem Spitznamen
.IR nick .
Ist
.B *
gegeben, dann ist man diesem Kontakt gegenüber auch sichtbar, wenn
man eigentlich unsichtbar ist. Ist
.B ~
gegeben, ist man diesem Kontakt gegenüber immer nicht verbunden. Ist
.B ^
gegeben, dann ignoriere diesen Kontakt. Taucht eine
Benutzernummer mehrfach auf, dann werden alle außer dem ersten
als Alias behandelt.

Hinweis: Die Kontaktliste muß immer der letzte Teil dieser Datei sein.
.SH SIEHE AUCH
.BR micq (1),
.BR micq (7)
.SH AUTOR
Diese Hilfeseite wurde von James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
geschrieben. Sie wurde an die neue Syntax angepaßt
und ins Deutsche übersetzt von Rüdiger Kuhlmann.
