.\" $Id$
.\"  EN: micq.7,v 1.16 2002/08/09 01:22:20
.TH MICQ 7 mICQ DE
.SH NAME
.B mICQ
\- interaktive Befehle
.SH BESCHREIBUNG
Diese Hilfeseite beschreibt die Befehle, die aus mICQ heraus verwendet
werden können. Diese Seite enthält prinzipiell dieselben Informationen wie
die Hilfe innerhalb von mICQ.
.SH BEFEHLE
.TP
.BI trans \ [Sprache|Nr]\ ...
Wechsle zur Sprache
.IR Sprache ,
gegeben durch ihren ISO-Sprachcode, oder gibt die Übersetzung
der Textes mit der Nummer
.I Nr
aus. Um die durch die Umgebungsvariablen
.BR LANG ,
.B LC_ALL
und
.B LC_MESSAGES
bestimmte Sprache auszuwählen, kann
.BR ! ,
.B auto
oder
.B default
verwendet werden. Um überhaupt keine Übersetzung auszuwählen,
kann man
.BR . ,
.B none
oder
.B unload
verwenden. Um zur Fehlersuche die Nummern der
übersetzten Texte mitauszugeben, kann man
.B debug
voranstellen. Um an ein paar Stellen lustige Meldungen
zu verwenden, kann man
.B _fun
anhängen.
.sp
Die Dateien aus ~/.micq/i18n/*.i18n haben Vorrang  über die globalen
Dateien, während die "lustigen" über die normalen Vorrang haben.
.sp
Tatsächlich kann man sogar soviele Argumente angeben, wie man will,
um z.B. den 117. Text in Deutsch auszugeben und dann zur Standardsprache
zurückzukehren, gebe man "trans de 117 default" ein.
.TP
.B tabs 
Zeigt eine Liste von Benutzern, zu denen man bereits Nachrichten
geschickt hat bzw. von denen man bereits welche Empfangen hat, und
die man mittels das <tab>-Taste durchgehen kann.
.TP
.B save
Speichert die aktuellen Einstellungen in der Konfigurationsdatei ab,
welches
.I ~/.micq/micqrc
ist, wenn nicht anders angegeben. Vorsicht, dies wird alle hinzugefügten
Kommentare in dieser Datei überschreiben.
.TP
.BI r \ [Nachricht]
Antwortet auf die zuletzt empfangene Nachricht. Ohne
.I Nachricht
wird der Mehr-Zeilen-Modus aktiviert. Um eine Mehr-Zeilen-Nachricht abzuschicken,
gebe man einen Punkt
.RB ( . )
auf einer Zeile für sich ein. Um die Nachricht abzubrechen, gebe man ein Doppelkreuz
.RB ( # )
auf einer Zeile für sich ein.
.TP
.BI a \ [Nachricht]
Schickt eine Nachricht zur gleichen Person wie die letzte Nachricht.
Siehe 
.B r
für das Verhalten ohne
.IR Nachricht .
.TP
.BI msg \ Benutzernummer|Spitzname\ [Nachricht]
Schickt eine Nachricht an
.IR Benutzernummer|Spitzname .
Siehe
.B r 
für das Verhalten ohne
.IR Nachricht .
.TP
.BI url \ Benutzernummer|Spitzname\ URL\ Nachricht
Schickt eine
.I Nachricht
über die Seite
.I URL
an
.IR Benutzernummer|Spitzname .
.TP
.BI sms \ HandyNr\ Nachricht
Verschickt eine SMS-Nachricht
.I Nachricht
an die Handy-Nummer
.IR HandyNr ,
die in der Form +<Landeskode><Nummer> sein muß.
.TP
.B msga
Schickt eine Mehr-Zeilen-Nachricht an jeden auf der Kontaktliste. Siehe
auch
.BI r .
.TP
.BI resend \ Benutzernummer|Spitzname\ ...
Schickt die letzte Nachricht erneut an
.I Benutzernummer
oder 
.IR Spitzname .
Es können beliebig viele Argumente angegeben werden.
.TP
.B uptime
Zeigt an, wie lange mICQ bereits läuft.
.TP
.BI last \ [Kontakt]
Zeigt eine Liste von Benutzern, von denen bereits eine Nachricht kam,
oder die letzte empfangene Nachricht von
.IR Kontakt ,
welches eine
.I Benutzernummer
oder ein
.I Spitzname
sein kann.
.TP
.BI verbose \ [verb]
Setzt die Ausführlichkeit der Ausgaben von mICQ auf
.IR verb ,
oder zeigt die aktuelle Ausführlichkeit an. Die Ausführlichkeit ist eine Menge von
Werten, die aufaddiert werden:
.RS
.TP
.B 8
Zeige Protokoll-Fehler.
.TP
.B 16
Zeige Erzeugung und Entfernung von Paketen.
.TP
.B 32
Zeige hinzugefügte und entfernte Warteschlangen-Ereignisse.
.TP
.B 64
Zeige Erzeugung und Entfernung von Verbindungen.
.TP
.B 256
Zeige Version-6-Pakete mit hexadezimalem Abbild.
.TP
.B 4096
Zeige Version-7/8-Pakete.
.TP
.B 8192
Zeige zusätzlich das hexadezimale Abbild.
.TP
.B 16284
Speichere diese Pakete in eine Datei.
.TP
.B 65536
Zeige Direktverbindungs-Pakete.
.TP
.B 131072
Zeige zusätzlich das hexadezimale Abbild.
.TP
.B 262144
Speichere diese Pakete in eine Datei.
.TP
.B 2097152
Zeige den Direktverbindungs-Handschlag.
.TP
.B 4194304
Zeige den Verbindungsaufbau von Verbindungen.
.RE

.RS
In jedem Fall bewirkt eine Ausfühlichkeit größer als 0 die Ausgabe von mehr
Informationen, und eine größer als 1 von noch mehr.
.RE
.TP
.B clear
Löscht den Bildschirm.
.TP
.BI sound \ [Befehl]
Schaltet Piepsen ein oder aus, oder verwende stattdessen
.IR Befehl .
.TP
.BI soundonline \ [Befehl]
Schaltet Piepsen für sich verbindende Benutzer ein oder aus, oder verwende stattdessen
.IR Befehl .
.TP
.BI soundoffline \ [Befehl]
Schaltet Piepsen für sich ausloggende Benutzer ein oder aus, oder verwende stattdessen
.IR Befehl .
.TP
.B q
Beendet mICQ.
.TP
.BI auto \ [on|off]
Schaltet automatische Antworten ein oder aus, oder zeigt die aktuellen
automatischen Antworten an.
.TP
.BI auto \ Status\ Nachricht
Setzt die automatische Antwort für den Status
.I Status
auf
.IR Nachricht .
.TP
.BI autoaway \ [Zeit|on|off]
Gehe nach
.I Zeit
Sekunden automatisch in den Status "abwesend" bzw. "nicht verfügbar",
oder schaltet dies an (\fBon\fR) (mit der letzten verwendeten Zeit) oder ab (\fBoff\fR).
Eine Zeit von 0 schaltet dies ebenfalls ab. Ist kein Argument gegeben,
zeigt es die aktuelle Einstellung an.
.TP
.BI alter \ Befehl\ Neu
Mache den ursprünglich oder vorher als
.I Befehl
bekannten Befehl unter dem Namen
.I Neu
bekannt.
.TP
.BI auth \ Benutzernummer|Spitzname
Erlaubt es
.IR Benutzernummer|Spitzname ,
Sie zu seiner Kontaktliste hinzuzufügen.
.TP
.BI rand \ [Nummer]
Findet einen zufälligen Kontakt in der Interessengruppe
.IR Nummer ,
oder zeigt alle Interessengruppen an.
.TP
.BI pass \ Paßwort
Setzt das Paßwort auf
.IR Paßwort . 
.br
Hinweis: Sie müssen danach mit
.B save
abspeichern, um diese Änderung dauerhaft zu machen, falls Sie Ihr Paßwort
in Ihrem
.I ~/.micq/micqrc
abspeichern (siehe
.BR micqrc (7),
oder Ihr Paßwort wird beim nächsten Login fehlerhaft sein.
.TP
.B search
.TP
.BI search \ eMail
.TP
.BI search \ Spitzname
.TP
.BI search \ Vorname\ Nachname
Sucht nach einem Benutzer mit der eMail-Adresse
.IR eMail ,
mit dem Spitznamen
.IR Spitzname ,
der kein @ enthalten darf, oder mit
.I Vorname
als Vor- und
.I Nachname
als Nachname. Ist kein Argument gegeben, frage nach
Spitznamen, Vornamen, Nachnamen, eMail-Adresse und einem
Haufen anderer Daten, nach denen man suchen kann.
.TP
.BI add \ Benutzernummer\ [Spitzname]
Fügt die Benutzernummer
.I Benutzernummer
zur Kontaktliste hinzu unter dem Namen
.IR Spitzname ,
oder nennt
.I Benutzernummer
in
.I Spitzname
um. Ist
.I Spitzname
nicht gegeben, benutze
.I Benutzernummer
als Spitzname.
.br
Hinweis: Sie müssen mit
.B save
abspeichern, um diese Änderungen dauerhaft zu machen.
.TP
.BI rem \ Spitzname
Entfernt
.I Spitzname
von der Kontaktliste.
.br
Hinweis: Sie müssen mit
.B save
abspeichern, um diese Änderungen dauerhaft zu machen.
.TP
.BI togvis \ Spitzname
Ändert, ob
.I Spitzname
sehen kann, wenn Sie unsichtbar sind.
.TP
.BI toginvis \ Spitzname
Ändert, ob
.I Spitzname
Sie niemals sehen kann.
.TP
.BI togig \ Spitzname
Ändert, ob Nachrichten und Statusänderungen von
.I Spitzname
ignoriert werden sollen.
.TP
.BI info \ Benutzernummer|Spitzname
Zeigt alle Daten über
.IR Benutzernummer|Spitzname .
.TP
.B e
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind.
.TP
.B w
Zeigt alle Kontakte auf der Kontaktliste.
.TP
.B ee
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind, mit mehr Details.
.TP
.B ww
Zeigt alle Kontakte auf der Kontaktliste, mit mehr Details.
.TP
.B wide
Zeigt alle Kontakte auf der Kontaktliste in einem breiten Format.
.TP
.B ewide
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind, in einem breiten Format.
.TP
.B s \ [Spitzname]
Zeigt den aktuellen Status, oder die Details zu dem angegebenen Kontakt.
.TP
.B i
Zeigt alle Kontakte auf der Ignorieren-Liste.
.TP
.BI status \ [Spitzname]
Zeigt den Status von
.IR Spitzname ;
dies beinhaltet die IP-Adresse, verwendete Version des ICQ-Protokolls für
Direktverbindungen und den Verbindungstyp, oder gebe für alle Kontakte
die benutzernummer, den Spitznamen, den Status und den Zeitpunkt des
letzten Verbunden-Seins aus.
.sp
Hinweis: Dieses Kommando ist obsolet; man verwende
.B s
oder
.B ww
stattdessen.
.TP
.BI reg \ Paßwort
Erzeugt eine neue Benutzernummer mit dem Paßwort
.IR Paßwort .
.TP
.BI change \ [Nummer\ [Nachricht]]
Wechselt in den Status
.IR Nummer ,
und setze optional die automatische Antwort für diesen Status auf
.IR Nachricht .
Ohne eine Nummer: liste die verfügbaren Nummern auf.
.TP
.B online \ [Nachricht]
Wechselt in den Status "verbunden". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B away \ [Nachricht]
Wechselt in den Status "abwesend". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B na \ [Nachricht]
Wechselt in den Status "nicht verfügbar". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B occ \ [Nachricht]
Wechselt in den Status "beschäftigt". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B dnd \ [Nachricht]
Wechselt in den Status "nicht stören". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B ffc \ [Nachricht]
Wechselt in den Status "frei für Plaudereien". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B inv
Wechselt in den Status "unsichtbar".
.TP
.B update
Aktualisiert die auf dem Server gespeicherten Benutzerinformationen (eMail-Adresse, Spitzname, und so weiter).
.TP
.B other
Aktualisiert weitergehende Benutzerinformationen wie Alter und Geschlecht.
.TP
.B about
Aktualisiert den Punkt "Über" der Benutzerinformationen.
.TP
.BI set \ Option\ Wert
Schaltet die Option
.I Option
entweder
.I an
.RB ( on )
oder
.I aus
.RB ( off ).
.I Option
kann
.B color
(Farben verwenden),
.B funny
(lustige Meldungen)
oder
.B quiet
(weniger Meldungen) sein.
.TP
.BI peek \ Spitzname
Überprüft, ob
.I Spitzname
tatsächlich verbunden ist oder nicht. Dies mißbraucht einen Fehler im ICQ-Protokoll, um
dies herauszufinden; es kann nur herausgefunden werden, ob verbunden oder nicht.
.TP
.BI setr \ [Nummer]
Setzt die Interessengruppe für zufällige Kontakte auf
.IR Nummer .
Ohne Argumente: listet mögliche Interessengruppen auf.
.TP
.BI tcp \ Befehl\ Benutzernummer|Spitzname
wendet den Befehl
.I Befehl
auf den durch Benutzernummer
.I Benutzernummer
oder Spitzname
.I Spitzname
angegebenen Benutzer an.
.RS
.TP
.B open
Öffnet eine Direktverbindung über TCP zu diesem Benutzer.
.TP
.B close
Schließt eine Direktverbindung zu diesem Benutzer bzw. setzt sie zurück.
.TP
.B off
Deaktiviert Direktverbindungen für diesen Benutzer.
.TP
.B auto
Fragt die aktuelle automatische Antwort des Benutzers ab.
.TP
.B away
Fragt die aktuelle automatische Antwort für "abwesend" des Benutzers ab.
.TP
.B dnd
Fragt die aktuelle automatische Antwort für "nicht stören" des Benutzers ab.
.TP
.B na
Fragt die aktuelle automatische Antwort für "nicht verfügbar" des Benutzers ab.
.TP
.B occ
Fragt die aktuelle automatische Antwort für "beschäftigt" des Benutzers ab.
.TP
.B ffc
Fragt die aktuelle "für Plaudereien frei"-Meldung des Benutzers ab.
.TP
.BI file \ [Datei\ als]...\ Beschreibung
Sende Dateien zum Benutzer. Es darf beliebig viele Paare von tatsächlichen Dateinamen
.I Datei
und dem gegenüber präsentierten Dateinamen
.I als
geben. Wenn
.IR als
.RB ' / '
is, dann gebe den Dateinamen ohne den Pfad an, wenn
.IR als
.RB ' . '
ist, dann gebe den richtigen Dateinamen an.
.sp
Hinweis: Weder Dateinamen noch die Beschreibung darf derzeit Leerzeichen enthalten.
.RE
.TP
.BI conn \ [Befehl\ Nr]
Zeigt alle offenen Verbindungen, oder wendet den Befehl
.I Befehl
auf die Verbindung
.I Nr 
an.
.RS
.TP
.B open
Öffne die angegebene, oder die erster Server-Verbindung.
.TP
.B login
dito
.TP
.B remove
Schließe und entferne die angegebene (temporäre) Verbindung.
.TP
.B select
Wählt die angegebene Server-Verbindung als die aktuelle aus.
.I Nr
kann dabei die sowohl die Verbindungsnummer als auch die in der
Server-Verbindung verwendete Benutzernummer sein.
.RE
.BI contact \ [Befehl]
Bearbeitet die Server-seitige Kontaktliste:
.RS
.TP
.B show
Läd die Server-seitige Kontaktliste herunter und zeigt sie an.
.TP
.B diff
Läd die Server-seitige Kontaktliste herunter und zeigt alle Kontakte
(also Benutzernummer/Spitzname-Paare) an, die nicht in der lokalen
Kontaktliste sind.
.TP
.B import
Läd die Server-seitige Kontaktliste herunter und fügt alle Kontakte
der lokalen Kontaktliste hinzu.
.RE

.SH SIEHE AUCH
.BR micq (1),
.BR micqrc (5)
.SH AUTOR
Diese Hilfeseite wurde von James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
erschaffen, um eine Referenz für alle interaktiven Befehle in
.B mICQ
zu erschaffen. Sie wurde übersetzt von Rüdiger Kuhlmann.
