.\" $Id$ -*- nroff -*-
.\"  EN: micq.7,v 1.28 2002/08/09 01:22:20
.TH MICQ 7 mICQ DE
.SH NAME
.B mICQ
\- interaktive Befehle
.SH BESCHREIBUNG
Diese Hilfeseite beschreibt die Befehle, die aus mICQ heraus verwendet
werden k\(:onnen. Diese Seite enth\(:alt prinzipiell dieselben Informationen wie
die Hilfe innerhalb von mICQ.
.SH BEFEHLE
.TP
.BI trans \ [Sprache|Nr]\ ...
Wechsle zur Sprache
.IR Sprache ,
gegeben durch ihren ISO-Sprachcode, oder gibt die \(:Ubersetzung
der Textes mit der Nummer
.I Nr
aus. Um die durch die Umgebungsvariablen
.BR LANG ,
.B LC_ALL
und
.B LC_MESSAGES
bestimmte Sprache auszuw\(:ahlen, kann
.BR ! ,
.B auto
oder
.B default
verwendet werden. Um \(:uberhaupt keine \(:Ubersetzung auszuw\(:ahlen,
kann man
.BR . ,
.B none
oder
.B unload
verwenden. Um zur Fehlersuche die Nummern der
\(:ubersetzten Texte mitauszugeben, kann man
.B debug
voranstellen. Um an ein paar Stellen lustige Meldungen
zu verwenden, kann man
.B _fun
anh\(:angen.
.sp
Die Dateien aus ~/.micq/i18n/*.i18n haben Vorrang  \(:uber die globalen
Dateien, w\(:ahrend die "lustigen" \(:uber die normalen Vorrang haben.
.sp
Tats\(:achlich kann man sogar soviele Argumente angeben, wie man will,
um z.B. den 117. Text in Deutsch auszugeben und dann zur Standardsprache
zur\(:uckzukehren, gebe man "trans de 117 default" ein.
.TP
.B tabs 
Zeigt eine Liste von Benutzern, zu denen man bereits Nachrichten
geschickt hat bzw. von denen man bereits welche Empfangen hat, und
die man mittels das <tab>-Taste durchgehen kann.
.TP
.B save
Speichert die aktuellen Einstellungen in der Kon\(figurationsdatei ab,
welches
.I ~/.micq/micqrc
ist, wenn nicht anders angegeben. Vorsicht, dies wird alle hinzugef\(:ugten
Kommentare in dieser Datei \(:uberschreiben.
.TP
.BI r \ [Nachricht]
Antwortet auf die zuletzt empfangene Nachricht. Ohne
.I Nachricht
wird der Mehr-Zeilen-Modus aktiviert. Um eine Mehr-Zeilen-Nachricht abzuschicken,
gebe man einen Punkt
.RB ( . )
auf einer Zeile f\(:ur sich ein. Um die Nachricht abzubrechen, gebe man ein Doppelkreuz
.RB ( # )
auf einer Zeile f\(:ur sich ein.
.TP
.BI a \ [Nachricht]
Schickt eine Nachricht zur gleichen Person wie die letzte Nachricht.
Siehe 
.B r
f\(:ur das Verhalten ohne
.IR Nachricht .
.TP
.BI msg \ Benutzernummer|Spitzname\ [Nachricht]
Schickt eine Nachricht an
.IR Benutzernummer|Spitzname .
Siehe
.B r 
f\(:ur das Verhalten ohne
.IR Nachricht .
.TP
.BI url \ Benutzernummer|Spitzname\ URL\ Nachricht
Schickt eine
.I Nachricht
\(:uber die Seite
.I URL
an
.IR Benutzernummer|Spitzname .
.TP
.BI sms \ HandyNr\ Nachricht
Verschickt eine SMS-Nachricht
.I Nachricht
an die Handy-Nummer
.IR HandyNr ,
die in der Form +<Landeskode><Nummer> sein mu\(ss.
.TP
.B msga
Schickt eine Mehr-Zeilen-Nachricht an jeden auf der Kontaktliste. Siehe
auch
.BI r .
.TP
.BI resend \ Benutzernummer|Spitzname\ ...
Schickt die letzte Nachricht erneut an
.I Benutzernummer
oder 
.IR Spitzname .
Es k\(:onnen beliebig viele Argumente angegeben werden.
.TP
.B uptime
Zeigt an, wie lange mICQ bereits l\(:auft.
.TP
.BI last \ [Kontakt]
Zeigt die zuletzt empfangene Nachricht von
.IR Kontakt ,
welches eine
.I Benutzernummer
oder ein
.I Spitzname
sein kann, oder von allen, die bisher eine Nachricht geschickt haben.
.TP
.BI verbose \ [verb]
Setzt die Ausf\(:uhrlichkeit der Ausgaben von mICQ auf
.IR verb ,
oder zeigt die aktuelle Ausf\(:uhrlichkeit an. Die Ausf\(:uhrlichkeit ist eine Menge von
Werten, die aufaddiert werden:
.RS
.TP
.B 8
Zeige Protokoll-Fehler.
.TP
.B 16
Zeige Erzeugung und Entfernung von Paketen.
.TP
.B 32
Zeige hinzugef\(:ugte und entfernte Warteschlangen-Ereignisse.
.TP
.B 64
Zeige Erzeugung und Entfernung von Verbindungen.
.TP
.B 256
Zeige Version-6-Pakete mit hexadezimalem Abbild.
.TP
.B 4096
Zeige Version-7/8-Pakete.
.TP
.B 8192
Zeige zus\(:atzlich das hexadezimale Abbild.
.TP
.B 16284
Speichere diese Pakete in eine Datei.
.TP
.B 65536
Zeige Direktverbindungs-Pakete.
.TP
.B 131072
Zeige zus\(:atzlich das hexadezimale Abbild.
.TP
.B 262144
Speichere diese Pakete in eine Datei.
.TP
.B 2097152
Zeige den Direktverbindungs-Handschlag.
.TP
.B 4194304
Zeige den Verbindungsaufbau von Verbindungen.
.RE

.RS
In jedem Fall bewirkt eine Ausf\(:uhlichkeit gr\(:o\(sser als 0 die Ausgabe von mehr
Informationen, und eine gr\(:o\(sser als 1 von noch mehr.
.RE
.TP
.B clear
L\(:oscht den Bildschirm.
.TP
.BI sound \ [Befehl]
Schaltet Piepsen ein oder aus, oder verwende stattdessen
.IR Befehl .
.TP
.BI soundonline \ [Befehl]
Schaltet Piepsen f\(:ur sich verbindende Benutzer ein oder aus, oder verwende stattdessen
.IR Befehl .
.TP
.BI soundoffline \ [Befehl]
Schaltet Piepsen f\(:ur sich ausloggende Benutzer ein oder aus, oder verwende stattdessen
.IR Befehl .
.TP
.B q
Beendet mICQ.
.TP
.BI auto \ [on|off]
Schaltet automatische Antworten ein oder aus, oder zeigt die aktuellen
automatischen Antworten an.
.TP
.BI auto \ Status\ Nachricht
Setzt die automatische Antwort f\(:ur den Status
.I Status
auf
.IR Nachricht .
.TP
.BI autoaway \ [Zeit|on|off]
Gehe nach
.I Zeit
Sekunden automatisch in den Status "abwesend" bzw. "nicht verf\(:ugbar",
oder schaltet dies an (\fBon\fR) (mit der letzten verwendeten Zeit) oder ab (\fBoff\fR).
Eine Zeit von 0 schaltet dies ebenfalls ab. Ist kein Argument gegeben,
zeigt es die aktuelle Einstellung an.
.TP
.BI alter \ Befehl\ Neu
Mache den urspr\(:unglich oder vorher als
.I Befehl
bekannten Befehl unter dem Namen
.I Neu
bekannt.
.TP
.BI auth \ [req|grant|deny|add]\ Benutzernummer|Spitzname
Erlaubt es
.IR Benutzernummer|Spitzname ,
Sie zu seiner Kontaktliste hinzuzuf\(:ugen
.RB ( grant ),
verbietet dies
.RB ( deny ),
beantragt dies
.RB ( req )
oder teilt das Hinzuf\(:ugen nach Autorisierung mit
.RB ( add ).
.TP
.BI rand \ [Nummer]
Findet einen zuf\(:alligen Kontakt in der Interessengruppe
.IR Nummer ,
oder zeigt alle Interessengruppen an.
.TP
.BI pass \ Pa\(sswort
Setzt das Pa\(sswort auf
.IR Pa\(sswort . 
.br
Hinweis: Sie m\(:ussen danach mit
.B save
abspeichern, um diese \(:Anderung dauerhaft zu machen, falls Sie Ihr Pa\(sswort
in Ihrem
.I ~/.micq/micqrc
abspeichern (siehe
.BR micqrc (7),
oder Ihr Pa\(sswort wird beim n\(:achsten Login fehlerhaft sein.
.TP
.B search
.TP
.BI search \ eMail
.TP
.BI search \ Spitzname
.TP
.BI search \ Vorname\ Nachname
Sucht nach einem Benutzer mit der eMail-Adresse
.IR eMail ,
mit dem Spitznamen
.IR Spitzname ,
der kein @ enthalten darf, oder mit
.I Vorname
als Vor- und
.I Nachname
als Nachname. Ist kein Argument gegeben, frage nach
Spitznamen, Vornamen, Nachnamen, eMail-Adresse und einem
Haufen anderer Daten, nach denen man suchen kann.
.TP
.BI add \ Spitzname\ Zweit-Name
.BI add \ Benutzernummer\ [Spitzname]
F\(:ugt den Benutzer mit Benutzernummer
.I Benutzernummer
zur Kontaktliste unter dem Namen
.IR Spitzname
hinzu oder vergibt einen Zweit-Namen
.I Zweit-Name
f\(:ur
.IR Spitzname .
Ist
.I Spitzname
nicht angegeben, benutze
.I Benutzernummer
als Spitzname.
.br
Hinweis: Sie m\(:ussen mit
.B save
abspeichern, um diese \(:Anderungen dauerhaft zu machen.
.TP
.BI rem \ Zweit-Name
Entfernt den Zweit-Namen
.IR Zweit-Name .
Wenn dies der einzige Name ist, entferne Kontakt
von der Kontaktliste.
.br
Hinweis: Sie m\(:ussen mit
.B save
abspeichern, um diese \(:Anderungen dauerhaft zu machen.
.TP
.BI togvis \ Spitzname
\(:Andert, ob
.I Spitzname
sehen kann, wenn Sie unsichtbar sind.
.TP
.BI toginvis \ Spitzname
\(:Andert, ob
.I Spitzname
Sie niemals sehen kann.
.TP
.BI togig \ Spitzname
\(:Andert, ob Nachrichten und Status\(:anderungen von
.I Spitzname
ignoriert werden sollen.
.TP
.BI f[inger] \ Benutzernummer|Spitzname
.TP
.BI info \ Benutzernummer|Spitzname
Zeigt alle Daten \(:uber
.IR Benutzernummer|Spitzname .
.TP
.B e
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind.
.TP
.B w
Zeigt alle Kontakte auf der Kontaktliste.
.TP
.B ee
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind, mit mehr Details.
.TP
.B ww
Zeigt alle Kontakte auf der Kontaktliste, mit mehr Details.
.TP
.B wide
Zeigt alle Kontakte auf der Kontaktliste in einem breiten Format.
.TP
.B ewide
Zeigt alle Kontakte auf der Kontaktliste, die verbunden sind, in einem breiten Format.
.TP
.B s \ [Spitzname]
Zeigt den aktuellen Status, oder die Details zu dem angegebenen Kontakt.
.TP
.B i
Zeigt alle Kontakte auf der Ignorieren-Liste.
.TP
.BI status \ [Spitzname]
Zeigt den Status von
.IR Spitzname ;
dies beinhaltet die IP-Adresse, verwendete Version des ICQ-Protokolls f\(:ur
Direktverbindungen und den Verbindungstyp, oder gebe f\(:ur alle Kontakte
die benutzernummer, den Spitznamen, den Status und den Zeitpunkt des
letzten Verbunden-Seins aus.
.sp
Hinweis: Dieses Kommando ist obsolet; man verwende
.B s
oder
.B ww
stattdessen.
.TP
.BI reg \ Pa\(sswort
Erzeugt eine neue Benutzernummer mit dem Pa\(sswort
.IR Pa\(sswort .
.TP
.BI change \ [Nummer\ [Nachricht]]
Wechselt in den Status
.IR Nummer ,
und setze optional die automatische Antwort f\(:ur diesen Status auf
.IR Nachricht .
Ohne eine Nummer: liste die verf\(:ugbaren Nummern auf.
.TP
.B online \ [Nachricht]
Wechselt in den Status "verbunden". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B away \ [Nachricht]
Wechselt in den Status "abwesend". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B na \ [Nachricht]
Wechselt in den Status "nicht verf\(:ugbar". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B occ \ [Nachricht]
Wechselt in den Status "besch\(:aftigt". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B dnd \ [Nachricht]
Wechselt in den Status "nicht st\(:oren". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B ffc \ [Nachricht]
Wechselt in den Status "frei f\(:ur Plaudereien". Setzt optional die automatische Antwort auf
.IR Nachricht .
.TP
.B inv
Wechselt in den Status "unsichtbar".
.TP
.B update
Aktualisiert die auf dem Server gespeicherten Benutzerinformationen (eMail-Adresse, Spitzname, und so weiter).
.TP
.B other
Aktualisiert weitergehende Benutzerinformationen wie Alter und Geschlecht.
.TP
.B about
Aktualisiert den Punkt "\(:Uber" der Benutzerinformationen.
.TP
.BI set \ Option\ Wert
Schaltet die Option
.I Option
entweder
.I an
.RB ( on )
oder
.I aus
.RB ( off ).
.I Option
kann
.B color
(Farben verwenden),
.B funny
(lustige Meldungen)
oder
.B quiet
(weniger Meldungen) sein.
.TP
.BI peek \ Spitzname
\(:Uberpr\(:uft, ob
.I Spitzname
tats\(:achlich verbunden ist oder nicht. Dies mi\(ssbraucht einen Fehler im ICQ-Protokoll, um
dies herauszu\(finden; es kann nur herausgefunden werden, ob verbunden oder nicht.
.TP
.BI setr \ [Nummer]
Setzt die Interessengruppe f\(:ur zuf\(:allige Kontakte auf
.IR Nummer .
Ohne Argumente: listet m\(:ogliche Interessengruppen auf.
.TP
.BI peer \ Befehl\ Benutzernummer|Spitzname
wendet den Befehl
.I Befehl
auf den durch Benutzernummer
.I Benutzernummer
oder Spitzname
.I Spitzname
angegebenen Benutzer an.
.RS
.TP
.B open
\(:O\(ffnet eine Direktverbindung \(:uber TCP zu diesem Benutzer.
.TP
.B close
Schlie\(sst eine Direktverbindung zu diesem Benutzer bzw. setzt sie zur\(:uck.
.TP
.B off
Deaktiviert Direktverbindungen f\(:ur diesen Benutzer.
.TP
.B auto
Fragt die aktuelle automatische Antwort des Benutzers ab.
.TP
.B away
Fragt die aktuelle automatische Antwort f\(:ur "abwesend" des Benutzers ab.
.TP
.B dnd
Fragt die aktuelle automatische Antwort f\(:ur "nicht st\(:oren" des Benutzers ab.
.TP
.B na
Fragt die aktuelle automatische Antwort f\(:ur "nicht verf\(:ugbar" des Benutzers ab.
.TP
.B occ
Fragt die aktuelle automatische Antwort f\(:ur "besch\(:aftigt" des Benutzers ab.
.TP
.B ffc
Fragt die aktuelle "f\(:ur Plaudereien frei"-Meldung des Benutzers ab.
.TP
.BI file \ Datei\ Beschreibung
Sendet eine einzelne Datei
.I Datei
mit der Beschreibung
.IR Beschreibung .
.TP
.BI files \ [Datei\ als]...\ Beschreibung
Sende Dateien zum Benutzer. Es darf beliebig viele Paare von tats\(:achlichen Dateinamen
.I Datei
und dem gegen\(:uber pr\(:asentierten Dateinamen
.I als
geben. Wenn
.IR als
.RB ' / '
is, dann gebe den Dateinamen ohne den Pfad an, wenn
.IR als
.RB ' . '
ist, dann gebe den richtigen Dateinamen an.
.RE
.TP
.BI conn \ [Befehl\ Nr]
Zeigt alle o\(ffenen Verbindungen, oder wendet den Befehl
.I Befehl
auf die Verbindung
.I Nr 
an.
.RS
.TP
.B open
\(:O\(ffne die angegebene, oder die erster Server-Verbindung.
.TP
.B login
dito
.TP
.B close
Schlie\(sst die angegebene Verbindung. Tempor\(:are Verbindungen werden entfernt.
.TP
.B remove
Schlie\(sse und entferne die angegebene (tempor\(:are) Verbindung.
.TP
.B select
W\(:ahlt die angegebene Server-Verbindung als die aktuelle aus.
.I Nr
kann dabei die sowohl die Verbindungsnummer als auch die in der
Server-Verbindung verwendete Benutzernummer sein.
.RE
.BI contact \ [Befehl]
Bearbeitet die Server-seitige Kontaktliste:
.RS
.TP
.B show
L\(:ad die Server-seitige Kontaktliste herunter und zeigt sie an.
.TP
.B diff
L\(:ad die Server-seitige Kontaktliste herunter und zeigt alle Kontakte
(also Benutzernummer/Spitzname-Paare) an, die nicht in der lokalen
Kontaktliste sind.
.TP
.B import
L\(:ad die Server-seitige Kontaktliste herunter und f\(:ugt alle Kontakte
der lokalen Kontaktliste hinzu.
.RE

.SH SIEHE AUCH
.BR micq (1),
.BR micqrc (5)
.SH AUTOR
Diese Hilfeseite wurde von James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
erscha\(ffen, um eine Referenz f\(:ur alle interaktiven Befehle in
.B mICQ
zu erscha\(ffen. Sie wurde \(:ubersetzt von R\(:udiger Kuhlmann.
