.\" $ Id: $
.\"                                      Hey, EMACS: -*- nroff -*-
.Dd 2. August 2002
.Dt MICQ 1
.Os MICQ(1)
.\" Please adjust this date whenever revising the manpage.
.Sh NAME
.Ic micq
\- ein kleines ICQ-Programm, das im Text-Modus läuft
.Sh ÜBERSICHT
.Ic micq Op Ar -v
.Op Ar -f Dateiname
.br
.Sh BESCHREIBUNG
.Ic mICQ
ist ein text-basiertes ICQ-Programm, das viele Eigenschaften
des von Mirabilis erstellten ICQ unterstützt. Mit mICQ kann man
das Paßwort ändern, neue Benutzernumern erzeugen, die
Benutzerinformationen aktualisieren, andere Benutzer suchen,
und so weiter.
.Sh OPTIONEN
.Bl -tag -width flag
.It Fl v Op Ar level
Wählt den ausführlichen Modus bzw. setzt wie Ausführlichkeit auf
.Ar level .
.It Fl f Ar Dateiname
Benutzt
.Ar Dateiname
als Konfigurationsdatei.
.It Fl l Ar Datei|Verzeichnis
Benutzt
.Ar Datei
als Log-Datei, bzw. benutzt
.Ar Verzeichnis ,
um dort die nach Benutzern getrennte Log-Dateien abzulegen.
.It Fl ?, h
Gibt die Syntax aus.
.El

.Sh EIGENSCHAFTEN
.Ic mICQ
ist sehr portabel und läuft unter Linux, DOS, OS/2, Win32, BeOS, AmigaOS, GNU HURD
und jedem anderen modernen Unix-artigen System.
.Ic mICQ version 0.4.8
läuft unter Linux, AIX, HPUX, Tru64, teilweise BeOS und anderen
Unix-artigen Systemen. Andere Portierungen funktionieren
möglicherweise ebenfalls noch, und jeder, der dies
testen möchte, sei dazu aufgerufen.
.Sh GESCHICHTE
.Bl -tag -width Fl
.It 16. August 1998
Matthew D. Smith gibt die erste Version von micq frei,
gefolgt von 12 datierten Freigaben bis zum 25. Septembet 1998.
.It 5. Januar 2001
Matthew D. Smith stirb in einem Autounfall.
Die Benutzer fahren dort fort, wo Matthew aufgehört hat,
formieren
.Ic mICQ
unter der BSD-Lizenz neu und nehmen
die Entwicklung von
.Ic mICQ
wieder auf.
.It 10. Juni 2002
Version 0.4.9 wird unter der GPL-Lizenz freigegeben und implementiert
endlich die neue Version 8 des ICQ-Protokolls, und wurde von Rüdiger
Kuhlmann gemacht.
.Sh MAILINGLISTE
Die mICQ-Mailingliste ist
.Pa micq-list@mc.ukeer.de .
Informationen über die Anmeldung und Archive finden sich unter
.Pa http://www.micq.org/pipermail/micq-list/ .
.Sh HERUNTERLADEN
Über HTTP von
.Pa http://www.micq.org/download .
.br
Um die neueste Version aus dem CVS zu bekommen, gebe man ein:
.br
cvs -d:pserver:anonymous@micq.org:/usr/local/cvsroot co micq
.br
.Sh SIEHE AUCH
.Xr micqrc 5 ,
.Xr micq 7
.Sh DATEIEN
.Bl -tag -width Fl
.It ~/.micqrc
Alte Konfigurationsdatei für mICQ - veraltet.
.It ~/.micq/micqrc
Konfigurationsdatei für mICQ.
.It PREFIX/share/micq/*.i18n
Übersetzungsdateien mit Übersetzungen von alle Texten, die mICQ ausgibt.
.It ~/.micq/i18n/*.i18n
Benutzer-Änderungen zu diesen Dateien.
.It ~/.micq/history/
Standardverzeichnis für Log-Dateien.
.El
.Sh FEHLERBERICHTE
Fehlerberichte oder Kommentare bitte an Rüdiger Kuhlmann
<micq@ruediger-kuhlmann.de> (Deutsch oder Englisch) schicken.
.Sh AUTOR
Diese Hilfeseite basiert auf einer von James Morrison
.Pa <ja2morrison@student.math.uwaterloo.ca>,
die aus der minimalen Hilfeseite hervorging, die Jordi Mallach
.Pa <jordi@sindominio.net>
für das  Debian-GNU/Linux-System geschrieben hat.
Sie wurde von Rüdiger Kuhlmann übersetzt.
