.\" $Id: climmrc.5 1934 2005-02-20 12:39:28Z kuhlmann $ -*- nroff -*-
.\"  EN: climmrc.5,v 1.29 2005/01/09 16:20:18
.TH CLIMMRC 5 climm PT_BR
.SH NOME
.B ~/.climm/climmrc
\- O arquivo de configura\(,c\(~ao para o climm
.SH DESCRI\(,C\(~AO
Esta p\('agina de manual (man-page) descreve os arquivos de configura\(,c\(~ao
para o climm. Consiste em diversas se\(,c\(~oes que s\(~ao iniciadas por
.IR [se\(,c\(~ao] ,
onde
.I se\(,c\(~ao
\('e o nome da se\(,c\(~ao. Nomes de arquivos ou diret\('orios dados s\(~ao
relativos ao diret\('orio base, que normalmente \('e ~/.climm/.
.SH CONNECTION
A se\(,c\(~ao
.B Connection
(conex\(~ao) descreve uma conex\(~ao na rede ICQ. Normalmente existem 2 lados
da conex\(~ao, que s\(~ao co-relacionados: uma conex\(~ao para o servidor ICQ e
uma conex\(~ao para atender a requisi\(,c\(~oes "peer-to-peer" ou
pessoa-a-pessoa. Voc\(^e deve ter tamb\('em uma conex\(~ao de controle remoto:
isto significa que um FIFO \('e aberto, e linhas lidas nele s\(~ao
interpretadas da mesma maneira que linhas entradas.
.TP
.BI type \ <tipo>\ [auto]
Ajusta o tipo da conex\(~ao para
.IR tipo ,
o qual pode ser
.B server
para uma conex\(~ao com o servidor ICQ,
.B peer
para uma conex\(~ao do tipo "peer-to-peer" ou pessoa-a-pessoa, ou
.B remote
para um FIFO remotamente controlado. Se
.I auto
for usado como par\(^ametro, cria-se esta conex\(~ao direto na
inicializa\(,c\(~ao. Voc\(^e possivelmente quer isso, a menos que possua
diversos UINs, sendo ent\(~ao necess\('ario acertar isso na conex\(~ao
correspondente como o UIN que se esta usando no momento.
.TP
.BI version \ <nr>
Ajusta a vers\(~ao do protocolo usado na conex\(~ao para
.IR nr .
No entanto, preste aten\(,c\(~ao que para conex\(~oes para servidor, as
vers\(~oes
.BR 5 ,
.B 7
e
.B 8
s\(~ao permitidas, e para "peer-to-peer" ou pessoa-a-pessoa
.BR 6 ,
.B 7
e
.BR 8 .
FIFOs de controle remoto n\(~ao possuem uma vers\(~ao.
.TP
.BI server \ <servidor>
Ajusta o servidor ICQ padr\(~ao para
.IR servidor .
O padr\(~ao \('e
.IR login.icq.com .
N\(~ao utilizado para conex\(~oes "peer-to-peer". Para FIFOs de controle
remoto, este \('e o caminho para o FIFO a ser criado.
.TP
.BI port \ <porta>
Muda a porta de conex\(~ao no servidor para
.IR porta ,
ou muda a porta padr\(~ao pra "escutar" requisi\(,c\(~oes "peer-to-peer" para a
porta
.IR porta .
.TP
.BI uin \ <uin>
Muda o UIN (n\('umero ICQ) para fazer o login na rede ICQ para
.IR uin .
N\(~ao usado para conex\(~oes "peer-to-peer" nem FIFOs de controle remoto.
.TP
.BI password \ [<senha>]
Ajusta a senha para conex\(~ao na rede ICQ para
.IR password .
N\(~ao v\('alido para conex\(~oes "peer-to-peer". Se omitido, voc\(^e devera
digitar a senha na inicializa\(,c\(~ao do climm.
Obs: Usu\('arios BeOS precisam preencher este campo.
.TP
.BI status \ <nr>
Ajusta o "status" padr\(~ao ao efetuar login para
.IR nr .
Onde "status" pode ser:
.RS
.TP
0
online
.TP
1
away (distante)
.TP
5
not available (n\(~ao dispon\('ivel)
.TP
17
occupied (ocupado)
.TP
19
do not disturb (n\(~ao perturbe)
.TP
32
free for chat (livre pra bate-papo)
.TP
256
invisible (invis\('ivel)
.RE

.RS
Para conex\(~oes "peer-to-peer", este par\(^ametro \('e usado para a
configura\(,c\(~ao da conex\(~ao direta:
.TP
1
Atr\('as de um firewall e n\(~ao pode receber conex\(~oes diretas. Nem mesmo
tentativas.
.TP
2
Atr\('as de um firewall, mas usando SOCKS e podendo receber conex\(~oes.
.TP
4
Sem qualquer firewall. Este \('e o padr\(~ao.
.RE
.RS
FIFOs de controle remoto n\(~ao usam estas configura\(,c\(~oes.
.RE
.SH GENERAL
A se\(,c\(~ao
.B General
(geral) inclui as op\(,c\(~oes para SOCKS 5 (que poder\(~ao no futuro ganhar
sua pr\('opria se\(,c\(~ao), op\(,c\(~oes gerais, defini\(,c\(~oes iniciais
para script TCL e algumas strings a superp\(^or.
.TP
.BI s5_use \ <n\('umero>
Use
.I n\('umero
em 0 para desabilitar e 1 para habilitar.
.TP
.BI s5_host \ <endere\(,co>
Conecte ao servidor de proxy SOCKS 5 no endere\(,co
.IR endere\(,co .
.TP
.BI s5_port \ <porta>
Conecte ao servidor de proxy SOCKS 5 na porta
.IR porta .
.TP
.BI s5_auth \ <n\('umero>
Use
.I n\('umero
0 para ignorar autentica\(,c\(~ao e 1 para efetuar a autentica\(,c\(~ao.
.TP
.BI s5_name \ <nome>
Efetuar a identifica\(,c\(~ao como o usu\('ario
.I nome
no servidor proxy SOCKS 5.
.TP
.BI s5_pass \ <senha>
Efetuar a autentica\(,c\(~ao com a senha
.I senha
no servidor proxy SOCKS 5.
.PP
Algumas op\(,c\(~oes "book-keeping" normalmente est\(~ao no in\('icio do
arquivo climmrc:
.TP
.BI encoding\ arquivo\  codifica\(,c\(~ao
Ajusta a codifica\(,c\(~ao que ser\('a usada para textos neste arquivo para
.IR codifica\(,c\(~ao .
climm ir\('a sempre escrever este arquivo em UTF8.
.TP
.BI encoding\ local\ <codifica\(,c\(~ao>
Ajusta a codifica\(,c\(~ao do terminal do usu\('ario atualmente para
.IR codifica\(,c\(~ao .
Isto sobrep\(~oe a codifica\(,c\(~ao obtida das vari\('aveis de ambiente.
.br
.B Nota:
Usando isto causa o locale ser marcado como quebrado, causando assim caracteres
fora da faixa iso-8859-1 serem impressos no manipulador de entrada como
pontos de c\('odigo unicode hex pois o comprimento de sua c\('elula de tela
n\(~ao pode ser determinada mais com wcwidth(). Assim, sempre use o ajuste de
locale LC_CTYPE para for\(,car a codifica\(,c\(~ao de caractere usada.
.TP
.BI encoding\ remote \ <codifica\(,c\(~ao>
Ajusta a codifica\(,c\(~ao para usar com meta dados no servidor, incluindo a
senha para
.IR codifica\(,c\(~ao .
Esta codifica\(,c\(~ao tamb\('em \('e usada para comunica\(,c\(~ao com outros
contatos cujos clientes n\(~ao entendam mensagens utf8, a menos que uma
codifica\(,c\(~ao espec\('ifica seja selecionada para este contato.
Depreciado no climm 0.5; use a op\(,c\(~ao global
.I encoding
ao inv\('es.
.TP
.BI format \ <nr>
Ajusta o formato para este arquivo para
.IR nr .
O formato 2 é o atual, mas o formato 1 tamb\('e\('e aceito.
.PP
Agora, as demais op\(,c\(~oes:
.TP
.BI verbose \ <n\('ivel>
Muda o n\('ivel de informa\(,c\(~ao verbal para
.IR n\('ivel .
.TP
.BI auto_away \ <tempo>
Muda o tempo de inatividade para auto-away (distante) para
.I tempo
segundos. Mude para
.I 0
para desabilitar o auto-away.
.TP
.BI Screen_width \ <largura>
Muda a largura padr\(~ao da tela para
.IR largura .
Se configurado para
.IR 0 , \ 80
ser\('a usado como medida padr\(~ao. Este par\(^ametro dificilmente precisa ser
especificado, pois e poss\('ivel defini-lo em tempo de execu\(,c\(~ao
(run-time).
.TP
.BI set \ delbs\ on|off
Se configurado para
.BR on ,
faz com que a tecla "delete" funcione como um "back space". Quando configurado
para
.BR off ,
deixa a tecla "delete" funcionar normalmente.
.TP
.BI set \ funny\ on|off
Habilita ou desabilita as mensagens "engra\(,cadas" ("funny").
.TP
.BI set \ color\ on|off
Habilita ou desabilita o uso de cores.
.TP
.BI set \ hermit\ on|off
Se configurado para
.BR on ,
descarta todas as mensagens de qualquer pessoa que n\(~ao esteja na lista de
contatos.
Depreciado no climm 0.5, ajuste a op\(,c\(~ao global
.I ignore
para
.I on
para o mesmo efeito.
.TP
.BI set \ log\ on|off
Habilita ou desabilita o "logging" (hist\('orico).
Depreciado no climm 0.5, ajuste a op\(,c\(~ao global
.I logmess
para
.I on
para o mesmo efeito.
.TP
.BI set \ logonoff\ on|off
Quando gerando hist\('orico de mensagens, desabilita ou habilita a
gera\(,c\(~ao de hist\('orico de quando os usu\('arios ficam "online" e quando
saem.
Depreciado no climm 0.5, ajuste a op\(,c\(~ao global
.IR logmess \ e \ logchange
para
.I on
para o mesmo efeito.
.TP
.BI set \ auto\ on|off
Desabilita ou habilita as respostas autom\('aticas.
.TP
.BI set \ uinprompt\ on|off
Desabilita ou habilita o uso no prompt do ultimo nick a lhe mandar uma
mensagem.
.TP
.BI set \ autosave\ on|off
Desabilita ou habilita o salvamento autom\('atico do climmrc.
.TP
.BI set \ autofinger\ on|off
Desabilita ou habilita o "fingering" autom\('atico de novos UINs.
.TP
.BI set \ linebreak\ <tipo>
Configura o tipo da quebra de linha (line break) em mensagens recebidas para
.IR tipo ,
o qual pode ser
.B simple
para fazer da maneira convencional,
.B break
para se ter uma quebra de linha antes de cada mensagem,
.B indent
para haver uma quebra de linha e a indenta\(,c\(~ao (par\('agrafo), e
.B smart
para se ter uma quebra de linha apenas se a mensagem n\(~ao couber na linha
atual.
.TP
.BI set \ tabs\ simple|cycle|cycleall
Depreciado no climm 0.5, pois este usa um manipulador de tabs muito melhorado
agora que possui todas as caracter\('isticas anteriores.
.TP
.BI set \ silent\ <type>
Suprime alguma sa\('ida, como mudan\(,cas de estado para
.B on
e mudan\(,cas de estado, logins e logouts para
.BR complete .
Depreciado no climm 0.5, use as op\(,c\(~oes globais
.IR showchange \ e \ showonoff
como
.I on
para o mesmo efeito.
.TP
.BI options \ <options>
Set global options. See the
.I opt
command for details.
.TP
.BI chat \ <nr>
Seleciona o random chat group para
.IR nr .
Use
.B \-1
para desabilitar e
.B 49
para climm (o qual \('e padr\(~ao).
.TP
.B autoupdate \ <n\('ivel>
O n\('ivel atual de configura\(,c\(~oes autom\('aticas feitas. Ser\('a
aumentado para um valor maior cada vez que a configura\(,c\(~ao for atualizada
para um novo valor padr\(~ao. N\(~ao cometa o erro de ajustar para 0 para
desabilitar pois isto ter\('a o efeito de todas as atualiza\(,c\(~oes
serem refeitas.
.PP
Por \('ultimo, algumas "strings" que podem ser definidas:
.TP
.BI color\ scheme \ <nr>
Muda o esquema de cor para o n\('umero
.IR nr .
.TP
.BI color \ <uso>\ <cor>
Seleciona a
.IR cor
para o
.IR uso .
.IR uso
pode qualquer um entre
.BR none ,
.BR server ,
.BR client ,
.BR message ,
.BR contact ,
.BR sent ,
.BR ack ,
.BR error ,
.BR debug
ou
.BR incoming ,
enquanto que
.IR cor
pode ser qualquer uma entre
.BR black ,
.BR red ,
.BR green ,
.BR yellow ,
.BR blue ,
.BR magenta ,
.BR cyan ,
.BR white ,
.BR none ,
ou
.BR bold
ou uma combina\(,c\(~ao das anteriores
.RB ( bold ,
no entanto, precisa ser o ultimo par\(^ametro na defini\(,c\(~ao),
ou qualquer "string" que fa\(,ca o terminal do usu\('ario usar a cor desejada.
.TP
.BI logplace \ <arquivo>|<dir>
Ajusta o arquivo de logs (hist\('orico) para
.IR arquivo ,
ou, sen\(~ao, o diret\('orio para gera\(,c\(~ao do hist\('orico em
.IR dir .
Por favor note que um diret\('orio e identificado pelo
.I /
no final.
.TP
.BI sound \ on|beep|off|event
Especifica o que ocorre se um beep est\('a para ser gerado.
.B on
ou
.B beep
ir\(~ao simplesmente gerar um beep,
.B off
n\(~ao far\('a nada, enquanto
.B event
ir\('a chamar o script para eventos.
.TP
.BI event \ <script>
Ajusta o script a ser executado em eventos para
.IR script .
Ele \('e chamado com os seguintes argumentos:
.br
1. O tipo do IM, atualmente somente
.BR icq .
.br
2. O UIN do contato ao qual o evento relaciona-se, ou 0.
.br
3. O nick do contato ao qual o evento relaciona-se, ou um texto vazio.
.br
4. O texto
.BR global .
.br
5. O tipo deste evento, que pode ser
.BR msg ,
.BR on ,
.BR off ,
.BR beep
ou
.BR status ,
onde
.BR on \ e \ off
s\(~ao para contatos conectando e desconectando-se. Esta lista n\(~ao deve ser
exaustiva
.br
6. Para mensagens, o tipo da mensagem, para contatos desconectando, o status
anterior, e para contatos conectando ou mudan\(,cas de status, o novo status,
de outro modo 0.
.br
7. O texto da mensagem.
.br
8. O agente do usu\('ario do contato.
.br
Note que, por raz\(~oes de seguran\(,ca, aspas simples podem ser
substitu\('idas por aspas duplas, e o texto da mensagem pode ser truncado.
.TP
.BI auto \ <estado>\ <texto>
Muda a resposta autom\('atica para quando o usu\('ario se encontra no estado
.I estado
(away/distante, not available/n\(~ao-dispon\('ivel, etc) para
.IR texto .
Esta op\(,c\(~ao pode ser repetida para todos os outros estados, como
.BR away ,
.BR na ,
.BR dnd ,
.BR occ ,
.BR inv ,
e
.B ffc
para
.IR status .
.SH STRINGS
A se\(,c\(~ao
.B Strings
cont\('em comandos renomeados.
.TP
.BI alter \ <antigo>\ <novo>
Renomeia o comando
.I antigo
para
.IR novo .
Observe que o comando antigo ainda funciona. Voc\(^e poder\('a usar as 2 formas
do comando, a menos que entre em conflito com algum outro nome
.IR novo .
Para saber quais s\(~ao os comandos poss\('iveis, consulte a p\('agina de manual
.BR climmcmds (7).
Esta op\(,c\(~ao pode ser usada quantas vezes quiser.
.br
Nota: esta op\(,c\(~ao est\('a obsoleta, use
.I alias
ao inv\('es.
.TP
.BI alias \ <alias>\ <expans\(~ao>
Define um alias chamado
.I alias
que \('e substitu\('ido pela
.IR expans\(~ao .
Se o texto %s estiver presente na
.IR expans\(~ao ,
ela ser\('a trocada pelos argumentos fornecidos quando o alias for invocado, de
outro modo eles ser\(~ao concatenados.
Novo para 0.4.10.
.SH GROUP
A se\(,c\(~ao
.B Group
cria um grupo de contatos e pode ser repetida como requerido. Note que para
format 2, ele \('e salvo no arquivo BASE/status file, n\(~ao em
BASE/climmrc.
Pode ter os seguintes comandos:
.TP
.BI server \ <tipo>\ <uin>
Ajusta o servidor de conex\(~ao deste grupo de contatos pertencendo a um dos
tipos
.IR tipo ,
que atualmente pode ser
.B icqv8
para servidores de conex\(~oes ICQ vers\(~ao 8 ou
.B icqv5
para servidores de conex\(~oes ICQ vers\(~ao 5,
e para UIN
.IR uin .
Se este comando for omitido, o primeiro servidor de conex\(~ao ativo \('e
assumido.
.TP
.BI label \ <r\('otulo>
Ajusta o r\('otulo deste grupo de contatos para
.IR r\('otulo .
Se este for
.BI contatos- <tipo> - <uin>,
ent\(~ao ele \('e a lista de contatos para este servidor de conex\(~oes.
Note que para format 2 do arquivo BASE/status file, isto \('e obsoleto, pois os
contatos distribu\('idos para conex\(~oes com o servidor de acordo com a
declara\(,c\(~ao server em sua se\(,c\(~ao Contacts.
.TP
.BI id \ <id>
Ajusta o id deste grupo de contatos para
.IR id .
.B 0
significa nenhum id definido. Este ser\('a ajustado quando baixando ou
atualizando uma lista de contatos.
.TP
.BI options \ <options>...
Define op\(,c\(~oes para este grupo de contatos. Veja o comando
.I opt
para detalhes.
.TP
.BI entry \ <id>\ <uin>
Adiciona contato com UIN
.I uin
como id
.I id
para este grupo de contatos. Note que
.I id 
\('e obsoleto no climm 0.5 e sempre ajustado para 0. O id \('e ajustado na
se\(,c\(~ao
.I Contacts
ao inv\('es.
.SH CONTACTS (formato obsoleto)
A se\(,c\(~ao
.B Contacts
cont\('em a lista de contatos (global) do climm. Ela est\('a obsoleta neste
formato.
.TP
.I [*][~][^] uin apelido
Faz com que um usu\('ario com UIN (Universal Internet Number)
.I uin
seja conhecido por
.IR apelido .
Se a op\(,c\(~ao
.B *
\('e usada, o usu\('ario tem a capacidade de ver seu "status" mesmo quando
voc\(^e esta invis\('ivel. Se a op\(,c\(~ao
.B ~
\('e usada, o usu\('ario vai sempre lhe enxergar como offline. Se a op\(,c\(~ao
.B ^
\('e passada, coloca o usu\('ario na lista de ignorados.
Se um UIN aparece mais de uma vez, s\(~ao tratados como "alias" ou apelidos
para o UIN.
.SH CONTACTS
A se\(,c\(~ao
.B Contacts
cont\('em uma lista de contatos para uma conex\(~ao com o servidor. Ela \('e
repetida para cada conex\(~ao com o servidor.
Note que ela \('e salva no arquivo BASE/status, n\(~ao em BASE/climmrc.
Ela deve ter os seguintes comandos:
.TP
.BI server \ <tipo>\ <uin>
Define a conex\(~ao com o servidor a qual esta lista de contatos \('e
destinada, com a mesma sintaxe como na se\(,c\(~ao
.IR Group .
.TP
.BI entry \ <id>\ <uin>\ <nick>...
Adiciona um usu\('ario com o UIN
.I uin
e id
.I id
para esta lista de contatos, com o nick e muitos apelidos arbitr\('arios
.IR nick .
.TP
.BI options \ <op\(,c\(~oes>...
Define op\(,c\(~oes para o contato anterior. Veja o comando
.I opt
para detalhes.
.SH VEJA TAMB\('EM
.BR climm (1),
.BR climmcmds (7)
.SH AUTOR
Esta p\('agina de manual foi escrita por James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca> .
Foi reescrita para se adaptar \(`as novas op\(,c\(~oes de configura\(,c\(~ao do
climm por R\(:udiger Kuhlmann
.IR <climm@ruediger-kuhlmann.de> .
Traduzida por Deives Michellis
.IR <dmichellis@yahoo.com> ,
e atualizada por Leonardo Rosa
.IR <leorosa@feq.unicamp.br> .
