.\" $Id$ -*- nroff -*-
.\"  EN: micqrc.5,v 1.16 2002/08/26 16:45:24 kuhlmann Exp $
.\"This is the man page for ~/.micqrc."
.TH MICQRC 5 mICQ PT_BR
.SH NOME
.B ~/.micq/micqrc
\- O arquivo de configura\(,c\(~ao para o mICQ
.SH NOTE - THIS FILE HAS NOT YET BEEN UPDATED FOR mICQ 0.4.10.
.SH DESCRI\(,C\(~AO
Esta pagina de manual (man-page) descreve o arquivo de configura\(,c\(~ao para o mICQ. Consiste em diversas se\(,c\(~oes que s\(~ao iniciadas por
.IR [se\(,c\(~ao] ,
onde
.I se\(,c\(~ao
\('e o nome da se\(,c\(~ao
.SH CONNECTION
A se\(,c\(~ao
.B Connection
(conex\(~ao) descreve uma conex\(~ao na rede ICQ. Normalmente existem 2 lados da conex\(~ao, que s\(~ao co-relacionados: uma conex\(~ao para o servidor ICQ e uma conex\(~ao para atender a requisi\(,c\(~oes "peer-to-peer" ou pessoa-a-pessoa.
.TP
.BI type \ tipo\ [auto]
Ajusta o tipo da conex\(~ao para 
.IR tipo ,
o qual pode ser
.B server
para uma conex\(~ao com o servidor ICQ, ou
.B peer
para uma conex\(~ao do tipo "peer-to-peer" ou pessoa-a-pessoa. Se
.I auto
e usado como par\(^ametro, cria-se esta conex\(~ao direto na inicializa\(,c\(~ao. Voc\(^e possivelmente quer isso, a menos que possua diversos UINs, sendo ent\(~ao necess\('ario acertar isso na conex\(~ao correspondente como o UIN que se esta usando no momento.
.TP
.BI version \ ver
Ajusta a vers\(~ao do protocolo usado na conex\(~ao para 
.IR ver .
No entanto, preste aten\(,c\(~ao que para conex\(~oes para servidor, as vers\(~oes 
.BR 5 ,
.B 7
e
.B 8
s\(~ao permitidas, e para "peer-to-peer" ou pessoa-a-pessoa
.BR 6 ,
.B 7
e
.BR 8 .
.TP
.BI server \ servidor
Ajusta o servidor ICQ padr\(~ao para 
.IR servidor .
O padr\(~ao \('e 
.IR login.icq.com .
N\(~ao valido para conex\(~oes "peer-to-peer".
.TP
.BI port \ porta
Muda a porta de conex\(~ao no servidor para 
.IR porta ,
ou muda a porta padr\(~ao pra "escutar" requisi\(,c\(~oes "peer-to-peer" para a porta
.IR porta .
.TP
.BI uin \ UIN
Muda o UIN (n\('umero ICQ) para fazer o login na rede ICQ para 
.IR UIN .
N\(~ao valido para conex\(~oes "peer-to-peer".
.TP
.BI password \ [senha]
Ajusta a senha para conex\(~ao na rede ICQ para
.IR password .
N\(~ao v\('alido para conex\(~oes "peer-to-peer". Se omitido, voc\(^e devera digitar a senha na inicializa\(,c\(~ao do mICQ.
Obs: Usu\('arios BeOS precisam preencher este campo.
.TP
.BI status \ nr
Ajusta o "status" padr\(~ao ao efetuar login para
.IR nr .
Onde "status" pode ser:
.RS
.TP
0
online
.TP
1
away (distante)
.TP
5
not available (n\(~ao dispon\('ivel)
.TP
17
occupied (ocupado)
.TP
19
do not disturb (n\(~ao perturbe)
.TP
32
free for chat (livre pra bate-papo)
.TP
256
invisible (invis\('ivel)
.RE

.RS
Para conex\(~oes "peer-to-peer", este par\(^ametro \('e usado para a configura\(,c\(~ao da conex\(~ao direta:
.TP
1
Atr\('as de um firewall e n\(~ao pode receber conex\(~oes diretas. Nem mesmo tentativas.
.TP
2
Atr\('as de um firewall, mas usando SOCKS e podendo receber conex\(~oes.
.TP
4
Sem qualquer firewall. Este \('e o padr\(~ao.
.RE
.SH GERAL
A se\(,c\(~ao
.B General
(geral) inclui as op\(,c\(~oes para SOCKS 5 (que poder\(~ao no futuro ganhar sua pr\('opria se\(,c\(~ao), op\(,c\(~oes gerais, e algumas strings espec\('ificas.
.TP
.BI s5_use \ n\('umero
Use
.I n\('umero
em 0 para desabilitar e 1 para habilitar.
.TP
.BI s5_host \ endereco
Conecte ao servidor de proxy SOCKS 5 no endere\(,co
.IR endere\(,co .
.TP
.BI s5_port \ porta
Conecte ao servidor de proxy SOCKS 5 na porta
.IR porta .
.TP
.BI s5_auth \ n\('umero
Use
.I n\('umero
0 para ignorar autentica\(,c\(~ao e 1 para efetuar a autentica\(,c\(~ao.
.TP
.BI s5_name \ nome
Efetuar a identifica\(,c\(~ao como o usu\('ario 
.I nome
no servidor proxy SOCKS 5.
.TP
.BI s5_pass \ senha
Efetuar a autentica\(,c\(~ao com a senha 
.I senha
no servidor proxy SOCKS 5.
.PP
As op\(,c\(~oes:
.TP
.BI verbose \ n\('ivel
Muda o n\('ivel de informa\(,c\(~ao verbal para
.IR n\('ivel .
.TP
.BI auto_away \ tempo
Muda o tempo de inatividade para auto-away (distante) para 
.I tempo
segundos. Mude para
.I 0
para desabilitar o auto-away.
.TP
.BI Screen_width \ largura
Muda a largura padr\(~ao da tela para
.IR largura .
Se configurado para
.IR 0 , \ 80
ser\('a usado como medida padr\(~ao. Este par\(^ametro dificilmente precisa ser especificado, pois e poss\('ivel defini-lo em tempo de execu\(,c\(~ao (run-time).
.TP
.BI set \ delbs\ on|off
Se configurado para
.BR on ,
faz com que a tecla "delete" funcione como um "back space". Quando configurado para
.BR off ,
deixa a tecla "delete" funcionar normalmente.
.TP
.BI set \ russian\ on|off
Habilita ou desabilita a convers\(~ao de caracteres russos entre koi8-r/u e cp1251.
.TP
.BI set \ japanese\ on|off
Habilita ou desabilita a convers\(~ao de caracteres Japoneses entre Shift-JIS e EUC.
.TP
.BI set \ funny\ on|off
Habilita ou desabilita as mensagens "engra\(,cadas" ("funny").
.TP
.BI set \ color\ on|off
Habilita ou desabilita o uso de cores.
.TP
.BI set \ hermit\ on|off
Se "hermit" for configurado para 
.BR on ,
descarta todas as mensagens de qualquer pessoa que n\(~ao esteja na lista de contatos.
.TP
.BI set \ log\ on|off
Habilita ou desabilita o "logging" (hist\('orico).
.TP
.BI set \ logonoff\ on|off
Quando gerando hist\('orico de mensagens, desabilita ou habilita a gera\(,c\(~ao de hist\('orico de quando os usu\('arios ficam "online" e quando saem.
.TP
.BI set \ auto\ on|off
Desabilita ou habilita as respostas autom\('aticas.
.TP
.BI set \ uinprompt\ on|off
Desabilita ou habilita o uso no prompt do ultimo nick a lhe mandar uma mensagem.
.TP
.BI set \ linebreak\ tipo
Configura o tipo da quebra de linha (line break) em mensagens recebidas para
.IR tipo ,
o qual pode ser
.B simple
para fazer da maneira convencional,
.B break
para se ter uma quebra de linha antes de cada mensagem,
.B indent
para haver uma quebra de linha e a indenta\(,c\(~ao (par\('agrafo), e
.B smart
para se ter uma quebra de linha apenas se a mensagem n\(~ao couber na linha atual.
.TP
.BI set \ tabs\ simple|cycle|cycleall
Seleciona o estilo de auto-completar da tecla "tab". Vers\(~oes antigas do mICQ s\('o conheciam o
.BR simple ,
o qual s\('o funciona com o comando 
.B msg
e completa o comando e tenta o auto-completar usando a lista de contatos. Qualquer texto digitado depois do "nick name" seria perdido quando pressionasse a tecla "tab".
.B cycle
faz o auto-completar com os contatos online na sua lista de contatos. Mant\('em intacto qualquer outro texto digitado no comando 
, no entanto, ele n\(~ao coloca o 
.B msg
antes do "nick name".
.B cycleall
e muito similar ao 
.BR cycle ,
s\('o que pesquisa em toda a lista de contatos, n\(~ao apenas nos contatos online.
.TP
.BI chat \ nr
Seleciona o random chat group para
.IR nr .
Use
.B -1
para desabilitar e
.B 49
para mICQ (o qual \('e padr\(~ao).

.PP
Por \('ultimo, algumas "strings" que podem ser definidas:
.TP
.BI color\ scheme \ num
Muda o esquema de cor para o n\('umero
.IR num .
.TP
.BI color \ uso\ cor
Seleciona a 
.IR cor
para o
.IR uso .
pode ser do tipo 
.BR none ,
.BR server ,
.BR client ,
.BR message ,
.BR contact ,
.BR sent ,
.BR ack ,
.BR error ,
.BR debug
ou
.BR incoming ,
enquanto que 
.IR cor
pode ser do tipo
.BR black ,
.BR red ,
.BR green ,
.BR yellow ,
.BR blue ,
.BR magenta ,
.BR cyan ,
.BR white ,
.BR none ,
ou
.BR bold
ou uma combina\(,c\(~ao das anteriores
.RB ( bold ,
no entanto, precisa ser o ultimo par\(^ametro na defini\(,c\(~ao),
ou qualquer "string" que fa\(,ca o terminal do usu\('ario usar a cor desejada.
.TP
.BI logplace \ arquivo|dir
Ajusta o arquivo de logs (hist\('orico) para
.IR arquivo ,
ou, sen\(~ao, o diret\('orio para gera\(,c\(~ao do hist\('orico em
.IR dir .
Por favor note que um diret\('orio e identificado pelo
.IR / 
no final.
.TP
.BI sound \ on|off|comando
Desabilita ou habilita o esquema de sons. Se o par\(^ametro n\(~ao for nem
.B on
ou
.BR off ,
significa que \('e o nome de algum programa externo ao mICQ que devera ser executado ao inv\('es do beep.
.TP
.BI soundonline \ on|off|comando
Id\(^entico ao anterior, s\('o que s\(~ao os sons para quando os usu\('arios ficam online.
.TP
.BI soundoffline \ on|off|comando
Id\(^entico ao anterior, s\('o que s\(~ao os sons para quando os usu\('arios ficam offline.
.TP
.BI receivescript \ comando
Ajusta o comando que devera ser executado para tratar novas mensagens. Deixe em branco para que nada seja feito.
.TP
.BI auto \ estado\ texto
Muda a resposta autom\('atica para quando o usu\('ario se encontra no estado  
.I estado
(away/distante, not available/n\(~ao-dispon\('ivel, etc) para o texto
.IR texto .
Esta op\(,c\(~ao pode ser repetida para todos os outros estados, como
.BR away ,
.BR na ,
.BR dnd ,
.BR occ ,
.BR inv ,
e
.B ffc
para
.IR status .
.SH STRINGS
A se\(,c\(~ao "Strings"
.B Strings
define comandos renomeados.
.TP
.BI alter \ antigo\ novo
Renomeia o comando 
.I antigo
para
.IR novo .
Observe que o comando antigo ainda funciona. V\(^oce poder\('a usar as 2 formas do comando, a menos que entre em conflito com algum outro comando
.I novo .
Para saber quais s\(~ao os comandos poss\('iveis, consulte a pagina de manual 
.BR micq (7).
Esta op\(,c\(~ao pode ser usada quantas vezes quiser.

.SH CONTACTS
A se\(,c\(~ao Contacts 
.B Contacts
define a lista de contatos do mICQ.
.TP
.I [*][~][^] uin apelido
Faz com que um usu\('ario com UIN (Universal Internet Number)
.I uin
seja conhecido pelo  
.IR apelido 
no mICQ.
Se a op\(,c\(~ao
.B *
e usada, o usu\('ario tem a capacidade de ver seu "status" mesmo quando voc\(^e esta invis\('ivel. Se a op\(,c\(~ao
.B ~
e usada, o usu\('ario vai sempre lhe enxergar como offline. Se a opcao
.B ^
e passada, coloca o usu\('ario na lista de ignorados.
Se um UIN aparece mais de uma vez, s\(~ao tratados como "alias" ou apelidos para o UIN.

Observa\(,c\(~ao: a se\(,c\(~ao "Contacts" precisa ser a ultima parte do arquivo de configura\(,c\(~ao.
.SH VEJA TAMB\('EM
.BR micq (1),
.BR micq (7)
.SH AUTOR
Esta pagina de manual foi escrita por James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca> .
Foi reescrita para se adaptar as novas op\(,c\(~oes de configura\(,c\(~ao do mICQ por R\(:udiger Kuhlmann
.IR <micq@ruediger-kuhlmann.de> .
Traduzida por Deives Michellis 
.IR <dmichellis@yahoo.com>.
