.\" $Id$ -*- nroff -*-
.\"  EN: micqrc.5,v 1.16 2002/08/26 16:45:24 kuhlmann Exp $
.\"This is the man page for ~/.micqrc."
.TH MICQRC 5 mICQ PT_BR
.SH NOME
.B ~/.micq/micqrc
\- O arquivo de configuração para o mICQ
.SH DESCRIÇÃO
Esta pagina de manual (man-page) descreve o arquivo de configuração para o mICQ. Consiste em diversas seções que são iniciadas por
.IR [seção] ,
onde
.I seção
é o nome da seção
.SH CONNECTION
A seção
.B Connection
(conexão) descreve uma conexão na rede ICQ. Normalmente existem 2 lados da conexão, que são co-relacionados: uma conexão para o servidor ICQ e uma conexão para atender a requisições "peer-to-peer" ou pessoa-a-pessoa.
.TP
.BI type \ tipo\ [auto]
Ajusta o tipo da conexão para 
.IR tipo ,
o qual pode ser
.B server
para uma conexão com o servidor ICQ, ou
.B peer
para uma conexão do tipo "peer-to-peer" ou pessoa-a-pessoa. Se
.I auto
e usado como parâmetro, cria-se esta conexão direto na inicialização. Você possivelmente quer isso, a menos que possua diversos UINs, sendo então necessário acertar isso na conexão correspondente como o UIN que se esta usando no momento.
.TP
.BI version \ ver
Ajusta a versão do protocolo usado na conexão para 
.IR ver .
No entanto, preste atenção que para conexões para servidor, as versões 
.BR 5 ,
.B 7
e
.B 8
são permitidas, e para "peer-to-peer" ou pessoa-a-pessoa
.BR 6 ,
.B 7
e
.BR 8 .
.TP
.BI server \ servidor
Ajusta o servidor ICQ padrão para 
.IR servidor .
O padrão é 
.IR login.icq.com .
Não valido para conexões "peer-to-peer".
.TP
.BI port \ porta
Muda a porta de conexão no servidor para 
.IR porta ,
ou muda a porta padrão pra "escutar" requisições "peer-to-peer" para a porta
.IR porta .
.TP
.BI uin \ UIN
Muda o UIN (número ICQ) para fazer o login na rede ICQ para 
.IR UIN .
Não valido para conexões "peer-to-peer".
.TP
.BI password \ [senha]
Ajusta a senha para conexão na rede ICQ para
.IR password .
Não válido para conexões "peer-to-peer". Se omitido, você devera digitar a senha na inicialização do mICQ.
Obs: Usuários BeOS precisam preencher este campo.
.TP
.BI status \ nr
Ajusta o "status" padrão ao efetuar login para
.IR nr .
Onde "status" pode ser:
.RS
.TP
0
online
.TP
1
away (distante)
.TP
5
not available (não disponível)
.TP
17
occupied (ocupado)
.TP
19
do not disturb (não perturbe)
.TP
32
free for chat (livre pra bate-papo)
.TP
256
invisible (invisível)
.RE

.RS
Para conexões "peer-to-peer", este parâmetro é usado para a configuração da conexão direta:
.TP
1
Atrás de um firewall e não pode receber conexões diretas. Nem mesmo tentativas.
.TP
2
Atrás de um firewall, mas usando SOCKS e podendo receber conexões.
.TP
4
Sem qualquer firewall. Este é o padrão.
.RE
.SH GERAL
A seção
.B General
(geral) inclui as opções para SOCKS 5 (que poderão no futuro ganhar sua própria seção), opções gerais, e algumas strings específicas.
.TP
.BI s5_use \ número
Use
.I número
em 0 para desabilitar e 1 para habilitar.
.TP
.BI s5_host \ endereco
Conecte ao servidor de proxy SOCKS 5 no endereço
.IR endereço .
.TP
.BI s5_port \ porta
Conecte ao servidor de proxy SOCKS 5 na porta
.IR porta .
.TP
.BI s5_auth \ número
Use
.I número
0 para ignorar autenticação e 1 para efetuar a autenticação.
.TP
.BI s5_name \ nome
Efetuar a identificação como o usuário 
.I nome
no servidor proxy SOCKS 5.
.TP
.BI s5_pass \ senha
Efetuar a autenticação com a senha 
.I senha
no servidor proxy SOCKS 5.
.PP
As opções:
.TP
.BI verbose \ nível
Muda o nível de informação verbal para
.IR nível .
.TP
.BI auto_away \ tempo
Muda o tempo de inatividade para auto-away (distante) para 
.I tempo
segundos. Mude para
.I 0
para desabilitar o auto-away.
.TP
.BI Screen_width \ largura
Muda a largura padrão da tela para
.IR largura .
Se configurado para
.IR 0 , \ 80
será usado como medida padrão. Este parâmetro dificilmente precisa ser especificado, pois e possível defini-lo em tempo de execução (run-time).
.TP
.BI set \ delbs\ on|off
Se configurado para
.BR on ,
faz com que a tecla "delete" funcione como um "back space". Quando configurado para
.BR off ,
deixa a tecla "delete" funcionar normalmente.
.TP
.BI set \ russian\ on|off
Habilita ou desabilita a conversão de caracteres russos entre koi8-r/u e cp1251.
.TP
.BI set \ japanese\ on|off
Habilita ou desabilita a conversão de caracteres Japoneses entre Shift-JIS e EUC.
.TP
.BI set \ funny\ on|off
Habilita ou desabilita as mensagens "engraçadas" ("funny").
.TP
.BI set \ color\ on|off
Habilita ou desabilita o uso de cores.
.TP
.BI set \ hermit\ on|off
Se "hermit" for configurado para 
.BR on ,
descarta todas as mensagens de qualquer pessoa que não esteja na lista de contatos.
.TP
.BI set \ log\ on|off
Habilita ou desabilita o "logging" (histórico).
.TP
.BI set \ logonoff\ on|off
Quando gerando histórico de mensagens, desabilita ou habilita a geração de histórico de quando os usuários ficam "online" e quando saem.
.TP
.BI set \ auto\ on|off
Desabilita ou habilita as respostas automáticas.
.TP
.BI set \ uinprompt\ on|off
Desabilita ou habilita o uso no prompt do ultimo nick a lhe mandar uma mensagem.
.TP
.BI set \ linebreak\ tipo
Configura o tipo da quebra de linha (line break) em mensagens recebidas para
.IR tipo ,
o qual pode ser
.B simple
para fazer da maneira convencional,
.B break
para se ter uma quebra de linha antes de cada mensagem,
.B indent
para haver uma quebra de linha e a indentação (parágrafo), e
.B smart
para se ter uma quebra de linha apenas se a mensagem não couber na linha atual.
.TP
.BI set \ tabs\ simple|cycle|cycleall
Seleciona o estilo de auto-completar da tecla "tab". Versões antigas do mICQ só conheciam o
.BR simple ,
o qual só funciona com o comando 
.B msg
e completa o comando e tenta o auto-completar usando a lista de contatos. Qualquer texto digitado depois do "nick name" seria perdido quando pressionasse a tecla "tab".
.B cycle
faz o auto-completar com os contatos online na sua lista de contatos. Mantém intacto qualquer outro texto digitado no comando 
, no entanto, ele não coloca o 
.B msg
antes do "nick name".
.B cycleall
e muito similar ao 
.BR cycle ,
só que pesquisa em toda a lista de contatos, não apenas nos contatos online.
.TP
.BI chat \ nr
Seleciona o random chat group para
.IR nr .
Use
.B -1
para desabilitar e
.B 49
para mICQ (o qual é padrão).

.PP
Por último, algumas "strings" que podem ser definidas:
.TP
.BI color\ scheme \ num
Muda o esquema de cor para o número
.IR num .
.TP
.BI color \ uso\ cor
Seleciona a 
.IR cor
para o
.IR uso .
pode ser do tipo 
.BR none ,
.BR server ,
.BR client ,
.BR message ,
.BR contact ,
.BR sent ,
.BR ack ,
.BR error ,
.BR debug
ou
.BR incoming ,
enquanto que 
.IR cor
pode ser do tipo
.BR black ,
.BR red ,
.BR green ,
.BR yellow ,
.BR blue ,
.BR magenta ,
.BR cyan ,
.BR white ,
.BR none ,
ou
.BR bold
ou uma combinação das anteriores
.RB ( bold ,
no entanto, precisa ser o ultimo parâmetro na definição),
ou qualquer "string" que faça o terminal do usuário usar a cor desejada.
.TP
.BI logplace \ arquivo|dir
Ajusta o arquivo de logs (histórico) para
.IR arquivo ,
ou, senão, o diretório para geração do histórico em
.IR dir .
Por favor note que um diretório e identificado pelo
.IR / 
no final.
.TP
.BI sound \ on|off|comando
Desabilita ou habilita o esquema de sons. Se o parâmetro não for nem
.B on
ou
.BR off ,
significa que é o nome de algum programa externo ao mICQ que devera ser executado ao invés do beep.
.TP
.BI soundonline \ on|off|comando
Idêntico ao anterior, só que são os sons para quando os usuários ficam online.
.TP
.BI soundoffline \ on|off|comando
Idêntico ao anterior, só que são os sons para quando os usuários ficam offline.
.TP
.BI receivescript \ comando
Ajusta o comando que devera ser executado para tratar novas mensagens. Deixe em branco para que nada seja feito.
.TP
.BI auto \ estado\ texto
Muda a resposta automática para quando o usuário se encontra no estado  
.I estado
(away/distante, not available/não-disponível, etc) para o texto
.IR texto .
Esta opção pode ser repetida para todos os outros estados, como
.BR away ,
.BR na ,
.BR dnd ,
.BR occ ,
.BR inv ,
e
.B ffc
para
.IR status .
.SH STRINGS
A seção "Strings"
.B Strings
define comandos renomeados.
.TP
.BI alter \ antigo\ novo
Renomeia o comando 
.I antigo
para
.IR novo .
Observe que o comando antigo ainda funciona. Vôce poderá usar as 2 formas do comando, a menos que entre em conflito com algum outro comando
.I novo .
Para saber quais são os comandos possíveis, consulte a pagina de manual 
.BR micq (7).
Esta opção pode ser usada quantas vezes quiser.

.SH CONTACTS
A seção Contacts 
.B Contacts
define a lista de contatos do mICQ.
.TP
.I [*][~][^] uin apelido
Faz com que um usuário com UIN (Universal Internet Number)
.I uin
seja conhecido pelo  
.IR apelido 
no mICQ.
Se a opção
.B *
e usada, o usuário tem a capacidade de ver seu "status" mesmo quando você esta invisível. Se a opção
.B ~
e usada, o usuário vai sempre lhe enxergar como offline. Se a opcao
.B ^
e passada, coloca o usuário na lista de ignorados.
Se um UIN aparece mais de uma vez, são tratados como "alias" ou apelidos para o UIN.

Observação: a seção "Contacts" precisa ser a ultima parte do arquivo de configuração.
.SH VEJA TAMBÉM
.BR micq (1),
.BR micq (7)
.SH AUTOR
Esta pagina de manual foi escrita por James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca> .
Foi reescrita para se adaptar as novas opções de configuração do mICQ por Rüdiger Kuhlmann
.IR <micq@ruediger-kuhlmann.de> .
Traduzida por Deives Michellis 
.IR <dmichellis@yahoo.com>.
