.\" $Id$  -*- nroff -*-
.\"  EN: micq.1,v 1.12 2002/08/21 08:50:56
.\"      ^^ <version of English man page this is in sync with>
.TH MICQ 1 mICQ PT_BR
.SH NOME
.B mICQ
\- um Cliente ICQ leve em modo texto
.SH SINOPSE
.B micq
.I [-v[nível]]
.I [-f arquivo]
.SH DESCRIÇÃO
.B mICQ
é um cliente ICQ em modo texto que possui muitos dos recursos providos pelos
clientes de ICQ da Mirabillis. mICQ permite que se mude a senha do usuário,
criem novas contas, atualize as informações pessoais, procure por outros usuários, etc.
.SH OPÇÕES
.TP
.BI -v [nível]
Inicia ou ajusta o nível de informação verbal para
.IR nível .
.TP
.BI -f \ arquivo
Use
.I arquivo
como um arquivo rc.
.TP
.BI -l \ arquivo|dir
Use
.I arquivo
como um arquivo de log, ou use
.I dir
como um diretório para criar os logs por usuário individual.
.TP
.BI -?,\ -h
Mostra a ajuda/modo de usar.


.SH RECURSOS
.B mICQ
é muito portável e funciona em Linux, DOS, OS/2, Win32, BeOS, AmigaOS, GNU HURD e
quaisquer outros sistemas Unix modernos.
.B mICQ versão 0.4.9.2
sabidamente funciona em Linux, AIX, HPUX, Tru64, AmigaOS, parcialmente BeOS
e outros sabores de Unix.
No entanto, os outros sabores de Unix podem ou não funcionar e qualquer pessoa
será bem-vinda para testar e nos avisar.
.SH HISTÓRICO
.TP
16 de Agosto de 1998
Matthew D. Smith publica o primeiro micq para o mundo. 
Seguido por 12 "releases" ate 25 de Setembro de 1998.
.TP
05 de Janeiro de 2001
Matthew D. Smith morre em um acidente de carro.
Os usuários continuam de onde Matthew parou, passam o mICQ para a licença BSD
e reiniciam o desenvolvimento do
.BR mICQ .
.TP
10 de Junho de 2002
A versão 0.4.9 e publicada sobre a licença GPL, finalmente implementando a nova
versão 8 do protocolo ICQ, por Rüdiger Kuhlmann.
.SH MAILING-LIST - LISTAS DE DISCUSSÃO
A lista de discussão oficial do mICQ e
.IR micq-list@micq.org .
Informação sobre subscrição e arquivos esta disponível no endereço 
.IR http://www.micq.org/pipermail/micq-list/ .
.SH DOWNLOAD
Via HTTP no site
.IR http://www.micq.org/download .
.br
Para obter a mais nova versão via CVS, acesse:
.br

cvs -d:pserver:anonymous@micq.org:/usr/local/cvsroot co micq
.br
.SH VEJA TAMBÉM
.BR micqrc (5),
.BR micq (7)
.SH ARQUIVOS
.TP
.I ~/.micqrc
Antigo arquivo de configuração do mICQ (obsoleto).
.TP
.I ~/.micq/micqrc
Arquivo de configuração do mICQ.
.TP
.I PREFIXO/share/micq/*.i18n
Arquivos de Internacionalização contendo traduções das mensagens e informações do mICQ.
.TP
.I ~/.micq/i18n/*.i18n
Um arquivo de Internacionalização local sobrepõe os arquivos descritos acima.
.TP
.I ~/.micq/history/
Localização padrão do diretório no qual os logs são criados.

.SH BUGS - PROBLEMAS
Envie relatórios de Bugs/Problemas ou comentários para Rüdiger Kuhlmann
.I <micq@ruediger-kuhlmann.de>
(em alemão ou inglês).
.SH AUTHOR
Esta man-page foi derivada por James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
da pagina original mínima escrita por Jordi Mallach
.I <jordi@sindominio.net>
para o sistema Debian GNU/Linux.
Traduzido por Deives Michellis
.I <dmichellis@yahoo.com>

