.\"     $Id$ -*- nroff -*-
.\" EN: $Id$
.TH MICQ 7 mICQ PT_BR
.SH NOME
mICQ - comandos interativos
.SH DESCRI\(,C\(~AO
Esta p\('agina de manual descreve os comandos que podem ser usados no micq.
Esta p\('agina tem a mesma informa\(,c\(~ao da ajuda online, por\('em mais
precisa e extensa.
.SH COMANDOS PARA O CLIENTE MICQ
.TP
.BI verbose \ [n\('ivel]
Ajusta o n\('ivel de informa\(,c\(~ao verbal para
.IR n\('ivel ,
ou mostra o n\('ivel atual. O n\('ivel de informa\(,c\(~ao verbal \('e um
conjunto de "flags":
.RS
.TP
.B 8
Mostra erros de protocolo.
.TP
.B 16
Mostra a cria\(,c\(~ao e remo\(,c\(~ao de pacotes.
.TP
.B 32
Mostra fila de eventos adicionados e removidos.
.TP
.B 64
Mostra conex\(~oes criadas e removidas.
.TP
.B 256
Mostra pacotes v6 e seus dados.
.TP
.B 4096
Mostra pacotes v7/v8.
.TP
.B 8192
Mostra o valor hexadecimal ("hexdump") de pacotes v7/v8.
.TP
.B 16284
Salva estes pacotes no disco.
.TP
.B 65536
Mostra pacotes peer-to-peer.
.TP
.B 131072
Mostra o hexdump de pacotes peer-to-peer.
.TP
.B 262144
Salva aqueles pacotes no disco.
.TP
.B 2097152
Mostra negocia\(,c\(~ao peer-to-peer.
.TP
.B 4194304
Mostra a configura\(,c\(~ao de conex\(~oes I/O (Entrada/Sa\('ida).
.PP
Entretanto, qualquer n\('ivel de informa\(,c\(~ao verbal diferente de zero
causar\('a a impress\(~ao de mais informa\(,c\(~ao, e quaisquer n\('iveis
maiores que 1 mais ainda.
.RE
.TP
.B clear
Limpa a tela.
.TP
.BI sound\ [on|off|event]
Altera o som para
.B on
(ligado) ou
.B off
(desligado), ou chama o script
.B event
para bipes. Sintaxe nova para 0.4.10.
.TP
.BI autoaway \ [tempo|on|off]
Ajusta o tempo de inatividade para
.IR tempo ,
ou troca o tempo de inatividade para
.I on
usando o \('ultimo ou o tempo padr\(~ao de inatividade, ou troca "auto away" para
.I off
salvando o tempo atual usado para auto away. Um tempo de 0 \('e equivalente a
.IR off .
Se nenhum argumento \('e dado, a condi\(,c\(~ao atual \('e mostrada.
.TP
.BI auto \ [on|off]
Muda mensagens de resposta autom\('atica on ou off. Se nem on nem off for dado
as mensagens de resposta autom\('atica s\(~ao mostradas.
.TP
.BI auto \ status\ mensagem
Altera a mensagem de resposta autom\('atica para o status
.I status
para
.IR mensagem .
.TP
.BI alias \ [apelido\ expans\(~ao]
Cria um novo apelido chamado
.I apelido
que \('e substitu\('ido pela
.IR expans\(~ao .
Se nenhum argumento for dado, todos os aliases atuais s\(~ao listados. Se o
texto %s estiver presente na
.IR expans\(~ao ,
ele ser\('a substitu\('ido pelos argumentos dados quando o alias for invocado,
de outra maneira eles ser\(~ao concatenados.
Novo para 0.4.10.
.TP
.BI unalias \ apelido
Remove o alias chamado
.IR apelido .
Novo para 0.4.10.
.TP
.BI alter \ comando\ novo
Faz com que o comando inicialmente ou previamente conhecido como
.I comando
seja agora conhecido como
.IR novo .
Este comando ficou obsoleto com o comando
.B alias
do mICQ 0.4.10.
.TP
.BI trans \ [lang|nr]\ ...
Muda para o idioma
.IR lang ,
dada pelo c\('odigo iso, ou imprime o texto de tradu\(,c\(~ao n\('umero
.IR nr .
Para selecionar o idioma padr\(~ao dada pelas vari\('aveis de ambiente
.BR LANG ,
.B LC_ALL
e
.BR LC_MESSAGES ,
use
.BR ! ,
.B auto
ou
.BR default .
Para selecionar nenhuma tradu\(,c\(~ao, use
.BR . ,
.B none
ou
.BR unload .
Para obter informa\(,c\(~oes de depura\(,c\(~ao, prefixe-o com
.BR debug .
Para obter informa\(,c\(~oes engra\(,cadas, p\('osfixe-o com
.BR @fun .
.sp
Os arquivos de ~/.micq/i18n/*.i18n tem preced\(^encia sobre os globais,
enquanto os "engra\(,cados" tem preced\(^encia sobre os padr\(~oes.
.sp
Atualmente voc\(^e pode especificar quantos argumentos desejar, p.ex. para
imprimir o texto n\('umero 117 em Alem\(~ao e ent\(~ao voltar para o idioma
padr\(~ao, use "trans de 117 default".
.TP
.B uptime
Mostra o tempo que o mICQ est\('a rodando, mais algumas estat\('isticas.
.TP
.BI set \ op\(,c\(~ao\ valor
Seleciona a op\(,c\(~ao
.I op\(,c\(~ao
tanto para
.I on
quanto
.IR off ,
ou um conjunto espec\('ifico de
.I op\(,c\(~oes
para
.IR valor (es).
.I op\(,c\(~ao
pode ser:
.RS
.TP
.BR hermit :
ignore todos os n\(~ao-contatos,
.TP
.BR delbs :
interprete caracteres delete como backspace,
.TP
.BR funny :
use mensagens engra\(,cadas,
.TP
.BR log :
fazer logging,
.TP
.BR logonoff :
criar log tamb\('em para mudan\(,cas de status,
.TP
.BR auto :
mandar respostas autom\('aticas quando voc\(^e estiver, p.ex., away,
.TP
.BR uinprompt :
ter o \('ultimo nick no prompt,
.TP
.BR autosave :
salvar automaticamente o micqrc,
.TP
.BR autofinger :
obter informa\(,c\(~oes automaticamente para novos UINs,
.TP
.BR linebreak :
selecionar o estilo para quebra-de-linha em mensagens para
.BR simple ,
para simplesmente imprimir a mensagem ap\('os o nick e continuar,
.BR break ,
para adicionar uma quebra de linha antes da impress\(~ao de cada mensagem
chegando,
.BR indent ,
para indentar todas as linhas de uma mensagem para o n\('ivel ap\('os o nick, ou
.BR smart ,
para adicionar uma quebra de linha apenas se a mensagem n\(~ao couber numa linha;
.TP
.BR tabs :
selecionar o estilo para tratar tab para
.BR simple ,
para tabular entre uma lista dos \('ultimos nicks aos quais foram enviados ou
recebidos,
.BR cycle ,
para circular entre todos os contatos online, completando automaticamente, ou
.BR cycleall ,
para circular entre todos (mesmo offline) os contatos, completando automaticamente;
.TP
.BR silent :
suprime alguma sa\('ida :
.BR off ,
.BR on ,
para suprimir mudan\(,cas de status ou
.BR complete ,
para suprimir mudan\(,cas de status, logins e logoffs.
.PP
Novas op\(,c\(~oes para 0.4.10.
.RE
.TP
.B save
Salva as sele\(,c\~oes atuais no arquivo de configura\(,c\(~ao, que \('e
.IR ~/.micq/micqrc ,
a menos que especificado outro.
Aten\(,c\(~ao, ele remover\('a quaisquer coment\('arios neste arquivo.
.TP
.B q[uit]
.TP
.B exit
Sair do mICQ.
Aliases quit e exit novos para 0.4.10.
.SH COMANDOS PARA O ENVIO DE MENSAGENS
Um argumento
.I <contacts>
denota uma lista separada por v\('irgula de contatos, isto \('e, de UINs e
nick names. Se ele for o \('ultimo argumento, os contatos podem tamb\('em serem
separados por espa\(,cos.
.TP
.BI msg \ <contatos>\ [mensagem]
Envia uma mensagem para todos os
.IR contatos .
Sem uma
.I mensagem
o modo de mensagem multi-linha \('e habilitado. Para enviar uma mensagem
multi-linha, coloque um ponto
.RB ( . )
sozinho em uma linha. Para cancelar a mensagem, coloque um sinal de cerquilha
.RB ( # )
sozinho em uma linha.
.br
Mensagens sendo enviadas e recebidas s\(~ao marcadas diferentemente dependendo
do transporte usado.
.B \(Fo\(Fo\(Fo
e
.B \(Fc\(Fc\(Fc
marcam mensagens enviadas atrav\('es de uma conex\(~ao direta; se uma mensagem
sendo enviada n\(~ao for reconhecida pelo ponto (peer) por algum tempo, ela
\('e impressa marcada com
.BR === .
.B \(Fo<<
e
.B >>\(Fc
marcam mensagens icq8 (tamb\('em chamadas tipo-2) messages; se uma mensagem
sendo emviada n\(~ao for reconhecida pelo ponto por algum tempo, ela \('e
impressa marcada com
.BR --= .
Finalmente,
.B <<<
e
.B >>>
marcam mensagens icq5, que podem ser tanto as mensagens chamadas tipo-1, tipo-4
ou offline. Estes tipos de mensagens n\(~ao s\(~ao reconhecidas.
.br
Uma mensagem \('e primeiro tentada ser enviada por uma conex\(~ao direta pr\('e-
existente; se nenhuma for estabelecida, uma \('e iniciada em segundo plano para
futuras mensagens. Se nenhuma conex\(~ao direta estiver aberta, ou se a mensagem
n\(~ao for reconhecida ap\('os algum tempo, a conex\(~ao ser\('a falha e o
pr\('oximo transporte tentado: enviar como mensagem tipo-2. Este passo ser\('a
ignorado se o ponto n\(~ao preencher as capacidades requeridas para sinalizar
sua habilidade em recebe-la. Se for ignorado, encerrado ap\('os algum tempo
ou retornar erro, p.ex. o ponto tornou-se offline neste per\('iodo, a mensagem
\('e enviada como uma mensagem comum tipo-4.
.br
Se o ponto sinalizar sua capacidade de aceita-las e suporte para elas n\(~ao
for desablitado na compila\(,c\(~ao, mensagens s\(~ao enviadas com a
codifica\(,c\(~ao UTF-8 e rotuladas apropriadamente. De outro modo, a mensagem
\('e enviada codificada com a codifica\(,c\(~ao configurada pelo ponto, ou, se
n\(~ao for especificado, a codifica\(,c\(~ao remota padr\(~ao assumda.
Mensagens tipo-1, tipo-4 e offline n\(~ao podem ser rotuladas com sua
codifica\(,c\(~ao, ent\(~ao o sucesso na transmiss\(~ao de caracteres de 8bit
depende da configura\(,c\(~ao correta.
.TP
.BI a \ [mensagem]
Envia uma mensagem para a \('ultima pessoa a qual voc\(^e enviou uma mensagem.
Veja
.B msg
para maiores detalhes.
.TP
.BI r \ [mensagem]
Responde para a \('ultima mensagem recebida. Veja
.B msg
para maiores detalhes.
.TP
.BI url \ <contatos>\ url\ mensagem
Envia uma
.I mensagem
lembrando de uma
.I url
para todos os
.IR contatos .
.TP
.BI sms \ [nick]\ [cell]\ mensagem
Envia uma mensagem SMS
.I mensagem
para o telefone celular n\('umero
.IR cell ,
que parece como +<c\('odigo do pa\('is><n\('umero>,
ou o n\('umero do telefone celular do
or to the cell phone number of
.IR nick ,
que estar\('a selecionado para
.IR cell
se n\(~ao for selecionado. Voc\(^e n\(~ao pode especificar
.IR cell
se
.IR nick
j\('a possui um n\('umero de telefone celular dado. N\('umeros de telefone
celular inv\('alidos ser\(~ao removidos dos meta dados do
.IR nick
.TP
.BI getauto \ [auto|away|na|dnd|occ|ffc]\ [contatos]
Chama as mensagens autom\('aticas de
.IR contatos
para o status dado, onde
.B away
\('e para away,
.B na
para n\(~ao dispon\('ivel,
.B dnd
para n\(~ao perturbe,
.B occ
para ocupado e
.B ffc
para livre para chat. Se
.B auto
ou nada for dado, a mensagem autom\('atica para os contatos
\('e ajustada para seu respectivo status. Contatos fora de quaisquer um destes
status ser\(~ao ignorados.
Novo para 0.4.10.
.TP
.BI auth \ [req|grant|deny|add]\ <contatos>
Libera ou nega todos os
.I contatos
a adicionar voc\(^e \(`as suas listas, pede a todos os
.I contatos
permitir voc\(^e a adiciona-los em sua lista de contatos, ou informa aos
.I contatos
que voc\(^e os adicionou em sua lista de contatos.
.TP
.BI resend \ <contatos>
Reenvia a \('ultima mensagem para mais
.IR contatos .
.TP
.BI last \ [<contatos>]
Mostra a \('ultima mensagem recebida de
.IR contatos ,
ou de qualquer um que j\('a tenha enviado uma mensagem.
.TP
.B tabs
Mostra uma lista de usu\('arios que voc\(^e pode tabular. Esta lista \('e usada
somente no estilo de tabula\(,c\~ao
.B simple
Veja a op\(,c\(~ao
.I tabs
do comando
.BR set .
.SH COMANDOS PARA ENCONTRAR E VER OUTROS USU\('ARIOS
.TP
.BI rand \ n\('umero
Encontra um usu\('ario aleat\('orio no grupo de interesse
.IR n\('umero .
.TP
.B s \ [<contatos>]
Mostra seu status atual, ou o de todos os
.I contatos 
dados em detalhe, incluindo todos os aliases.
.TP
.BR e ,\  w ,\  ee ,\  ww ,\  eg ,\  wg ,\  eeg ,\  wwg
Lista partes de sua lista de contatos. Os seguintes par\(^ametros s\(~ao
mostrados na primeira coluna:
.RS
.TP
.B +
Esta entrada \('e atualmente nenhum contato real, mas um alias do precedente.
Apenas com
.BR ww .
.TP
.B #
Esta entrada n\(~ao est\('a em sua lista de contatos, mas o UIN foi usado em
algum tempo. Apenas com
.B w
e
.BR ww .
.TP
.B *
Este contato ver\('a seu status mesmo se voc\(^e estiver invis\('ivel.
.TP
.B -
Este contato n\(~ao ver\('a voc\(^e.
.TP
.B ^
Este contato \('e ignorado: sem mensagens, nem mudan\(,cas de status.
.PP
O
.B ww
e
.B ee
mostra outra coluna para flags de conex\(~ao direta. Se a primeira columa
estiver vazia, outra coluna ser\('a mostrada no primeiro contato para todos
aqueles comandos a menos que seja
.BR ^ .
.TP
.B &
Uma conex\(~ao direta para este contato est\('a estabelecida.
.TP
.B \(ba
Uma conex\(~ao direta para este contato falhou.
.TP
.B :
Uma conex\(~ao direta est\('a sendo atualmente tentando ser estabelecida.
.TP
.B ^
Nenhuma conex\(~ao direta aberta, mas o endere\(,co IP e n\('umero da porta
s\(~ao conhecidos.
.RE
.TP
.B e
Lista todas as pessoas que est\(~ao online em sua lista de contatos
.TP
.B w
Lista todas as pessoas em sua lista de contatos.
.TP
.B ee
Lista todas as pessoas que est\(~ao online em sua lista de contatos com mais
detalhes.
.TP
.B ww
Lista todas as pessoas em sua lista de contatos com mais detalhes. Tamb\('em
mostra todos os aliases.
.TP
.B eg
Lista todas as pessoas que est\(~ao online em sua lista de contatos, organizados
por grupos de contatos. Novo para 0.4.10.
.TP
.B wg
Lista todas as pessoas em sua lista de contatos, organizados por grupos de
contatos. Novo para 0.4.10.
.TP
.B eeg
Lista todas as pessoas que est\(~ao online em sua lista de contatos com mais
detalhes, organizados por grupos de contatos. Novo para 0.4.10.
.TP
.B wwg
Lista todas as pessoas em sua lista de contatos com mais detalhes. Tamb\('em
mostra todos os aliases, organizados por grupos de contatos. Novo para 0.4.10.
.TP
.B ewide
Lista todas as pessoas que est\(~ao online em sua lista de contatos em formato
de tela cheia.
.TP
.B wide
Lista todas as pessoas em sua lista de contatos em formato de tela cheia.
.TP
.BI status \ [nickname]
Mostra o status do
.IR nickname .
Isto inclui o endere\(,co de IP, vers\(~ao do protocolo ICQ e tipo de
conex\(~ao, ou lista resumidamente UIN, nick, status e ultimo per\('iodo online
para todos os contatos.
.sp
Nota: Este comando est\('a deepreciado, use
.B s
ou
.B ww
ao inv\('es.
.TP
.BI f[inger] \ uin|nickname
.TP
.BI info \ uin|nickname
Mostra todas as informa\(,c\(~oes "white page" para o
.IR uin|nickname .
.TP
.B i
Lista todas as pessoas em sua lista de ignorar.
.TP
.B search
.TP
.BI search \ em@il
.TP
.BI search \ nick
.TP
.BI search \ nome\ sobrenome
Procura por um usu\('ario com
.I em@il
como seu endere\(,co de emal, com
.I nick
como seu nick (que n\(~ao deve conter um @), ou com
.I nome
como seu nome e
.I sobrenome
como seu sobrenome. Se nenhum argumento for dado, pede por
nick, nome, sobrenome, endere\(,co de email e todo um conjunto de outros dados
para procurar.
.TP
.BI add[group] \ grupo\ [contatos]
Adiciona todos os contatos em
.IR contatos
para o grupo de contatos
.IR grupo ,
que \('e criado se ele n\(~ao existir e o comando for dado como
.BI addgroup .
Novo para 0.4.10.
.br
Nota: voc\(^e precisa salvar com
.B save
para tornar isto persistente.
.TP
.BI add[alias] \ nickname\ alias
.TP
.BI add[alias] \ uin\ nickname
Adiciona
.I uin
para a sua lista de contatos como
.IR nickname ,
ou adiciona alias
.IR alias
para
.IR nickname .
Novo (addalias) para 0.4.10.
.br
Nota: voc\(^e precisa salvar com
.B save
para tornar isto persistente.
.TP
.BI rem[group] \ [all]\ grupo
.TP
.BI rem[group] \ grupo\ contatos
Remove todos os contados em
.IR contatos
do grupo de contatos
.IR grupo ,
ou remove o grupo de contatos completamente se
.B all
for dado.
Novo para 0.4.10.
Nota: voc\(^e precisa salvar com
.B save
para tornar isto persistente.
.TP
.BI rem[alias] \ [all]\ contatos
Remove os aliases en
.IR contatos .
Se qualquer nick for o \('ultimo alias para este contato, ou se
.B all
for dado, remove o contato completamente.
.br
Novo (remalias) para 0.4.10.
Nota: voc\(^e precisa salvar com
.B save
para tornar isto persistente.
.TP
.BI togig \ contatos
Troca quando as mensagens e mudan\(,cas de status de
.IR contatos
s\(~ao ignorados.
.TP
.BI toginv \ contatos
Troca quando voc\(^e estar\('a oculto para
.IR contatos .
.TP
.BI togvis \ contacts
Troca quando
.I contatos
pode ver voc\(^e mesmo quando estiver invis\('ivel.
.SH COMANDOS PARA SUA CONTA ICQ
.TP
.BI reg \ senha
Cria uma nova conta de usu\('ario com senha
.IR senha .
.TP
.BI pass \ senha
Muda sua senha icq para
.IR senha .
.br
Nota: sua senha n\(~ao deve iniciar com \('o (o byte 0xf3).
.br
Nota: voc\(^e precisa salvar com
.B save
para tornar isto persistente, salvando sua senha no arquivo
.I ~/.micq/micqrc
(veja
.BR micqrc (7)),
ou voc\(^e obter\('a uma senha errada no pr\('oximo login.
.TP
.BI change \ [n\('umero\ [mensagem]]
Muda seu status para
.IR n\('umero .
Sem um n\('umero lista alguns modos dispon\('iveis. Opcionalmente seleciona
auto resposta para este status para
.IR mensagem .
.TP
.B online
Muda o status para "online".
.TP
.BI away \ [mensagem]
Muda o status para "away". Opcionalmente seleciona auto resposta para
este status para
.IR mensagem .
.TP
.BI na \ [mensagem]
Muda o status para "not available". Opcionalmente seleciona auto resposta para
este status para
.IR mensagem .
.TP
.BI occ \ [mensagem]
Muda o status para "occupied". Opcionalmente seleciona auto resposta para
este status para
.IR mensagem .
.TP
.BI dnd \ [mensagem]
Muda o status para "do not disturb". Opcionalmente seleciona auto resposta para
este status para
.IR mensagem .
.TP
.BI ffc \ [mensagem]
Muda o status para "free for chat". Opcionalmente seleciona auto resposta para
este status para
.IR mensagem .
.TP
.B inv
Muda o status para "invisible".
.TP
.B update
Atualiza suas informa\(,c\(~oes b\('asicas de usu\('ario (email, nickname, etc.).
.TP
.B other
Atualiza outras informa\(,c\(~oes como idade e sexo.
.TP
.B about
Atualiza sua informa\(,c\(~ao 'sobre'.
.TP
.BI setr \ [n\('umero]
Seleciona seu grupo de usu\('ario aleat\('orio para
.IR n\('umero .
Sem argumentos, lista poss\('iveis grupos de interesse.
.SH COMANDOS PARA CARACTER\('ISTICAS AVAN\(,CADAS
.TP
.BI meta \ [show|load|save|set|get|rget]\ <contatos>
Manipula meta dados dos contatos. Os seguintes subcomandos s\(~ao conhecidos:
.RS
.TP
.B show
Mostra meta dados de todos os
.I contatos
dados.
.TP
.B load
L\(^e os meta dados para todos os
.I contatos
dados de um disco e mostra-os.
.TP
.B save
Salva os meta dados de todos os
.I contatos
dados para o disco.
.TP
.B set
Envia seus meta dados para o servidor.
.TP
.B get
Obt\('em os meta dados para todos os
.I contatos
do servidor e mostra-os.
.TP
.B getr
Obt\('em os meta dados para o contato da \('ultima mensagem recebida do
servdor e mostra-os.
.PP
Novo para 0.4.10.
.RE
.TP
.BI file \ [...]
Alias para
.BR peer\ file .
Novo para 0.4.10.
.TP
.BI peer \ comando\ uin|nick
Opera comando
.I comando
no usu\('ario dado por UIN
.I uin
ou nick name
.IR nick .
.RS
.TP
.B open
Abre conex\(~ao peer to peer atrav\('es de TCP com o usu\('ario.
.TP
.B close
Fecha e reseta conex\(~ao peer to peer com o usu\('ario.
.TP
.B off
Desiste de tentar estabelecer uma conex\(~ao para enviar
mensagens at\('e que seja explicitamente aberta ou resetada.
.TP
.BI file \ arquivo\ descri\(,c\(~ao
Envia arquivo
.I arquivo
com descri\(,c\(~ao
.IR descri\(,c\(~ao .
.TP
.BI files \ [arquivo\ como]...\ descri\(,c\(~ao
Envia arquivos para o usu\('ario. Podem haver arbitrariamente tantos
pares de um nome de um arquivo f\('isico
.I arquivo
e como deve ser apresentado ao ponto (peer),
.IR como .
Se
.IR como
for
.RB ' / ',
o nome do arquivo sem o caminho \('e enviado, e se for
.RB ' . '
o mesmo nome \('e enviado.
.RE
.TP
.BI conn \ [comando\ nr]
Lista todas as conex\(~oes, ou opera
.I comando
na conex\(~ao
.IR nr .
.RS
.TP
.B open
Abre a dada, ou a primeira conex\(~ao com o servidor.
.TP
.B login
Abre a dada, ou a primeira conex\(~ao com o servidor.
.TP
.B close
Fecha a conex\(~ao dada. Conex\(~oes tempor\('arias ser\(~ao removidas assim.
.TP
.B remove
Fecha e remove a conex\(~ao (tempor\('aria) dada.
.TP
.B select
Seleciona a conex\(~ao com o servidor dada como a atual.
.I nr
pode ser o n\('umero da conex\(~ao ou o UIN usado para a conex\(~ao.
.RE
.TP
.BI contact \ [comando]
Manipula a lista de contatos do servidor:
.RS
.TP
.B show
Baixa a lista de contatos do servdor e apenas mostra-a.
.TP
.B diff
Baixa a lista de contatos do servdor e mostra apenas contatos (pares uin/nick)
que n\(~ao est\(~ao na lista de contatos local.
.TP
.B import
Baixa a lista de contatos do servdor e adiciona todos os contatos na local.
.PP
Ainda n\(~ao h\('a upload de lista ainda.
.RE
.TP
.BI peek \ nick
Checa quando
.I nick
est\('a online ou n\(~ao. Abusa de um bug no protocolo ICQ para isto;
nenhuma informa\(,c\(~ao adicional exceto onlne ou offline pode ser encontrada
desta maneira.
.SH VEJA TAMB\('EM
.BR micq (1),
.BR micqrc (5)
.SH AUTOR
Esta man page foi criada por James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
para uma refer\(^encia a todos os comandos interativos no
.BR mICQ .
Traduzido por Leonardo Rosa
.IR <leorosa@feq.unicamp.br> .
