.\" $Id: climmcmds.7 1055 2003-01-08 22:20:59Z kuhlmann $ -*- nroff -*-
.\"  EN: climmcmds.7 1000 2007-07-12 00:00:00Z ,v 1.28U 2002/08/04 21:01:38
.\"      ^^ <version of English man page this is in sync with>
.TH CLIMM 7 climm FR
.SH NOM
.B climm
\- les commandes interactives
.SH NOTE - THIS FILE HAS NOT YET BEEN UPDATED FOR climm 0.4.10.
.SH DESCRIPTION
Cette page de manuel d\('ecrit les commandes qui peuvent \(^etre utilis\('e dans climm.
Cette page contient les m\(^emes informations que l'aide en ligne.
.SH COMMANDES

.TP
.BI trans \ [langue|nr]\ ...
Basculer vers la langue
.IR langue ,
donn\('e par son code iso, ou affiche la cha\(^ine de carat\(`eres traduite num\('ero
.IR nr .
Pour s\('electionner la langue par d\('efaut donn\('ee par les variables d'environnement
.BR LANG ,
.BR LC_ALL
et
.BR LC_MESSAGES ,
utilisez
.BR ! ,
.BR auto
ou
.BR default .
Pour ne pas s\('electionner de traduction du tout, utilisez
.BR . ,
.BR none
ou
.BR unload .
Pour obtenir des informations de debug, ajoutez le pr\('efixe
.BR debug .
Pour obtenir des messages farfelus, ajoutez le suffixe
.BR _fun .
.sp
Les fichiers correspondant \(`a ~/.climm/i18n/*.i18n sont prioritaires sur les messages globaux,
alors que les messages "farfelus" sont plus prioritaires que les messages standards.
.sp
En fait, vous pouvez donner autant d'arguments que vous le voulez,
par exemple pour afficher la cha\(^ine de caract\(`eres num\('ero 117 en allemand
et ensuite revenir au langage par d\('efaut, utilisez "trans de 117 default".
.TP
.BI tabs
Affiche une liste d'utilisateurs que vous pouvez parcourir gr\(^ace \(`a
la touche tabulation.
.TP
.BI save
Enregistre les param\(`etres actuels dans le fichier de configuration, qui est
.IR ~/.climm/climmrc ,
a moins qu'autre chose n'ait \('et\('e sp\('ecifi\('e.
Faites attention car cela ne conservera pas les commentaires pr\('esents
dans le fichier.
.TP
.BI r \ [message]
R\('epondre au dernier message re\(,cu. Si un
.IR message
n'est pas donn\('e, le mode multi-lignes est activ\('e.
Pour envoyer le message multi-lignes, \('ecrivez un point
.RB ( . )
seul sur une ligne.  Pour annuler l'\('ecriture d'un message, \('ecrivez un diese
.RB ( # )
tout seul sur une ligne.
.TP
.BI a \ [message]
Envoie un message \(`a la derni\(`ere personne \(`a laquelle vous avez envoy\('e un message. Voir
.BR r
pour un comportement sans
.IR message .
.TP
.BI msg \ uin|surnom\ [message]
Envoie un message \(`a
.IR uin|surnom .
Voir
.BR r
pour conna\(^itre son comportement sans
.IR message .
.TP
.BI url \ uin|surnom\ url\ message
Envoie un
.IR message
concernant une
.IR url
\(`a
.IR uin|surnom .
.TP
.BI sms \ num\('ero\ message
Envoie le message SMS
.IR message
\(`a un t\('el\('ephone de num\('ero
.IR num\('ero ,
qui a la forme suivante : +<code pays><num\('ero>.
.TP
.BI msga
Envoie un message multi-lignes \(`a tous les contacts que vous poss\('edez.
Utilisez un point
.RB ( . )
seul sur une ligne pour envoyer le message, ou un diese
.RB ( # )
seul sur une ligne pour annuler le message.
.TP
.BI resend \ uin|surnom\ ...
R\('e-envoie le dernier message \(`a
.IR uin
ou
.IR surnom .
L'argument peut \(^etre r\('ep\('et\('e autant de fois que n\('ecessaire.
.TP
.BI uptime
Affiche depuis combien de temps climm s'ex\('ecute.
.TP
.BI last \ [contact]

.B BEGIN UNTRANSLATED

Show a list of users who have sent you messages or the last message
received from
.IR contact ,
which can be a
.I uin
or a
.IR nickname ,
or from everyone who already sent a message.

.B END UNTRANSLATED

Affiche une liste d'utilisateurs qui vous ont envoy\('e des messages ou le
dernier message re\(,cu de la part de
.IR contact ,
qui peut \(^etre un
.IR uin
ou un
.IR surnom .
.TP
.BI verbose \ [verb]
Param\(`etre la verbosit\('e de climm \(`a
.IR verb ,
ou affiche le niveau actuel de verbosit\('e. Le niveau de verbosit\('e est
constitu\('e d'un ensemble d'options :
.RS

.B BEGIN UNTRANSLATED

.B 8
Show protocol errors.
.TP
.B 16
Show creation and deletion of packets.
.TP
.B 32
Show added and removed queue events.
.TP
.B 64
Show created and deleted connections.
Show v6 packets and their data.
.TP
.B 4096
Show v7/v8 packets.
.TP
.B 8192
Show the hexdump of v7/v8 packets.
.TP
.B 16284
Save those packets to disc.
.TP
.B 65536
Show peer-to-peer packets.
.TP
.B 131072
Show the hexdump of peer-to-peer packets.
.TP
.B 262144
Save those packets to disc.
.TP
.B 2097152
Show peer-to-peer handshake.
.TP
.B 4194304
Show I/O connection setup.


.B END UNTRANSLATED

.TP
.128
Affiche les paquets entrants et sortants.
.TP
.256
Ecrit les paquets entrants et sortants concernant le serveur dans un fichier
(~/.climm/debug/packets).
.IP
Il en existe d'autres.

.B BEGIN UNTRANSLATED

However, any non-zero verbose level will cause more information to be printed,
and any level greater than 1 even more.

.B END UNTRANSLATED

.TP
.BI clear
Efface l'\('ecran.
.TP
.BI sound \ [commande]
Active ou d\('esactive le son, ou param\(`etre l'ex\('ecution de la commande
.IR commande
pour le produire.
.TP
.BI soundonline \ [commande]
Active ou d\('esactive le son pour les notifications d'utilisateurs connect\('es,
ou param\(`etre l'ex\('ecution de la commande
.IR commande
pour le produire.
.TP
.BI soundoffline \ [commande]
Active ou d\('esactive le son pour les notifications d'utilisateurs se d\('econnectant,
ou param\(`etre l'ex\('ecution de la commande
.IR commande
pour le produire.
.TP
.BI q
Termine climm.
.TP
.BI auto \ [on|off]
Active ou d\('esactive les messages de r\('eponse automatique.
Si aucune des deux options n'est donn\('ee, la liste des r\('eponses automatiques
actuelles est donn\('ee.
.TP
.BI auto \ \('etat\ message
Change le message de r\('eponse automatique pour l'\('etat
.IR \('etat
comme \('etant le message
.IR message .
.TP
.BI autoaway \ [d\('elai|on|off]
Param\(`etre le d\('elai \(`a
.IR d\('elai ,
ou active le mode "auto away" en utilisant le dernier d\('elai choisi si
.IR on
est donn\('e, ou d\('esactive le mode "auto away" si l'option
.IR off
est choisie en enregistrant le d\('elai actuel. Un d\('elai d'une valeur de 0 est
\('equivalent \(`a l'option
.IR off .
Si aucun argument n'est donn\('e, les param\(`etres actuels sont affich\('es.
.TP
.BI alter \ ancienne_commande\ nouvelle_commande
Renomme la commande
.IR ancienne_commande
en
.IR nouvelle_commande .
.TP

.B BEGIN UNTRANSLATED

.BI auth \ [req|grant|deny|add]\ uin|nickname
Grant or deny
.I uin|nickname
to add you to their list, request
.I uin|nickname
to allow you to add them to your contact list, or tell
.I uin|nickname
that you added hem to your contact list.

.B END UNTRANSLATED

.TP
.BI auth \ uin|surnom
Autorise
.IR uin|surnom
vous a ajouter \(`a sa liste de contacts.
.TP
.BI rand \ num\('ero
Trouve al\('eatoirement un utilisateur dans le groupe d'int\('er\(^et
.IR num\('ero .
.TP
.BI pass \ mot_de_passe
Change votre mot de passe ICQ en
.IR mot_de_passe .
.br
Remarque: vous devez entrer
.B save
pour rendre la modification persistante au cas o\(`u vous sauvegardiez votre mot
de passe dans le fichier
.IR ~/.climm/climmrc
(voir
.BR climmrc (5),
sinon votre mot de passe sera rejet\('e \(`a la prochaine authentification.
.TP
.BI search
.TP
.BI search \ email
.TP
.BI search \ surnom
.TP
.BI search \ pr\('enom\ nom
Recherche un utilisateur qui a
.IR email
pour courriel,
.IR surnom
comme surnom (qui peut contenir le caract\(`ere @), ou
.IR pr\('enom
comme pr\('enom et
.IR nom
comme nom. Si aucun argument n'est donn\('e, vous devrez donner le surnom,
pr\('enom, nom, courriel et une quantit\('e importante de donn\('ees qui seront utilis\('ees
comme crit\(`eres de recherche.
.TP

.B BEGIN UNTRANSLATED

.BI add \ nickname\ alias

.B END UNTRANSLATED

.TP
.BI add \ uin\ [surnom]
Ajoute
.IR uin
\(`a votre liste de contacts avec comme surnom
.IR surnom ,

.B BEGIN UNTRANSLATED

or add alias
.IR alias
for

.B END UNTRANSLATED

ou renomme
.IR uin
en
.IR surnom .
Si
.IR surnom
n'est pas sp\('ecifi\('e, utilise
.IR uin
comme surnom.
.br
Remarque: vous devez utiliser la commande
.IR save
pour rendre les changements persistants.
.TP

.B BEGIN UNTRANSLATED

.BI rem \ alias
Remove the alias
.IR alias .
If
.IR alias
is the last alias for this contact, remove the contact completely.

.B END UNTRANSLATED

.BI rem \ surnom
Supprime
.IR surnom
de votre liste de contacts.
.br
Remarque: vous devez utiliser la commande
.IR save
pour rendre ce changement persistant.
.TP
.BI togvis \ surnom
Active ou d\('esactive le fait que
.IR nickname
puisse vous contacter m\(^eme si vous \(^etes en mode invisible.
.TP
.BI toginvis \ surnom
Active ou d\('esactive le fait que vous soyez invisible pour le contact ayant le surnom
.IR surnom .
.TP
.BI togig \ surnom
Active ou d\('esactive le fait que les messages et changements d'\('etats du contact ayant comme surnom
.IR surnom
soient ignor\('es.
.TP
.BI f[inger] \ uin|surnom
.TP
.BI info \ uin|surnom
Affiche toutes les infos pour le contact ayant comme uin ou surnom
.IR uin|surnom .
.TP
.BI e
Affiche toutes les personnes de votre liste de contacts qui sont connect\('ees.
.TP
.BI w
Affiche toutes les personnes de votre liste de contacts.
.TP

.B BEGIN UNTRANSLATED

.B ee
List all people who are online in your contact list with more details.
.TP
.B ww
List all people in your contact list with more details. Also shows all aliases.

.B END UNTRANSLATED

.TP
.BI wide
Affiche toutes les personnes qui sont dans votre liste de contacts en utilisant
toute la largeur de l'\('ecran.
.TP
.BI ewide
Affiche toutes les personnes de votre liste de contacts qui sont connect\('ees
en utilisant toute la largeur de l'\('ecran.
.TP

.B BEGIN UNTRANSLATED

.B s \ [nickname]
Show your current status, or the given nickname's in detail, including all aliases.

.B END UNTRANSLATED

.BI s
Affiche votre \('etat actuel.
.TP
.BI i
Affiche tous les contacts que vous ignorez.
.TP
.BI status \ surnom
Affiche l'\('etat du contact ayant pour surnom
.IR surnom .
Les informations affich\('ees comprennent l'adresse IP, la version du
protocole ICQ et le type de connexion.

.B BEGIN UNTRANSLATED

Note: This command is deprecated, use
.B s
or
.B ww
instead.

.B END UNTRANSLATED

.TP
.BI reg \ mot_de_passe
Cr\('ee un nouvel utilisateur ayant pour mot de passe
.IR mot_de_passe .
.TP

.B BEGIN UNTRANSLATED

.BI change \ [number\ [message]]
Changes your status to
.IR number .
Without a number it lists some available modes. Optionally
set auto response for this status to
.IR message .
.TP

.B END UNTRANSLATED

.BI change \ [num\('ero]
Change votre \('etat \(`a l'\('etat num\('ero
.IR num\('ero .
Si vous ne lui fournissez pas de num\('ero, cette commande affiche une liste
des modes disponibles.
.TP
.BI online
Change votre \('etat en "connect\('e".
.TP

.B BEGIN UNTRANSLATED

.BI away \ [message]
Change status to "away". Optionally set auto response for this status to
.IR message .

.B END UNTRANSLATED

.BI away
Change votre \('etat en "absent".
.TP

.B BEGIN UNTRANSLATED

.BI na \ [message]
Change status to "not available". Optionally set auto response for this status to
.IR message .

.B END UNTRANSLATED

.BI na
Change votre \('etat en "non disponible".
.TP

.B BEGIN UNTRANSLATED

.BI occ \ [message]
Change status to "occupied". Optionally set auto response for this status to
.IR message .

.B END UNTRANSLATED

.BI occ
Change votre \('etat en "occup\('e".
.TP

.B BEGIN UNTRANSLATED

.BI dnd \ [message]
Change status to "do not disturb". Optionally set auto response for this status to
.IR message .

.B END UNTRANSLATED

.BI dnd
Change votre \('etat en "ne pas d\('eranger".
.TP

.B BEGIN UNTRANSLATED

.BI ffc \ [message]
Change status to "free for chat". Optionally set auto response for this status to
.IR message .

.B END UNTRANSLATED

.BI ffc
Change votre \('etat en "libre pour chatter".
.TP
.BI inv
Change votre \('etat en "invisible".
.TP
.BI update
Actualise vos informations basiques (courriel, surnom, etc.).
.TP
.BI other
Actualise d'autres informations comme l'age et le sexe.
.TP
.BI about
Met \(`a jour les informations de la section "\(`a propos".
.TP
.BI set \ option\ valeur
Donne a l'option
.IR option
la valeur
.BR on
ou
.BR off .
.IR option
peut \(^etre
.BR color ,
.BR funny
ou
.BR quiet .
.TP
.BI peek \ surnom
V\('erifie si l'utilisateur ayant pour surnom
.IR surnom
est actuellement connect\('e. Cette commande utilise un bug dans le protocole ICQ pour
trouver ce renseignement;
aucune information except\('e l'\('etat de connexion ne peut \(^etre r\('ecup\('er\('ee de cette mani\(`ere.
.TP
.BI setr \ [num\('ero]
Param\(`etre votre num\('ero de groupe d'utilisateur al\('eatoire \(`a
.IR num\('ero .
Sans argument, cette command affiche les groupes d'int\('er\(^ets existants.
.TP
.BI peer \ commande\ uin|surnom
Effectue la commande
.IR commande
sur l'utilisateur dont l'uin est
.IR uin
ou dont le surnom est
.IR surnom .

.B BEGIN UNTRANSLATED

.RS
.TP
.B open
Open a peer to peer connection over TCP to the user.
.TP
.B close
Close and reset a peer to peer connection to the user.
.TP
.B off
Switch off trying to establish such a connection for sending
messages until it is explicitly opened or reset.
.TP
.B auto
Get the user's current auto response.
.TP
.B away
Get the user's current away auto response.
.TP
.B na
Get the user's current not available auto response.
.TP
.B dnd
Get the user's current do not disturb auto response.
.TP
.B occ
Get the user's current occupied auto response.
.TP
.B ffc
Get the user's current free for chat message.
.TP
.BI file \ file\ description
Send file
.I file
with description
.IR description .
.TP
.BI files \ [file\ as]...\ description
Send files to the user. There may be arbitrarily many
pairs of a physical file name
.I file
and the name to be presented to the peer,
.IR as .
If
.IR as
is
.RB ' / ',
the file name without the path is sent, and if it is
.RB ' . '
the same name is sent.
.RE

.B END UNTRANSLATED

.IR commande
peut \(^etre
.BR open
pour ouvrir une connexion de pair \(`a pair avec TCP vers l'utilisateur, ou
.BR close
pour fermer et r\('einitialiser une telle connexion, ou
.BR off
pour arr\(^eter d'\('essayer d'\('etablir une telle connexion pour envoyer des messages
jusqu'\(`a ce qu'elle soit explicitement ouverte ou r\('einitialis\('ee, ou
.BR auto
pour obtenir la r\('eponse automatique actuelle de l'utilisateur ou encore
.BR away ,
.BR na ,
.BR dnd ,
.BR occ
ou
.BR ffc
pour obtenir la r\('eponse automatique de l'utilisateur pour un de ces \('etats.
.TP
.BI conn \ [commande\ nr]
Affiche toutes les connexion, ou effectue la commande
.IR command
sur la connexion
.IR nr .

.B BEGIN UNTRANSLATED

.RS
.TP
.B open
Open the given, or the first server connection.
.TP
.B login
Open the given, or the first server connection.
.TP
.B close
Close the given connection. Temporary connections will get removed by this.
.TP
.B remove
Close and remove given (temporary) connection.
.TP
.B select
Select the given server connection as the current one.
.I nr
may be the connection number or the UIN used for the connection.
.RE

.B END UNTRANSLATED

.IR commande
peut \(^etre
.BR open
ou
.BR login
pour ouvrir cette connexion si elle ne l'est pas actuellement.

.B BEGIN UNTRANSLATED

.TP
.BI contact \ [command]
Handle the server side contact list:
.RS
.TP
.B show
Download the server side contact list and just show it.
.TP
.B diff
Download the server side contact list and show only contacts (uin/nick pairs) that are not
in the local contact list.
.TP
.B import
Download the server side contact list and add all contacts to the local one.
.RE

.B END UNTRANSLATED

.SH VOIR AUSSI
.BR climm (1),
.BR climmrc (5)
.SH AUTEUR
Cette page de manuel a \('et\('e \('ecrite par James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca>
pour pouvoir consulter une r\('ef\('erence de toutes les commandes de
.BR climm .
Cette page de manuel a \('et\('e traduite par Julien Gilli
.IR <jgilli@nerim.fr>.
