.\" $Id$
.\"  EN: micqrc.5,v 1.8 2002/08/04 21:01:38
.\"      ^^ <version of English man page this is in sync with>
.TH MICQRC 5 mICQ FR
.SH NOM
.BR ~/.micq/micqrc
\- Le fichier de configuration de mICQ
.SH DESCRIPTION
Cette page de manuel décrit le fichier de configuration de micq. Il comprend 
plusieurs sections qui débutent par
.BR [section] ,
où
.BR section
est le nom de la section.
.SH CONNEXIONS - connection
Une section 
.BR Connection
décrit une connexion au sein d'ICQ. En général, il y en a deux,
qui sont en relation l'une avec l'autre: une connexion au serveur ICQ, et une 
connexion pour écouter les communications des contacts.


.TP
.BI type \ type\ [auto]
Paramètre le type de la connexion à
.IR type ,
qui peut être
.BR server
pour une connexion au serveur ICQ, ou
.BR peer
pour une connexion qui concerne les communications avec les contacts. Si l'option 
.IR auto
est donnée, la connexion est créée au démarrage de mICQ. 
Ceci est probablement ce que vous devriez faire, à moins que vous 
possédiez plusieurs UINs, dans ce cas paramétrez cela sur la connexion 
correspondant à l'UIN que vous utilisez.

.TP
.BI version \ nr
Paramètre la version du protocole ICQ utilisée pour cette connexion à
.IR nr .
Remarquez que pour les connexions vers des serveurs, seule la version
.BR 5
est supportée, bien que le support pour la version
.BR 8
soit plannifié, et seule la version
.BR 6 
est supportée pour les communications avec les contacts.

.TP
.BI server \ server
Paramètre le serveur auquel se connecter à
.IR server .
La valeur par défaut est
.BR icq.icq.com .
Ceci est inutilisé pour les communications avec les contacts.

.TP
.BI port \ port
Paramètre le port auquel se connecter sur le serveur à
.IR port ,
ou le port à écouter pour les communications avec les contacts à
.IR port .

.TP
.BI uin \ UIN
Paramètre l'UIN à utiliser pour la phase de connexion à
.IR UIN .
Inutilisé pour les communications avec les contacts.

.TP
.BI password \ [mot_de_passe]
Paramètre le mot de passe à utiliser lors de la phase de connexion à
.IR mot_de_passe .
Inutilisé pour les communications avec les contacts. Si ce paramètre n'est 
pas présent, le mot de passe vous sera demandé au lancement.

.TP
.BI status \ nr
Paramètre l'état à choisir après la phase de connexion à
.IR nr .
L'état peut être:
.RS
.TP
0
connecté
.TP
1
absent
.TP
5
non disponible
.TP
17
occupé
.TP
19
ne pas déranger
.TP
32
libre pour chatter
.TP
256
invisible
.RE
.SH GENERAL - general
Cette section inclue les options concernant SOCKS 5, qui seront 
éventuellement déplacées vers leur propre section, les options générales,
et quelques chaînes de caractères à redéfinir.


.TP
.BI s5_use \ nombre
Paramétrez
.IR number
à 0 pour désactiver et 1 pour activer l'utilisation de SOCKS 5.

.TP
.BI s5_host \ host
Se connecter au proxy socks 5 de la machine
.IR machine .

.TP
.BI s5_port \ port
Se connecter au proxy socks 5 qui écoute sur le port
.IR port .

.TP
.BI s5_auth \ nombre
Paramètrez
.IR nombre
à 0 pour ne pas effectuer l'authentification et 1 pour l'effectuer.

.TP
.BI s5_name \ nom
S'identifier en tant qu'utilisateur de nom
.IR nom
auprès du proxy socks 5.
.br

.TP
.BI s5_pass \ mot_de_passe
S'authentifier avec le mot de passe
.IR mot_de_passe
auprès du proxy socks5.

.sp
Maintenant les options :


.TP
.BI verbose \ niveau
Paramètre le niveau de verbosité au lancement à
.IR niveau .

.TP
.BI auto_away \ délai
Paramètre le délai précédent l'activation de l'état away à
.IR délai
en secondes. Donnez la valeur
.BR 0
pour désactiver le mode auto away.

.TP
.BI Screen_width \ largeur
Paramètre la largeur par défaut de l'écran à
.IR largeur .
Si la valeur n'est pas paramétrée ou égale à 
.BR 0 , \ 80
sera la valeur utilisée. Cela est rarement utile car 
généralement la largeur actuelle de l'écran peut être connue à l'exécution.

.TP
.BI set \ delbs\ on|off
Si la valeur est
.B on ,
le caractère suppr agira comme un retour (backspace). Si la valeur est
.B off ,
le caractère suppr agira normalement.

.TP
.BI set \ russian\ on|off
Désactive ou active la conversion des caractères russes entre le jeu koi8-r/u 
et  cp1251.

.TP
.BI set \ japanese\ on|off
Désactive ou active la conversion des caractères japonais entre le jeu 
Shift-JIS et EUC.

.TP
.BI set \ funny\ on|off
Désactive ou active les messages amusants.

.TP
.BI set \ color\ on|off
Désactive ou active l'utilisation des couleurs.

.TP
.BI set \ hermit\ on|off
Si la valeur est
.IR on ,
tous les messages provenant de personnes qui ne sont pas dans votre 
liste de contacts seront ignorés.

.TP
.BI set \ log\ on|off
Désactive ou active l'utilisation des journaux.

.TP
.BI set \ logonoff\ on|off
Lorsque l'utilisation des journaux est activée, désactive ou active l'enregistrement 
des changements d'états de connecté à deconnecté et vice-versa.

.TP
.BI set \ auto\ on|off
Désactive ou active les réponses automatiques.

.TP
.BI set \ uinprompt\ on|off
Désactive ou active l'utilisation à partir de l'invite du dernier surnom 
duquel vous avez reçu un message.

.TP
.BI set \ linebreak\ type
Paramètre le type des retours à la ligne pour les messages reçus à
.IR type ,
qui peut être
.BR simple
pour arranger les lignes de manière habituelle,
.BR break
pour obtenir un retour à la ligne avant chaque message,
.BR indent
pour obtenir un retour à la ligne et indenter le message et
.BR smart
pour obtenir un retour à la ligne seulement si le message ne rentre pas dans la ligne actuelle.

.TP
.BI set \ tabs\ simple|cycle|cycleall
Sélectionne le type d'utilisation de la complétion. Les anciennes versions de 
mICQ ne connaissaient que
.BR simple ,
qui ne fonctionne qu'avec la commande
.BR msg
et complète la commande en parcourant la liste de tous les contacts auquel 
vous avez envoyé ou desquels vous avez reçus des messages. 
Le texte déjà entré après le surnom était perdu.
.BR cycle
parcourt la liste de tous les contacts en ligne de votre liste de contact. 
Elle conserve tout texte entré précédemment intact, cependant elle ne 
fonctionne qu'avec la commande 
.BR msg .
.BR cycleall
est équivalente à
.BR cycle ,
mais parcourt la liste de tous les contacts, même ceux qui ne sont pas connectés.
.sp
Enfin, des chaînes de caractères peuvent être définies:
.TP
.BI logplace \ fichier|répertoire
Paramètre le fichier contenant le journal à
.IR fichier ,
ou le répertoire contenant les journaux à
.IR répertoire .
Remarquez qu'un chemin est considéré comme un répertoire si il a un
.BR / 
à la 
fin de son nom.

.TP
.BI sound \ on|off|cmd
Désactive ou active l'avertissement sonore. Si le paramètre n'est ni
.B on
ni
.B off,
le paramètre est considéré comme un programme à exécuter à la place de 
l'avertissement sonore.

.TP
.BI soundonline \ on|off|cmd
Même chose que ci-dessus, mais concernant les utilisateurs se connectant.

.TP
.BI soundoffline \ on|off|cmd
Même chose que ci-dessus, mais pour les utilisateurs qui se déconnectent.

.TP
.BI receivescript \ cmd
Paramètre la commande à exécuter lors de la réception d'un message. 
Laissez vide pour ne rien faire.

.TP
.BI auto \ état\ chaîne_de_caractères
Paramètre la réponse automatique de l'état
.IR état
à
.IR chaine_de_caractères.
Cette option peut être répétée pour tous les états possibles
.BR away ,
.BR na ,
.BR dnd ,
.BR occ ,
.BR inv ,
and
.BR ffc .
.SH CHAINES - strings
Cette section contient les changements de nom de commandes.
.TP
.BI alter \ ancienne\ nouvelle
Renomme la commande
.IR ancienne
en
.IR nouvelle .
Remarquez que l'ancien nom peut toujours être utilisé, à moins qu'il entre 
en conflit avec le nom de la commande
.IR nouvelle
Pour les noms de commandes possibles, consultez 
.BR micq (7).
Cette option peut être répétée à volontée.
.SH CONTACTS - contacts
Cette section contient la liste de contacts.
.I [*][~][^] uin surnom
Donner à l'utilisateur possédant l'UIN
.IR uin
le surnom
.IR surnom .
Si
.B *
est donnée, l'utilisateur peut vous voir lorsque vous êtes en mode invisible. Si
.B ~
est donnée, il vous verra toujours comme étant déconnecté. Si
.B ^
est donnée, vous ignorez l'utilisateur.
Si un UIN apparaît plusieurs fois, tous excepté le premier sont considérés comme 
des alias.
Remarque: la liste de contacts doit être la dernière partie du fichier.
.SH VOIR AUSSI
.BR micq (1),
.BR micq (7)
.SH AUTEUR
Cette page de manuel a été écrite par James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca> .
Elle a été écrite pour correspondre à la nouvelle syntaxe du fichier de 
configuration choisie par Rüdiger Kuhlmann
.IR <micq@ruediger-kuhlmann.de> .
Cette page de manuel a été traduite vers le français par Julien Gilli 
.IR <jgilli@nerim.fr> .
