.\" $Id$
.\"  EN: micq.7,v 1.1 2002/08/11 20:17:33
.\"      ^^ <version of English man page this is in sync with>
.TH MICQ 7 mICQ FR
.SH NOM
.B mICQ
\- les commandes interactives
.SH DESCRIPTION
Cette page de manuel décrit les commandes qui peuvent être utilisé dans mICQ.
Cette page contient les mêmes informations que l'aide en ligne.
.SH COMMANDES

.TP
.BI trans \ [langue|nr]...
Basculer vers la langue
.IR langue ,
donné par son code iso, ou affiche la chaîne de caratères traduite numéro
.IR nr .
Pour sélectionner la langue par défaut donnée par les variables d'environnement
.BR LANG ,
.BR LC_ALL
et
.BR LC_MESSAGES ,
utilisez
.BR ! ,
.BR auto
ou
.BR default .
Pour ne pas sélectionner de traduction du tout, utilisez
.BR . ,
.BR none
ou
.BR unload .
Pour obtenir des informations de debug, ajoutez le préfixe
.BR debug .
Pour obtenir des messages farfelus, ajoutez le suffixe 
.BR _fun .
.sp
Les fichiers correspondant à ~/.micq/i18n/*.i18n sont prioritaires sur les messages globaux, 
alors que les messages "farfelus" sont plus prioritaires que les messages standards.
.sp
En fait, vous pouvez donner autant d'arguments que vous le voulez, 
par exemple pour afficher la chaîne de caractères numéro 117 en allemand 
et ensuite revenir au langage par défaut, utilisez "trans de 117 default".
.TP
.BI tabs 
Affiche une liste d'utilisateurs que vous pouvez parcourir grâce à 
la touche tabulation.
.TP
.BI save
Enregistre les paramètres actuels dans le fichier de configuration, qui est
.IR ~/.micq/micqrc ,
a moins qu'autre chose n'ait été spécifié.
Faites attention car cela ne conservera pas les commentaires présents 
dans le fichier.
.TP
.BI r \ [message]
Répondre au dernier message reçu. Si un
.IR message
n'est pas donné, le mode multi-lignes est activé.  
Pour envoyer le message multi-lignes, écrivez un point 
.RB ( . )
seul sur une ligne.  Pour annuler l'écriture d'un message, écrivez un diese 
.RB ( # )
tout seul sur une ligne.
.TP
.BI a \ [message]
Envoie un message à la dernière personne à laquelle vous avez envoyé un message. Voir 
.BR r
pour un comportement sans 
.IR message .
.TP
.BI msg \ uin|surnom\ [message]
Envoie un message à
.IR uin|surnom .
Voir
.BR r 
pour connaiître son comportement sans 
.IR message .
.TP
.BI url \ uin|surnom\ url\ message
Envoie un 
.IR message
concernant une 
.IR url
à 
.IR uin|surnom .
.TP
.BI sms \ numéro\ message
Envoie le message SMS 
.IR message
à un téléphone de numéro 
.IR numéro ,
qui a la forme suivante : +<code pays><numéro>.
.TP
.BI msga
Envoie un message multi-lignes à tous les contacts que vous possédez. 
Utilisez un point 
.RB ( . )
seul sur une ligne pour envoyer le message, ou un diese 
.RB ( # )
seul sur une ligne pour annuler le message.
.TP
.BI resend \ uin|surnom\ ...
Ré-envoie le dernier message à 
.IR uin
ou 
.IR surnom .
L'argument peut être répété autant que nécessaire.
.TP
.BI uptime
Affiche depuis combien de temps mICQ s'exécute.
.TP
.BI last\ [contact]
Affiche une liste d'utilisateurs qui vous ont envoyé des messages ou le 
dernier message reçu de la part de 
.IR contact ,
qui peut être un 
.IR uin
ou un 
.IR surnom .
.TP
.BI verbose \ [verb]
Paramètre la verbosité de mICQ à 
.IR verb ,
ou affiche le niveau actuel de verbosité. Le niveau de verbosité est 
constitué d'un ensemble d'options :
.RS
.TP
.128
Affiche les paquets entrants et sortants.
.TP
.256
Ecrit les paquets entrants et sortants concernant le serveur dans un fichier 
(~/.micq/debug/packets).
.IP
Il en existe d'autres.
.TP
.BI clear
Efface l'écran.
.TP
.BI sound \ [commande]
Active ou désactive le son, ou paramètre l'exécution de la commande 
.IR commande 
pour le produire.
.TP
.BI soundonline \ [commande]
Active ou désactive le son pour les notifications d'utilisateurs connectés, 
ou paramètre l'exécution de la commande 
.IR commande 
pour le produire.
.TP
.BI soundoffline \ [commande]
Active ou désactive le son pour les notifications d'utilisateurs se déconnectant, 
ou paramètre l'exécution de la commande 
.IR commande 
pour le produire.
.TP
.BI q
Termine mICQ.
.TP
.BI auto \ [on|off]
Active ou désactive les messages de réponse automatique. 
Si aucune des deux options n'est donnée, la liste des réponses automatiques 
actuelles est donnée.
.TP
.BI auto \ état\ message
Change le message de réponse automatique pour l'état 
.IR état
comme étant le message 
.IR message .
.TP
.BI autoaway \ [délai|on|off]
Paramètre le délai à 
.IR délai ,
ou active le mode "auto away" en utilisant le dernier délai choisi si 
.IR on
est donné, ou désactive le mode "auto away" si l'option  
.IR off
est choisie en enregistrant le délai actuel. Un délai d'une valeur de 0 est 
équivalent à l'option 
.IR off .
Si aucun argument n'est donné, les paramètres actuels sont affichés.
.TP
.BI alter \ ancienne_commande\ nouvelle_commande
Renomme la commande 
.IR ancienne_commande
en 
.IR nouvelle_commande .
.TP
.BI auth \ uin|surnom
Autorise
.IR uin|surnom
à vous ajouter à sa liste de contacts.
.TP
.BI rand \ numéro
Trouve aléatoirement un utilisateur dans le groupe d'intérêt 
.IR numéro .
.TP
.BI pass \ mot_de_passe
Change votre mot de passe ICQ en 
.IR mot_de_passe . 
.br
Remarque: vous devez entrer 
.B save
pour rendre la modification persistante au cas où vous sauvegardiez votre mot 
de passe dans le fichier 
.IR ~/.micq/micqrc
(voir 
.BR micqrc (7),
sinon votre mot de passe sera rejeté à la prochaine authentification.
.TP
.BI search
.TP
.BI search \ email
.TP
.BI search \ surnom
.TP
.BI search \ prénom\ nom
Recherche un utilisateur qui a 
.IR email
pour courriel, 
.IR surnom
comme surnom (qui peut contenir le caractère @), ou 
.IR prénom
comme prénom et 
.IR nom 
comme nom. Si aucun argument n'est donné, vous devrez donner le surnom, 
prénom, nom, courriel et une quantité importante de données qui seront utilisées 
comme critères de recherche.
.TP
.BI add \ uin\ [surnom]
Ajoute 
.IR uin
à votre liste de contacts avec comme surnom 
.IR surnom , 
ou renomme 
.IR uin
en 
.IR surnom .
Si 
.IR surnom 
n'est pas spécifié, utilise 
.IR uin
comme surnom.
.br
Remarque: vous devez utiliser la commande
.IR save
pour rendre les changements persistants.
.TP
.BI rem \ surnom 
Supprime 
.IR surnom 
de votre liste de contacts.
.br
Remarque: vous devez utiliser la commande 
.IR save
pour rendre ce changement persistant.
.TP
.BI togvis \ surnom 
Active ou désactive le fait que 
.IR nickname
puisse vous contacter même si vous êtes en mode invisible.
.TP
.BI toginvis \ surnom 
Active ou désactive le fait que vous soyez invisible pour le contact ayant le surnom 
.IR surnom .
.TP
.BI togig \ surnom 
Active ou désactive le fait que les messages et changements d'états du contact ayant comme surnom 
.IR surnom 
soient ignorés.
.TP
.BI info \ uin|surnom 
Affiche toutes les infos pour le contact ayant comme uin ou surnom
.IR uin|surnom .
.TP
.BI w
Affiche toutes les personnes de votre liste de contacts.
.TP
.BI e 
Affiche toutes les personnes de votre liste de contacts qui sont connectées.
.TP
.BI wide
Affiche toutes les personnes qui sont dans votre liste de contacts en utilisant 
toute la largeur de l'écran.
.TP
.BI ewide
Affiche toutes les personnes de votre liste de contacts qui sont connectées 
en utilisant toute la largeur de l'écran.
.TP
.BI s
Affiche votre état actuel.
.TP
.BI i
Affiche tous les contacts que vous ignorez.
.TP
.BI status \ surnom 
Affiche l'état du contact ayant pour surnom 
.IR surnom .
Les informations affichées comprennent l'adresse IP, la version du 
protocole ICQ et le type de connexion.
.TP
.BI change \ [numéro]
Change votre état à l'état numéro 
.IR numéro .
Si vous ne lui fournissez pas de numéro, cette commande affiche une liste 
des modes disponibles. 
.TP
.BI reg \ mot_de_passe 
Crée un nouvel utilisateur ayant pour mot de passe 
.IR mot_de_passe .
.TP
.BI online
Change votre état en "connecté".
.TP
.BI away
Change votre état en "absent".
.TP
.BI na
Change votre état en "non disponible".
.TP
.BI occ             
Change votre état en "occupé".
.TP
.BI dnd 
Change votre état en "ne pas déranger".
.TP
.BI ffc
Change votre état en "libre pour chatter".
.TP
.BI inv
Change votre état en "invisible".
.TP
.BI update
Actualise vos informations basiques (courriel, surnom, etc.).
.TP
.BI other
Actualise d'autres informations comme l'age et le sexe.
.TP
.BI about
Met à jour les informations de la section "à propos".
.TP
.BI set \ option\ valeur 
Donne a l'option
.IR option
la valeur 
.BR on
ou 
.BR off .
.IR option
peut être 
.BR color ,
.BR funny
ou 
.BR quiet .
.TP
.BI peek \ surnom 
Vérifie si l'utilisateur ayant pour surnom 
.IR surnom 
est actuellement connecté. Cette commande utilise un bug dans le protocole ICQ pour 
trouver ce renseignement;
aucune information excepté l'état de connexion ne peut être récupérée de cette manière.
.TP
.BI setr \ [numéro]
Paramètre votre numéro de groupe d'utilisateur aléatoire à
.IR numéro .
Sans argument, cette command affiche les groupes d'intérêts existants. 
.TP
.BI tcp \ commande\ uin|surnom 
Effectue la commande 
.IR commande 
sur l'utilisateur dont l'uin est
.IR uin
ou dont le surnom est
.IR surnom .
.IR commande
peut être 
.BR open
pour ouvrir une connexion de pair à pair avec TCP vers l'utilisateur, ou 
.BR close
pour fermer et réinitialiser une telle connexion, ou
.BR off
pour arrêter d'éssayer d'établir une telle connexion pour envoyer des messages 
jusqu'à ce qu'elle soit explicitement ouverte ou réinitialisée, ou  
.BR auto
pour obtenir la réponse automatique actuelle de l'utilisateur ou encore
.BR away ,
.BR na ,
.BR dnd ,
.BR occ
ou
.BR ffc
pour obtenir la réponse automatique de l'utilisateur pour un de ces états.
.TP
.BI conn \ [commande\ nr]
Affiche toutes les connexion, ou effectue la commande 
.IR command
sur la connexion 
.IR nr .
.IR commande 
peut être 
.BR open
ou 
.BR login
pour ouvrir cette connexion si elle ne l'est pas actuellement.

.SH VOIR AUSSI
.BR micq (1),
.BR micqrc (5)
.SH AUTEUR
Cette page de manuel a été écrite par James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca>
pour pouvoir consulter une référence de toutes les commandes de
.BR mICQ .
Cette page de manuel a été traduite par Julien Gilli 
.IR <jgilli@nerim.fr>.
