.\" $Id$
.\"This is the man page for ~/.micqrc."
.TH MICQRC 5 mICQ
.SH NAME
.B ~/.micq/micqrc
\- The configuration file for micq
.SH DESCRIPTION
This manual page describes the configuration file for micq. It consists
of several sections that are started by
.IR [section] ,
where
.I section
is the name of the section.
.SH CONNECTIONS
A
.B Connection
section describes a connection within ICQ. Typically, there are two of them,
that are related to each other: a connection to the ICQ server, and a
connection to listen to peer to peer communication.
.TP
.BI type \ type\ [auto]
Set the connection type to
.IR type ,
which can be
.B server
for a connection to the ICQ server, or
.B peer
for a connection listening to peer to peer communication. If
.I auto
is given, create this connection on startup. You presumable want to do this,
unless you have several UINs, then set this on the connection corresponding
to this UIN you are using.
.TP
.BI version \ nr
Set the version of the protocol used for this connection to
.IR nr .
Please note that for a server connections, versions
.BR 5 ,
.B 7
and
.B 8
are supported, and for peer to peer connections
.BR 6 ,
.B 7
and
.BR 8 .
.TP
.BI server \ server
Set the server to connect to to
.IR server .
This defaults to
.IR login.icq.com .
Unused for peer to peer connections.
.TP
.BI port \ port
Set the port to connect on the server to
.IR port ,
or the port to listen on for peer to peer connections to
.IR port .
.TP
.BI uin \ UIN
Set the UIN to log in with to
.IR UIN .
Unused for peer to peer connections.
.TP
.BI password \ [password]
Se the password to log in with to
.IR password .
Unused for peer to peer connections. If omitted, ask for password on startup.
Note: BeOS users may not omit the password.
.TP
.BI status \ nr
Set the status to be on log in in to
.IR nr .
Status can be:
.RS
.TP
0
online
.TP
1
away
.TP
5
not available
.TP
17
occupied
.TP
19
do not disturb
.TP
32
free for chat
.TP
256
invisible
.RE
.SH GENERAL
The
.B General
section includes the options for SOCKS 5, that may be eventually
moved to their own section, general options, and some strings to override.
.TP
.BI s5_use \ number
Set
.I number
to 0 to disable and 1 to enable.
.TP
.BI s5_host \ host
Connect to socks 5 proxy on host
.IR host .
.TP
.BI s5_port \ port
Connect to socks 5 proxy listening on port
.IR port .
.TP
.BI s5_auth \ number
Set
.I number
to 0 to omit authentification and 1 to do authentification.
.TP
.BI s5_name \ name
Identify as user
.I name
to socks 5 proxy.
.TP
.BI s5_pass \ password
Authenticate with password
.I password
to socks 5 proxy.
.PP
Now the options:
.TP
.BI verbose \ level
Set the verbosity level on startup to
.IR level .
.TP
.BI auto_away \ time
Set the time to set status to away after to
.I time
seconds. Set to
.I 0
to disable.
.TP
.BI Screen_width \ width
Set the default screen with to
.IR width .
If unset or
.IR 0 , \ 80
will be used. This is rarely needed as usually
the current screen width can be deduced on runtime.
.TP
.BI set \ delbs\ on|off
If set to
.BR on ,
let the delete character act as a backspace. When
.BR off ,
let it act as a delete character.
.TP
.BI set \ russian\ on|off
Disable or enable Russian character conversion between koi8-r/u and cp1251.
.TP
.BI set \ japanese\ on|off
Disable or enable Japanese character conversion between Shift-JIS and EUC.
.TP
.BI set \ funny\ on|off
Disable or enable "funny" messages.
.TP
.BI set \ color\ on|off
Disable or enable the use of colors.
.TP
.BI set \ hermit\ on|off
If set to
.BR on ,
ignore all messages from everyone not on your contact list.
.TP
.BI set \ log\ on|off
Disable or enable logging.
.TP
.BI set \ logonoff\ on|off
Whenn logging, disable or enable the logging of online/offline status changes.
.TP
.BI set \ auto\ on|off
Disable or enable automatic responses (reply messages).
.TP
.BI set \ uinprompt\ on|off
Disable or enable the use of the nick you last received a message from in the prompt.
.TP
.BI set \ linebreak\ type
The the line break type for incoming messages to
.IR type ,
which can be
.B simple
to just wrap lines as usual,
.B break
to have a line break before each message,
.B indent
to have a line break and indent the message and
.B smart
to have a line break only if the message doesn't fit on the current line.
.TP
.BI set \ tabs\ simple|cycle|cycleall
Selects the style of tab cycling. Older versions of mICQ only knew
.BR simple ,
which would only work with the
.B msg
command and would complete the command and cycle through all contacts that
messages had been sent to or received from. Already typed text after the
nick name was lost.
.B cycle
however cycles through all online contacts on your contact list. It keeps all
other input text intact, however it also doesn't add the default
.B msg
command.
.B cycleall
is like
.BR cycle ,
it just cycles through all, and not only online, contacts.
.PP
At last, some strings can be defined:
.TP
.BI logplace \ file|dir
Set the file to log into to
.IR file ,
or the directory to log into to
.IR dir .
Please note that a path is assumed to be a directory if it has a trailing
.IR / .
.TP
.BI sound \ on|off|cmd
Disable or enable beeping. If the argument is neither
.B on
nor
.BR off ,
it is assumed to be a program to execute instead of beeping.
.TP
.BI soundonline \ on|off|cmd
The same as above for users coming online.
.TP
.BI soundoffline \ on|off|cmd
The same as above for users going offline.
.TP
.BI receivescript \ cmd
The command to execute for incoming messages. Leave blank to do nothing.
.TP
.BI auto \ status\ string
Set the automatic reply in status
.I status
to
.IR string .
This option may be repeated for all possible values
.BR away ,
.BR na ,
.BR dnd ,
.BR occ ,
.BR inv ,
and
.B ffc
for
.IR status .

.SH STRINGS
The
.B Strings
section contains command renames.
.TP
.BI alter \ old\ new
Rename command
.I old
to
.IR new .
Note the old name may still be used, unless it conflicts with some
.I new
name.
For posible command names, see
.BR micq (7).
This option may be repeated as desired.

.SH CONTACTS
The
.B Contacts
section contains the contact list.
.TP
.I [*][~][^] uin nick
Make user with UIN
.I uin
known under the nick
.IR nick .
If
.B *
is given, the user may see you while you're invisible. If
.B ~
is given, let him see you as always offline. If
.B ^
is given, ignore this user.
If a uin occurs multiple times, all except the first are treated as aliases.

Note: the contact list has to be the last part of this file.
.SH SEE ALSO
.BR micq (1),
.BR micq (7)
.SH AUTHOR
This man page was written by James Morrison
.IR <ja2morrison@student.math.uwaterloo.ca> .
It was rewritten to match new config file syntax by Rüdiger Kuhlmann
.IR <micq@ruediger-kuhlmann.de> .
