.\" $Id$
.\"This is the man page for ~/.micq/micqrc."
.TH MICQ 7 mICQ
.SH NAME
mICQ - interactive commands
.SH DESCRIPTION
This manual page describes the commands that can be used within micq.  This
page holds the same information as the online help.
.SH COMMANDS
.TP
.BI trans \ [lang|nr]\ ...
Switch to the language 
.IR lang ,
given by iso code, or output translation string number
.IR nr .
To select the default language given by the environment
variables
.BR LANG ,
.B LC_ALL
and
.BR LC_MESSAGES ,
use
.BR ! ,
.B auto
or
.BR default .
To select no translation at all, use
.BR . ,
.B none
or
.BR unload .
To get debugging information, prefix it with
.BR debug .
To get funny messages, postfix it with
.BR _fun .
.sp
The files from ~/.micq/i18n/*.i18n take precedence over the global
ones, while the "funny" ones take precedence over the standard ones.
.sp
Actually you may specify as many arguments as you wish, e.g. to print
string number 117 in German and then switch back to default language,
use "trans de 117 default".
.TP
.B tabs 
Shows of a list of users you can tab through.
.TP
.B save
Saves current settings in the configuration file, which is
.IR ~/.micq/micqrc ,
unless specified otherwise.
Beware, it will clobber any comments in this file.
.TP
.BI r \ [message]
Reply to last message received.  Without
.I message
multi-line message mode is enabled.  To send the multi-line message, put
a period
.RB ( . )
on a line of its own.  To cancel the message, put a hash sign
.RB ( # )
on a line of its own.
.TP
.BI a \ [message]
Send a message to the last person you sent a message to.  See
.B r
for behaviour without
.IR message .
.TP
.BI msg \ uin|nickname\ [message]
Send a message to
.IR uin|nickname .
See
.B r 
for behaviour without
.IR message .
.TP
.BI url \ uin|nickname\ url\ message
Send a
.I message
regarding an
.I url
to
.IR uin|nickname .
.TP
.BI sms \ cell\ message
Send an SMS message
.I message
to cell phone number
.IR cell ,
which looks like +<country code><number>.
.TP
.B msga
Send a multiple line message to everyone on your list.  Use a period
.RI ( . )
on a line of its own to send the message, or a hash sign
.RI ( # )
on a line of its own to cancel the message.
.TP
.BI resend \ uin|nickname \fR...
Resend the last message to the new
.I uin
or
.IR nickname .
The argument may be repeated as often as needed.
.TP
.B uptime
Show the time mICQ has been running, plus some statistics.
.TP
.BI last \ [contact]
Show the last message 
received from
.IR contact ,
which can be a
.I uin
or a
.IR nickname ,
or from everyone who already sent a message.
.TP
.BI verbose \ [verb]
Set verbosity of mICQ to
.IR verb ,
or show the current verbosity. The verbosity level is a set of flags:
.RS
.TP
.B 8
Show protocol errors.
.TP
.B 16
Show creation and deletion of packets.
.TP
.B 32
Show added and removed queue events.
.TP
.B 64
Show created and deleted connections.
.TP
.B 256
Show v6 packets and their data.
.TP
.B 4096
Show v7/v8 packets.
.TP
.B 8192
Show the hexdump of v7/v8 packets.
.TP
.B 16284
Save those packets to disc.
.TP
.B 65536
Show peer-to-peer packets.
.TP
.B 131072
Show the hexdump of peer-to-peer packets.
.TP
.B 262144
Save those packets to disc.
.TP
.B 2097152
Show peer-to-peer handshake.
.TP
.B 4194304
Show I/O connection setup.
.RE

.RS
However, any non-zero verbose level will cause more information to be printed,
and any level greater than 1 even more.
.RE
.TP
.B clear
Clear the screen.
.TP
.BI sound \ [command]
Toggle sound on or off, or set to
.IR command .
.TP
.BI soundonline \ [command]
Toggle sound for users coming online on or off, or set to
.IR command .
.TP
.BI soundoffline \ [command]
Toggle sound for users going offline on or off, or set to
.IR command .
.TP
.B q
Quit mICQ.
.TP
.BI auto \ [on|off]
Turn auto reply messages on or off. If neither on or off is given
the auto reply messages are displayed.
.TP
.BI auto \ status\ message
Change auto reply message for status
.I status
to
.IR message .
.TP
.BI autoaway \ [timeout|on|off]
Set the timeout to
.IR timeout ,
or switch auto away
.I on
using the last used or default auto away time, or switch auto away
.I off
saving the current used auto away time. A timeout of 0 is equivalent to
.IR off .
If no argument is given, the current setting is displayed.
.TP
.BI alter \ command\ new
Make command initially or previously known as
.I command
from now on known as
.IR new .
.TP
.BI auth \ [req|grant|deny|add]\ uin|nickname
Grant or deny
.I uin|nickname
to add you to their list, request
.I uin|nickname
to allow you to add them to your contact list, or tell
.I uin|nickname
that you added hem to your contact list.
.TP
.BI rand \ number
Find a random user in interest group
.IR number .
.TP
.BI pass \ password
Changes your icq password to
.IR password . 
.br
Note: you need to
.B save
to make this persistent in case you save your password in your
.I ~/.micq/micqrc
file (see
.BR micqrc (7)),
or you will get a mismatched password
on your next login.
.TP
.B search
.TP
.BI search \ email
.TP
.BI search \ nick
.TP
.BI search \ first\ last
Search for a user with
.I email
as their email address, with
.I nick
as their nick (which mustn't contain an @), or with
.I first
as their first and
.I last
as their last name. If no argument is given, ask for
nick name, first name, last name, email address and a whole bunch of other data
to search for.
.TP
.BI add \ nickname\ alias
.TP
.BI add \ uin\ [nickname]
Add
.I uin
to your contact list as
.IR nickname ,
or add alias
.IR alias
for
.IR nickname .
If
.I nickname
is not given, use
.I uin
as nickname.
.br
Note: you need to
.B save
to make this persistent.
.TP
.BI rem \ alias
Remove the alias
.IR alias .
If
.IR alias
is the last alias for this contact, remove the contact completely.
.br
Note: you need to
.B save
to make this persistent.
.TP
.BI togvis \ nickname
Toggles whether
.I nickname
can see you even if you are invisible.
.TP
.BI toginvis \ nickname
Toggles whether you will be hidden for
.IR nickname .
.TP
.BI togig \ nickname
Toggles whether
.I nickname's
messages and status changes are ignored.
.TP
.BI f[inger] \ uin|nickname
.TP
.BI info \ uin|nickname
Show all white page info for
.IR uin|nickname .
.TP
.B e
List all people who are online in your contact list.
.TP
.B w
List all people in your contact list.
.TP
.B ee
List all people who are online in your contact list with more details.
.TP
.B ww
List all people in your contact list with more details. Also shows all aliases.
.TP
.B wide
List all people who are in your contact list in a screen wide format.
.TP
.B ewide
List all people who are online in your contact list in a screen wide format.
.TP
.B s \ [nickname]
Show your current status, or the given nickname's in detail, including all aliases.
.TP
.B i
List all the people on your ignore list.
.TP
.BI status \ [nickname]
Show the status of
.IR nickname .
This includes IP address, ICQ protocol version and connection type,
or list shortly UIN, nick, status and last online time for all contacts.
.sp
Note: This command is deprecated, use
.B s
or
.B ww
instead.
.TP
.BI reg \ password
Creates a new user account with password
.IR password .
.TP
.BI change \ [number\ [message]]
Changes your status to
.IR number .
Without a number it lists some available modes. Optionally
set auto response for this status to
.IR message .
.TP
.B online
Change status to "online".
.TP
.BI away \ [message]
Change status to "away". Optionally set auto response for this status to
.IR message .
.TP
.BI na \ [message]
Change status to "not available". Optionally set auto response for this status to
.IR message .
.TP
.BI occ \ [message]
Change status to "occupied". Optionally set auto response for this status to
.IR message .
.TP
.BI dnd \ [message]
Change status to "do not disturb". Optionally set auto response for this status to
.IR message .
.TP
.BI ffc \ [message]
Change status to "free for chat". Optionally set auto response for this status to
.IR message .
.TP
.B inv
Change status to "invisible".
.TP
.B update
Updates your basic user information (email, nickname, etc.).
.TP
.B other
Updates other user information like age and sex.
.TP
.B about
Updates your about user information.
.TP
.BI set \ option\ value
Set option
.I option
to either
.I on
or
.IR off .
.I option
can be
.BR color ,
.B funny
or
.BR quiet .
.TP
.BI peek \ nick
Check whether
.I nick
is actually online or not. Abuses a bug in the ICQ protocol to figure this out;
no additional information except online or offline can be found out this way.
.TP
.BI setr\ [number]
Sets your random user group to
.IR number .
Without argument, lists possible interest groups.
.TP
.BI peer \ command\ uin|nick
Operate command
.I command
on user given by UIN
.I uin
or nick name
.IR nick .
.RS
.TP
.B open
Open a peer to peer connection over TCP to the user.
.TP
.B close
Close and reset a peer to peer connection to the user.
.TP
.B off
Switch off trying to establish such a connection for sending
messages until it is explicitly opened or reset.
.TP
.B auto
Get the user's current auto response.
.TP
.B away
Get the user's current away auto response.
.TP
.B na
Get the user's current not available auto response.
.TP
.B dnd
Get the user's current do not disturb auto response.
.TP
.B occ
Get the user's current occupied auto response.
.TP
.B ffc
Get the user's current free for chat message.
.TP
.BI file \ file\ description
Send file
.I file
with description
.IR description .
.TP
.BI files \ [file\ as]...\ description
Send files to the user. There may be arbitrarely many
pairs of a physical file name
.I file
and the name to be presented to the peer,
.IR as .
If
.IR as
is
.RB ' / ',
the file name without the path is sent, and if it is
.RB ' . '
the same name is sent.
.RE
.TP
.BI conn \ [command\ nr]
List all connections, or operate
.I command
on connection
.IR nr .
.RS
.TP
.B open
Open the given, or the first server connection.
.TP
.B login
Open the given, or the first server connection.
.TP
.B close
Close the given connection. Temporary connections will get removed by this.
.TP
.B remove
Close and remove given (temporary) connection.
.TP
.B select
Select the given server connection as the current one.
.I nr
may be the connection number or the UIN used for the connection.
.RE
.TP
.BI contact \ [command]
Handle the server side contact list:
.RS
.TP
.B show
Download the server side contact list and just show it.
.TP
.B diff
Download the server side contact list and show only contacts (uin/nick pairs) that are not
in the local contact list.
.TP
.B import
Download the server side contact list and add all contacts to the local one.
.RE

.SH SEE ALSO
.BR micq (1),
.BR micqrc (5)
.SH AUTHOR
This man page was created by James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
for a reference to all interactive commands in 
.BR mICQ .
