.\"This is the man page for ~/.micqrc."
.\"There is also no global preferences such as micq.conf"
.\"However, ~/etc/micq.conf is an options with micq -E"
.Dd June 16, 2001
.Dt MICQ.CONF 5
.Os MICQ.CONF(5)
.\".TH micq.conf 5 "10 June 2001"
.Sh NAME
.Ic ~/.micqrc
\- The configuration file for micq
.Sh DESCRIPTION
This manual page describes the configuration file for micq.
.Sh BASIC CONFIGURATION
.Bl -tag -width Fl
.It Ic UIN Ar uin
Log in using UIN
.Ar uin .
.It Ic Password Op Ar password
Log in with password
.Ar password .
If omitted, ask for password at startup.
.It Ic Status Ar number
Be initially in status
.Ar status
after log in.
.Ar status
can be:
.br
0   Online
.br
1   Away
.br
5   Not Available
.br
17  Occupied
.br
19  Do Not disturb
.br
32  Free for Chat
.br
256 Invisible
.It Ic Server Ar server
Connect to ICQ server
.Ar server ,
e.g. icq1.mirabilis.com.
.It Ic Port Ar port
Listen on port
.Ar port
for incoming connections.
.Ar port
can be any unpriviledged port (> 1024), e.g. 4000.
.El
.Sh SOCKS 5
.Bl -tag -width Fl
.It Ic s5_use Ar number
Set
.Ar number
to 0 to disable and 1 to enable.
.It Ic s5_host Ar host
Connect to socks 5 proxy on host
.Ar host .
.It Ic s5_port Ar port
Connect to socks 5 proxy listening on port
.Ar port .
.It Ic s5_auth Ar number
Set
.Ar number
to 0 to omit authentification and 1 to do authentification.
.It Ic s5_name Ar name
Identify as user
.Ar name
to socks 5 proxy.
.br
.It Ic s5_pass Ar password
Authenticate with password
.Ar password
to socks 5 proxy.
.El
.Sh OPTIONS
.Bl -tag -width Fl
.It Ic Hermit
Only accept messages from people on your contact list.
.It Ic LogDir Ar path
Put log files into directory
.Ar path .
Default is the home directory.
.It Ic LogType Ar number
Choose logging style
.Ar number ,
which can be:
0 Disable logging
1 Log to LogDir/micq_log
2 Log to LogDir/micq.log/uin.log
3 Log to LogDir/micq.log/uin.log but don't log mode changes
.It Ic No_Color
Do not use colors in output.
.It Ic Auto
Turns auto reply messages on.
.It Ic Auto_Away Ar number
Wait
.Ar number
seconds before automatically changing status to away or na.
Use 0 to disable.
.It Ic Screen_Width Ar number
Set screen width to
.Ar number
columns, or 0 to auto detect.
.El
.Sh COMMAND IDENTIFIERS
The following items define the command names for the internal commands
whose defaults (unless noted otherwise) are defined in
.Xr micq 7 .
.Bl -tag -width Fl
.It Ic clear_cmd Ar alias
.It Ic message_cmd Ar alias
Default
.Ic msg .
.It Ic togig_cmd Ar alias
.It Ic iglist_cmd Ar alias
Default
.Ic i .
.It Ic info_cmd Ar alias
.It Ic quit_cmd Ar alias
Default
.Ic q .
.It Ic reply_cmd Ar alias
Default
.Ic r .
.It Ic again_cmd Ar alias
Default
.Ic a .
.It Ic list_cmd Ar alias
Default
.Ic w .
.It Ic online_list_cmd Ar alias
Default
.Ic e .
.It Ic away_cmd Ar alias
.It Ic na_cmd Ar alias
.It Ic dnd_cmd Ar alias
.It Ic online_cmd Ar alias
.It Ic occ_cmd Ar alias
.It Ic ffc_cmd Ar alias
.It Ic inv_cmd Ar alias
.It Ic search_cmd Ar alias
.It Ic status_cmd Ar alias
.It Ic auth_cmd Ar alias
.It Ic auto_cmd Ar alias
.It Ic add_cmd Ar alias
.It Ic togvis_cmd Ar alias
.It Ic change_cmd Ar alias
.It Ic save_cmd Ar alias
.It Ic alter_cmd Ar alias
.It Ic msga_cmd Ar alias
.It Ic url_cmd Ar alias
.It Ic update_cmd Ar alias
.It Ic about_cmd Ar alias
.El
.Sh AUTO RESPONSE MESSAGES
.Bl -tag -width Fl
.It Ic auto_rep_str_away Ar msg
Set the away auto reply message to
.Ar msg .
.It Ic auto_rep_str_na Ar msg
Set the not available auto replay message to
.Ar msg .
.It Ic auto_rep_str_dnd Ar msg
Set the do not disturb auto reply message to
.Ar msg .
.It Ic auto_rep_str_occ Ar msg
Set the occupied auto reply message to
.Ar msg .
.It Ic auto_rep_str_inv Ar msg
Set the invisible auto reply message to
.Ar msg .
.El
.Sh CONTACT LIST
.Bl -tag -width Fl
.It Ic Contacts
Start the contact list.
.El
.br
The contacts are of the form
.br
.Ar uin
.Ar nickname ,
.br
which will associate
.Ar nickname
to the user with user ID
.Ar uin .
Prefixing the
.Ar uin
with an asterisk
.Ic ( * )
will allow the user to see you while beeing invisible, while a
tilde
.Ic ( ~ )
will put the user on your ignore list of users that will never see you.
.br
Note: micq does not reject messages from people on your ignore list. Note:
the contact list has to be the last part of this file.
.Sh SEE ALSO
.Xr micq 1 ,
.Xr micq 7
.Sh Author
This man page was written by James Morrison
.Pa <ja2morrison@student.math.uwaterloo.ca> .
