.\"This is the man page for ~/.micqrc."
.Dd February 15, 2002
.Dt MICQRC 5
.Os MICQRC(5)
.\".TH micqrc 5 "February 15, 2002"
.Sh NAME
.Ic ~/.micq/micqrc
\- The configuration file for micq
.Sh DESCRIPTION
This manual page describes the configuration file for micq. It consists
of several sections that are started by
.Ic [section] ,
where
.Ic section is the name of the section.
.Sh CONNECTIONS
A
.Ic Connection
section describes a connection within ICQ. Typically, there are two of them,
that are related to each other: a connection to the ICQ server, and a
connection to listen to peer to peer communication.
.Bl -tag -width Fl
.It Ic type Ar type Op Ar auto
Set the connection type to
.Ar type ,
which can be
.Ic server
for a connection to the ICQ server, or
.Ic peer
for a connection listening to peer to peer communication. If
.Ar auto
is given, create this connection on startup. You presumable want to do this,
unless you have several UINs, then set this on the connection corresponding
to this UIN you are using.
.It Ic version Ar nr
Set the version of the protocol used for this connection to
.Ar nr .
Please note that for server connections, only version
.Ic 5
is supported, though
.Ic 8
is planned, and for peer to peer connections only
.Ic 6 .
.It Ic server Ar server
Set the server to connect to to
.Ar server .
This defaults to
.Ic icq.icq.com .
Unused for peer to peer connections.
.It Ic port Ar port
Set the port to connect on the server to
.Ar port ,
or the port to listen on for peer to peer connections to
.Ar port.
.It Ic uin Ar UIN
Set the UIN to log in with to
.Ar UIN .
Unused for peer to peer connections.
.It Ic password Op Ar password
Se the password to log in with to
.Ar password .
Unused for peer to peer connections. If omitted, ask for password on startup.
.It Ic status Ar nr
Set the status to be on log in in to
.Ar nr .
Status can be:
.br
0   Online
.br
1   Away
.br
5   Not Available
.br
17  Occupied
.br
19  Do Not disturb
.br
32  Free for Chat
.br
256 Invisible
.El
.Sh GENERAL
This section includes the options for SOCKS 5, that may be eventually
moved to their own section, general options, and some strings to override.
.Bl -tag -width Fl
.It Ic s5_use Ar number
Set
.Ar number
to 0 to disable and 1 to enable.
.It Ic s5_host Ar host
Connect to socks 5 proxy on host
.Ar host .
.It Ic s5_port Ar port
Connect to socks 5 proxy listening on port
.Ar port .
.It Ic s5_auth Ar number
Set
.Ar number
to 0 to omit authentification and 1 to do authentification.
.It Ic s5_name Ar name
Identify as user
.Ar name
to socks 5 proxy.
.br
.It Ic s5_pass Ar password
Authenticate with password
.Ar password
to socks 5 proxy.
.El
.sp
Now the options:
.Bl -tag -width Fl
.It Ic verbose Ar level
Set the verbosity level on startup to
.Ar level .
.It Ic auto_away Ar time
Set the time to set status to away after to
.Ar time
seconds. Set to
.Ic 0
to disable.
.It Ic Screen_width Ar width
Set the default screen with to
.Ar width .
If unset or
.Ic 0 , 80
will be used. This is rarely needed as usually
the current screen width can be deduced on runtime.
.It Ic set delbs Ar on|off
If set to
.Ar on ,
let the delete character act as a backspace. When
.Ar off ,
let it act as a delete character.
.It Ic set russian Ar on|off
Disable or enable Russian character conversion between koi8-r/u and cp1251.
.It Ic set japanese Ar on|off
Disable or enable Japanese character conversion between Shift-JIS and EUC.
.It Ic set funny Ar on|off
Disable or enable "funny" messages.
.It Ic set color Ar on|off
Disable or enable the use of colors.
.It Ic set hermit Ar on|off
If set to
.Ar on ,
ignore all messages from everyone not on your contact list.
.It Ic set log Ar on|off
Disable or enable logging.
.It Ic set logonoff Ar on|off
Whenn logging, disable or enable the logging of online/offline status changes.
.It Ic set auto Ar on|off
Disable or enable automatic responses (reply messages).
.It Ic set uinprompt Ar on|off
Disable or enable the use of the nick you last received a message from in the prompt.
.It Ic set linebreak Ar type
The the line break type for incoming messages to
.Ar type ,
which can be
.Ic simple
to just wrap lines as usual,
.Ic break
to have a line break before each message,
.Ic indent
to have a line break and indent the message and
.Ic smart
to have a line break only if the message doesn't fit on the current line.
.El
.sp
At last, some strings can be defined:
.Bl -tag -width Fl
.It Ic logplace Ar file|dir
Set the file to log into to
.Ar file ,
or the directory to log into to
.Ar dir .
Please note that a path is assumed to be a directory if it has a trailing
.Ic / .
.It Ic sound Ar on|off|cmd
Disable or enable beeping. If the argument is neither
.Ar on
nor
.Ar off,
it is assumed to be a program to execute instead of beeping.
.It Ic soundonline Ar on|off|cmd
The same as above for users coming online.
.It Ic soundoffline Ar on|off|cmd
The same as above for users going offline.
.It Ic receivescript Ar cmd
The command to execute for incoming messages. Leave blank to do nothing.
.It Ic auto Ar status Ar string
Set the automatic reply in status
.Ar status
to
.Ar string .
This option may be repeated for all possible values
.Ic away ,
.Ic na ,
.Ic dnd ,
.Ic occ ,
and
.Ic inv
for
.Ar status .
.El

.Sh STRINGS
This sections contains command renames.
.Bl -tag -width Fl
.It Ic alter Ar old Ar new
Rename command
.Ar old
to
.Ar new .
Note the old name may still be used, unless it conflicts with some
.Ar new name .
For posible command names, see
.Xr micq 7 .
This option may be repeated as desired.
.El
.Sh CONTACTS
This section contains the contact list.
.Bl -tag -width Fl
.It Ic [ Ar * ] [ Ar ~ ] [ Ar ^ ] Ar uin Ar nick
Make user with UIN
.Ar uin
known under the nick
.Ar nick .
If
.Ar *
is given, the user may see you while you're invisible. If
.Ar ~
is given, let him see you as always offline. If
.Ar ^
is given, ignore this user.
If a uin occurs multiple times, all except the first are treated as aliases.
.El
Note: the contact list has to be the last part of this file.
.Sh SEE ALSO
.Xr micq 1 ,
.Xr micq 7
.Sh Author
This man page was written by James Morrison
.Pa <ja2morrison@student.math.uwaterloo.ca> .
It was rewritten to match new config file syntax by Rüdiger Kuhlmann
.Pa <micq@ruediger-kuhlmann.de> .
