.\"This is the man page for ~/.micq/micqrc."
.\".TH MICQ 7 "February 15, 2002" "MICQ(7)"
.Dd February 15, 2002
.Dt MICQ 7
.Os MICQ(7)
.Sh NAME
micq interactive commands
.Sh DESCRIPTION
This manual page describes the commands that can be used within micq.  This
page holds the same information as the online help.
.Sh COMMANDS
.Bl -tag -width Fl
.It Ic trans Op Ar lang|nr ...
Switch to the language 
.Ar lang ,
given by iso code, or output translation string number
.Ar nr .
To select the default language given by the environment
variables
.Ic LANG ,
.Ic LC_ALL
and
.Ic LC_MESSAGES ,
use
.Ic \&! ,
.Ic auto
or
.Ic default .
To select no translation at all, use
.Ic \&. ,
.Ic none
or
.Ic unload .
To get debugging information, prefix it with
.Ic debug .
To get funny messages, postfix it with
.Ic _fun .
.sp
The files from ~/.micq/i18n/*.i18n take precedence over the global
ones, while the "funny" ones take precedence over the standard ones.
.sp
Actually you may specify as many arguments as you wish, e.g. to print
string number 117 in German and then switch back to default language,
use "trans de 117 default".
.It Ic tabs 
Shows of a list of users you can tab through.
.It Ic save
Saves current settings in the configuration file, which is
.Pa ~/.micq/micqrc ,
unless specified otherwise.
Beware, it will clobber any comments in this file.
.It Ic r Op Ar message
Reply to last message received.  Without
.Ar message
multi-line message mode is enabled.  To send the multi-line message, put
a period
.Ic ( . )
on a line of its own.  To cancel the message, put a hash sign
.Ic ( # )
on a line of its own.
.It Ic a Op Ar message
Send a message to the last person you sent a message to.  See
.Ic r
for behaviour without
.Ar message .
.It Ic msg Ar uin|nickname Ic Op Ar message
Send a message to
.Ar uin|nickname .
See
.Ic r 
for behaviour without
.Ar message .
.It Ic url Ar uin|nickname Ic Ar url Ar message
Send a
.Ar message
regarding an
.Ar url
to
.Ar uin|nickname .
.It Ic sms Ar cell message
Send an SMS message
.Ar message
to cell phone number
.Ar cell ,
which looks like +<country code><number>.
.It Ic msga
Send a multiple line message to everyone on your list.  Use a period
.Ic ( . )
on a line of its own to send the message, or a hash sign
.Ic ( # )
on a line of its own to cancel the message.
.It Ic uptime
Show the time micq has been running.
.It Ic last Op Ar contact
Show a list of users who have sent you messages or the last message
received from
.Ar contact ,
which can be a
.Ar uin
or a
.Ar nickname .
.It Ic verbose Op Ar verb
Set verbosity of micq to
.Ar verb ,
or show the current verbosity. The verbosity level is a set of flags:
.Bl -tag -width Fl
.It 128
Dump incoming and outgoing packets.
.It 256
Write incoming and outgoing server packets to disc (~/.micq/debug/packets).
.El
And some more.
.It Ic clear
Clear the screen.
.It Ic sound Op Ar command
Toggle sound on or off, or set to
.Ar command .
.It Ic soundonline Op Ar command
Toggle sound for users coming online on or off, or set to
.Ar command .
.It Ic soundoffline Op Ar command
Toggle sound for users going offline on or off, or set to
.Ar command .
.It Ic q
Quit micq.
.It Ic auto Op Ar on|off
Turn auto reply messages on or off. If neither on or off is given
the auto reply messages are displayed.
.It Ic auto Ar status message
Change auto reply message for status
.Ar status
to
.Ar message .
.It Ic autoaway Op Ar timeout
Toggles auto away, or set the timeout to
.Ar timeout .
.It Ic alter Ar command new
Make command initially or previously known as
.Ar command
from now on known as
.Ar new .
.It Ic auth Ar uin|nickname
Allow
.Ar uin|nickname
to add you to their list.
.It Ic rand Ar number
Find a random user in interest group
.Ar number .
.It Ic pass Ar password
Changes your icq password to
.Ar password . 
.br
Note: you need to
.Ar save
to make this persistent in case you save your password in your
.Pa ~/.micq/micqrc
file (see
.Xr micqrc 7 ) ,
or you will get a mismatched password
on your next login.
.It Ic search
.It Ic search Ar email
.It Ic search Ar nick
.It Ic search Ar first last
Search for a user with
.Ar email
as their email address, with
.Ar nick
as their nick (which can't contain an @), or with
.Ar first
as their first and
.Ar last
as their last name. If no argument is given, ask for
nick name, first name, last name, email address and a whole bunch of other data
to search for.
.It Ic add Ar uin Op Ar nickname
Add
.Ar uin
to your contact list as
.Ar nickname ,
or renames
.Ar uin
to
.Ar nickname .
If
.Ar nickname
is not given, use
.Ar uin
as nickname.
.br
Note: you need to
.Ar save
to make this persistent.
.It Ic rem Ar nick
Remove
.Ar nick
from your contact list.
.br
Note: you need to
.Ar save
to make this persistent.
.It Ic togvis Ar nickname
Toggles whether
.Ar nickname
can see you even if you are invisible.
.It Ic toginvis Ar nickname
Toggles whether you will be hidden for
.Ar nickname .
.It Ic togig Ar nickname
Toggles whether
.Ar nickname's
messages and status changes are ignored.
.It Ic info Ar uin|nickname
Show all white page info for
.Ar uin|nickname .
.It Ic w
List all people in your contact list.
.It Ic e
List all people who are online in your contact list.
.It Ic wide
List all people who are in your contact list in a screen wide format.
.It Ic ewide
List all people who are online in your contact list in a screen wide format.
.It Ic s
Show your current status.
.It Ic i
List all the people on your ignore list.
.It Ic status Ar nickname
Show the status of
.Ar nickname .
This includes IP address, ICQ protocol version and connection type.
.It Ic change Op Ar number
Changes your status to
.Ar number .
Without a number it lists some available modes.
.It Ic reg password
Creates a new user account with password
.Ar password .
.It Ic online
Change status to Online.
.It Ic away
Change status to Away.
.It Ic na
Change status to Not Available.
.It Ic occ             
Change status to Occupied.
.It Ic dnd 
Change status to Do not Disturb.
.It Ic ffc
Change status to Free for Chat.
.It Ic inv
Change status to Invisible
.It Ic update
Updates your basic user information (email, nickname, etc.).
.It Ic other
Updates other user information like age and sex.
.It Ic about
Updates your about user information.
.It Ic set Ar option Ar value
Set option
.Ar option
to either
.Ic on
or
.Ic off .
.Ar option
can be
.Ic color ,
.Ic funny
or
.Ic quiet .
.It Ic peek Ar nick
Check whether
.Ar nick
is actually online or not. Abuses a bug in the ICQ protocol to figure this out;
no additional information except online or offline can be found out this way.
.It Ic setr Op Ar number
Sets your random user group to
.Ar number .
Without argument, lists possible interest groups.
.It Ic tcp Ar command Ar uin|nick
Operate command
.Ar command
on user given by UIN
.Ar uin
or nick name
.Ar nick .
.Ar command
can be
.Ic open
to open a peer to peer connection over TCP to the user, or
.Ic close
to close and reset such a connection, or
.Ic off
to switch off trying to establish such a connection for sending
messages until it is explicitly opened or reset.
.It Ic conn Op Ar command Ar nr
List all connections, or operate
.Ar command
on connection
.Ar nr .
.Ar command
can be
.Ic open
or
.Ic login
to open this connection if it is not currently open.
.El
.Sh SEE ALSO
.Xr micq 1 ,
.Xr micqrc 5
.Sh AUTHOR
This man page was created by James Morrison
.Pa <ja2morrison@student.math.uwaterloo.ca>
for a reference to all interactive commands in 
.Ic micq .
