.\" $Id$ -*- nroff -*-
.\"  EN: micq.1,v 1.12 2002/08/21 08:50:56
.\"      ^^ <version of English man page this is in sync with>
.TH MICQ 1 mICQ ES
.SH NOMBRE
.B mICQ
\- un ligero cliente ICQ en modo texto
.SH SINOPSIS
.B micq
.I [-v[nivel]]
.I [-f archivo]
.SH DESCRIPCIÓN
.B mICQ
es un cliente ICQ en modo texto que soporta muchas de las caracteristicas
ofrecidas por el cliente de Mirabillis. mICQ permite cambiar la clave del
usuario, crear nuevas cuentas, actualizar la informacion del usuario, buscar
otros usuarios, etc.
.SH OPCIONES
.TP
.BI -v \ [nivel]
Activa el nivel de salida, seteandolo opcionalmente al numero indicado en
.IR nivel .
.TP
.BI -f \ archivo
Usa
.I archivo
como el archivo rc (el de configuracion).
.TP
.BI -l \ archivo|dir
Usa
.I archivo
como el archivo donde escribir el log, o usa
.I dir
como el directorio en donde crear archivos de log por usuario.
.TP
.B -?, -h
Muestran la ayuda.


.SH CARACTERISTICAS
.B mICQ
es muy portable y ha sido ejecutado en Linux, DOS, OS/2, Win32, BeOS, AmigaOS,
GNU HURD y cualquier otro sistema unix moderno.
.B mICQ version 0.4.9.2
fue probado y testeado en Linux, AIX, HPUX, Tru64, AmigaOS, parcialmente BeOS
y otros unixes; sin embargo los otros ports pueden o no funcionar, y
cualquiera que quiera probar es bienvenido.
.SH HISTORIA
.TP
16 Ago 1998
Matthew D. Smith publica micq al mundo. 
Siguieron 12 releases hasta el 25 de Septiembre de 1998.
.TP
05 Ene 2001
Matthew D. Smith muere en un accidente de auto.
Los usuarios continuan basandose en el codigo de Matthew,
formalizan mICQ bajo la licencia BSD y reinician el desarrollo.
.TP
10 Jun 2002
La version 0.4.9 es publicada bajo la licencia GPL, finalmente implementando
la nueva version 8 del protocolo ICQ, escrita por Rüdiger Kuhlmann.
.SH MAILING-LIST
La lista de correo de mICQ es
.IR micq-list@micq.org .
Mas informacion (metodos de suscripcion y archivos) se encuentra disponible en
.IR http://www.micq.org/pipermail/micq-list/ .
.SH DOWNLOAD
Via HTTP de
.IR http://www.micq.org/download .
.br
Para obtener la ultima version del CVS, utilizar el comando:
.br

cvs -d:pserver:anonymous@micq.org:/usr/local/cvsroot co micq
.br
.SH VER TAMBIEN
.BR micqrc (5),
.BR micq (7)
.SH ARCHIVOS
.TP
.I ~/.micqrc
Viejo archivo de configuracion - obsoleto.
.TP
.I ~/.micq/micqrc
Archivo de configuracion para mICQ.
.TP
.I PREFIX/share/micq/*.i18n
Archivos de internacionalizacion, contienen las traducciones de las salidas de
mICQ.
.TP
.I ~/.micq/i18n/*.i18n
Versiones locales de los archivos recien mencionados.
.TP
.I ~/.micq/history/
Ubicacion por default donde los archivos de log son creados.

.SH BUGS
or favor, enviar reportes de bugs o comentarios a Rüdiger Kuhlmann
.I <micq@ruediger-kuhlmann.de>
(en Aleman o en Ingles).
.SH AUTOR
Este manual fue derivado por James Morrison
.I <ja2morrison@student.math.uwaterloo.ca>
del minimo escrito por Jordi Mallach
.I <jordi@sindominio.net>
para Debian GNU/Linux.
Este manual fue traducido por Alberto Bertogli
.IR <albertogli@telpin.com.ar> .

