# $Id$
#

all:	
	
clean:	
	
indent:	
	

install:
	@if [ $$UID = 0 ]; then \
	 mkdir /usr/local/share/micq ; \
	 cp *.i18n /usr/local/share/micq ;\
	else \
	 mkdir ${HOME}/.micq/ ; \
	 cp *.i18n ${HOME}/.micq/ ; \
	fi
