
--brace-indent0
--continuation-indentation3
--case-indentation4
--indent-level4
--continuation-indentation3
--line-length100

--blank-lines-after-procedures 
--blank-before-sizeof
--case-brace-indentation4
--continue-at-parentheses
--leave-preprocessor-space
--no-blank-lines-after-commas
--dont-cuddle-do-while
--dont-cuddle-else
--dont-break-function-decl-args
--dont-break-procedure-type
--honour-newlines
-nut
--space-after-procedure-calls
--braces-after-if-line
